### ISSUE TITLE
is Deployment-Resources-Must-Not-Be-Debug correct?

### ISSUE THREAD

**Issue by tfitzmac** [Azure/arm-ttk#105]
It seems like the new test Deployment-Resources-Must-Not-Be-Debug is not correct. The fail unit test shows debugSetting like:

{
    "$schema":  "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "resources":  [
        {            
            "debugSetting":  "requestContent",
            "type":  "Microsoft.Resources/deployments"
        }
    ]
}

But, debugSetting is in the properties and it has a detailLevel property. I would think the following template should fail but it passes:

{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "storageAccountName": {
      "type": "string"
    }
  },
  "resources": [
    {
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2019-10-01",
      "name": "nestedTemplate1",
      "properties": {
        "mode": "Incremental",
        "debugSetting": {
          "detailLevel": "requestContent"
        },
        "template": {
          "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
          "contentVersion": "1.0.0.0",
          "resources": [
            {
              "type": "Microsoft.Storage/storageAccounts",
              "apiVersion": "2019-04-01",
              "name": "[parameters('storageAccountName')]",
              "location": "West US",
              "sku": {
                "name": "Standard_LRS"
              },
              "kind": "StorageV2"
            }
          ]
        }
      }
    }
  ],
  "outputs": {
  }
}

**Comment by bmoore-msft** [comment]
good catch
