### ISSUE TITLE
problems with new formatter

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#106]
1) The first line of test results does not start on a new line:

> Validating github-enterprise\azuredeploy.json  deploymentTemplate    [+] adminUsername Should Not Be A Literal (225 ms)

2) The unreferenced var test has appended debug spew

> ##[error]        Unreferenced variable: vmStorageAccountContainerName##vso[task.logissue 

> Not sure if that's present on other tests

3) it look like there are a number of places where newline is not being honored:

>   [-] IDs Should Be Derived From ResourceIDs (120 ms)
        Property: "frontEndIPConfigID" must use one of the following expressions for an resourceId property:      extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid        Property: "id" must use one
of the following expressions for an resourceId property:

>  Microsoft.Compute/virtualMachines uses a preview version ( 2016-04-30-preview ) and there are more recent versions available.        Valid Api Versions:

4) switch the default colors to be Bright Green and Bright Red, Bright Yellow

**Comment by StartAutomating** [comment]
@bmoore-msft the fix is in #108
