### ISSUE TITLE
The documentation link in README.md points to a 404

### ISSUE THREAD

**Issue by iamalexmang** [Azure/arm-ttk#115]
Please revise the link to docs.microsoft.com, as it currently renders into a 404 error page.

![image](https://user-images.githubusercontent.com/5773281/85339591-20dfad00-b4ed-11ea-87c6-f382ba0ccae5.png)

**Comment by bmoore-msft** [comment]
@iamalexmang - can you clarify?  Which link?  Which readme?

**Comment by iamalexmang** [comment]
Everything seems fine now. It was a link in the README.MD fine in the root of the repository, linking to https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/test-toolkit. Previously, that link was 404'ing.

**Comment by bmoore-msft** [comment]
got it, thx for confirming...
