### ISSUE TITLE
variables-must-be-referenced test failing on ros-vm-windows

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#116]
Running on the following sample:

https://github.com/Azure/azure-quickstart-templates/tree/master/ros-vm-windows

returns: 
Cannot bind argument to parameter 'Name' because it is an empty string.

My guess is the array variables (the are correctly referenced in the template).

**Comment by bmoore-msft** [comment]
@StartAutomating can we front load this one?

**Comment by StartAutomating** [comment]
Yes.  Should be able to make the bandwidth this evening.

**Comment by StartAutomating** [comment]
@bmoore-msft PR #118 is in.  Added a test case for the type of problem.
