### ISSUE TITLE
IDs Should Be Derived From ResourceIDs

### ISSUE THREAD

**Issue by jf781** [Azure/arm-ttk#123]
Getting this error on a number of ARM templates and it predominately relates to those that use App Registration IDs.   For example the AKS with Azure AD integration template.   

```json
"aadProfile": {
                    "clientAppID": "[parameters('AAD_ClientAppID')]",
                    "serverAppID": "[parameters('AAD_ServerAppID')]",
                    "tenantID": "[parameters('AAD_TenantID')]",
                    "serverAppSecret": "[parameters('AAD_ServerAppSecret')]"
                },
```

Is there any way to add an exclusion to the "allowedExpressions " hash table to account for that allows "AppID" or some other variant?   

Alternatively, is there a way to create a known exception/allowed list?  I have a number of other templates that get flagged for this for parameters like "ObjectID" and "ClientID".   

Thank you for all the hard work as well.  This is a great tool and I really appreciate it the effort that is being spent on it!!

**Comment by bmoore-msft** [comment]
You can add exceptions here:

https://github.com/Azure/arm-ttk/blob/master/arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1#L67

That will change the test so that it works for everyone...  Please submit a PR ;)

**Comment by jf781** [comment]
Thanks Brian - PR #124 submitted.    
Not sure why I didn't think of that in the first place.....

**Comment by bmoore-msft** [comment]
merged
