### ISSUE TITLE
api versions test on locks

### ISSUE THREAD

**Issue by tw3lveparsecs** [Azure/arm-ttk#126]
When using the latest api version for locks on any resource, the api version test fails.

Example of lock on vnet error below.

Api versions must be the latest or under 2 years old (730 days) - API version 2016-09-01 of Microsoft.Network/virtualNetworks/Microsoft.Network/virtualNetworks/providers/locks is 1406 days old in template file

Latest version of locks: https://docs.microsoft.com/en-us/azure/templates/microsoft.authorization/2016-09-01/locks

**Comment by bmoore-msft** [comment]
Can you copy/paste the resource body? I think this is for extension resources, want to make sure (code disambiguates everything)

**Comment by tw3lveparsecs** [comment]
`{
    "type": "Microsoft.Network/virtualNetworks/providers/locks",                                   
    "name": "[concat(parameters('vnetname'), '/Microsoft.Authorization/', parameters('vnetname'), '-lock')]",
    "dependsOn": [
        "[resourceId('Microsoft.Network/virtualNetworks', parameters('vnetname'))]"
    ],
    "apiVersion": "2016-09-01",
    "properties": {
        "level": "CannotDelete"
    }
}`

**Comment by tw3lveparsecs** [comment]
just found another example, if it helps.

Recovery Services Vaults. 
Only has one api available at the moment and api versions test results in a fail. Error below.

Microsoft.PowerShell.Commands.WriteErrorException: Api versions must be the latest or under 2 years old (730 days) - API version 2016-06-01 of Microsoft.RecoveryServices/vaults is 1499 days old in template file.

https://docs.microsoft.com/en-us/azure/templates/microsoft.recoveryservices/2016-06-01/vaults

`{
  "name": "string",
  "type": "Microsoft.RecoveryServices/vaults",
  "apiVersion": "2016-06-01",
  "location": "string",
  "tags": {},
  "identity": {
    "type": "string"
  },
  "properties": {
    "upgradeDetails": {}
  },
  "sku": {
    "name": "string"
  }
}`

**Comment by bmoore-msft** [comment]
Microsoft.RecoveryServices/vaults is actually a correct message - the docs are out of date.  You can see what Azure support by using:

az provider list -o json

The error message from the TTK should give you the supported apiVersions from it's cache

**Comment by bmoore-msft** [comment]
The scope property also needs to be checked...  and example:

https://github.com/Azure/azure-quickstart-templates/blob/master/101-data-share-share-storage-account/azuredeploy.json#L130

So there are 2 variations of how to check apiVersions for extension resources

**Comment by bmoore-msft** [comment]
The tricky one here is the syntax that does not use the scope property:

```json
                   "resources": [
                        {
                            "type": "Microsoft.Network/virtualNetworks/subnets/providers/roleAssignments",
                            "apiVersion": "2020-04-01-preview",
                            "name": "[concat(parameters('existingVirtualNetworkName'), '/', parameters('existingSubnetName'), '/Microsoft.Authorization/', guid(resourceGroup().id, deployment().name))]",
                            "properties": {
                                "roleDefinitionId": "[variables('builtInRole')[parameters('builtInRoleType')]]",
                                "principalId": "[parameters('existingServicePrincipalObjectId')]",
                                "scope": "[variables('vnetSubnetId')]"
                            }
                        }
                    ]
                }
```

**Comment by StartAutomating** [comment]
@bmoore-msft :  This may be fixed in the most recent build.

I get:

The apiVersion 2016-09-01 was not found for the resource type: Microsoft.Authorization

**Comment by bmoore-msft** [comment]
let's add a test case and make sure ;)
