### ISSUE TITLE
each resource control that allows for "hideExisting" must have a condition property on it's resource

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#142]
for something like storage, networking, publicIp - if hideExisting=false (or the property is omitted) then the resource in the template must have a condition property.

Watch for nested templates.

If I have a storageAccount control in CUID and that control has the property hideExisting=false or the hideExisting property is omitted...
Then, when that resource is provisioned in the template, that resource must have a condition property on it. 

Note that, the resource could be in any of the templates in a deployment (mainTemplate or a nested one).

We should defer this until the next round...

**Comment by StartAutomating** [comment]
Do we have a list of resources that have hideExisting?

**Comment by StartAutomating** [comment]
I believe this has already been merged and can be resolved.
