### ISSUE TITLE
RBAC must not assign the "owner" role to an MSI

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#144]
1) find all resources that do role assignments (type will be direct type or an extension resource) - we might be able to search for the property instead but it might not be unambiguous
2) make sure the roleId property does not contain the guid for the owner role (8e3af657-a8ff-443c-a75c-2fe8c4bcb635)
3) check that the principal is an MSI (Managed Service Identity)

**Comment by StartAutomating** [comment]
@bmoore-msft

> 1. find all resources that do role assignments (type will be direct type or an extension resource) - we might be able to search for the property instead but it might not be unambiguous

Which resources?

> 2. make sure the roleId property does not contain the guid for the owner role (8e3af657-a8ff-443c-a75c-2fe8c4bcb635)
👍 

> 3. check that the principal is an MSI (Managed Service Identity)
Refresh me on how we make this mapping.  We also may want to consider if we can make some of the relationship mapping part of a function.

**Comment by StartAutomating** [comment]
Covered by BPA
