### ISSUE TITLE
UIDef: VM Image details (on size control) must match the image used in the template

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#153]

**Comment by StartAutomating** [comment]
@bmoore-msft we may already have this.  Does this look right?  [VMSizes-Must-Match-Template.test.ps1](https://github.com/Azure/arm-ttk/blob/master/arm-ttk/testcases/CreateUIDefinition/VMSizes-Must-Match-Template.test.ps1)
