### ISSUE TITLE
don't allow uniqueString() at the beginning of an expression that requires a letter

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#161]
need to figure out what expressions require a letter - or we could over-reach and never allow it at the beginning

**Comment by bobbyangers** [comment]
This could be flagged as a warning

**Comment by StartAutomating** [comment]
@bmoore-msft 👍 .  I think we could over-reach here and provide an exclusion parameter (or allow other excludes),  And also mark it as a warning.

**Comment by bobbyangers** [comment]
@bmoore-msft how to identify **expression require a letter** ?
Most usage will involve the "recommended" usage (I would tend to think):
[concat('prefix', uniqueString(resrouceGroup().id))]

So I think, simply flagging as a warning and using **[uniqueString(...)]** would be ok.

**Comment by bmoore-msft** [comment]
TBH the only way to identify is from the rest-api-specs - some (most?) should be documented but I don't know if they are doc'd in one place...
