### ISSUE TITLE
Test for API version is failing for -preview

### ISSUE THREAD

**Issue by jpodoba** [Azure/arm-ttk#169]
https://github.com/Azure/arm-ttk/blob/167a704d70743bd4c05a7b1fd4e69c7a549fd954/arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1#L134

Hi there I found an issue about API in templates and **"-preview"** version of them.

It looks the test will always fail when the pattern of API version is:

`($av.ApiVersion -like '*-*-*-*')`

That looks fine at the beginning but some providers like in my example **"Microsoft.Sql/servers"** have all versions in preview. [All available versions](https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/2019-06-01-preview/servers)

There is one which is not in preview **"2014-04-01"** but unfortunately with that versions test will fail any way because is older than **730** days.

I'm using the Azure DevOps extensions from market place created by @sam-cogan  but he just pull the original tests from main one so the issue is in test it self.

**Comment by bmoore-msft** [comment]
@jpodoba - I'm not sure I understand the issue... is it that SQL has no apiVersions, that are not preview, that are less than 2 years old?  So in the scenario where I want to make sure I'm using the latest "non-preview-version" the ttk will flag it if the only non-preview version is > 2 years old?

**Comment by jpodoba** [comment]
> @jpodoba - I'm not sure I understand the issue... is it that SQL has no apiVersions, that are not preview, that are less than 2 years old?  So in the scenario where I want to make sure I'm using the latest "non-preview-version" the ttk will flag it if the only non-preview version is > 2 years old?
> 

There is one non-preview API version from 2014-04-01 and other test which checks how old is API will fail.

**Comment by bmoore-msft** [comment]
@jpodoba - Ok, I'm with you... a few things are at play here...

SQL tends to not remove the -preview from their apiVersions when they GA...  What we'd need to do here is make sure that if there are only preview apiVersions in the last 2 years that we grab the latest non-preview on as well (when determining valid versions) - this would be correct given the reasoning behind the test, but SQL is an outlier.

The other option would be provide a switch for for you to state that apiVersion errors are warnings and not errors when running the tests - which may apply to more than just this scenario...

Thoughts?

**Comment by jpodoba** [comment]
Thanks for respond @bmoore-msft 

In my opinion first option looks more reliable. The second option with switch will not works if we're using those test in extensions like created by @sam-cogan. If we start add extra switch for each tests it could be hard to maintain in future.

**Comment by bmoore-msft** [comment]
believe this one is fixed...  feel free to reopen if not...
