### ISSUE TITLE
Missing Folder name in Pester output. Variable scope issue.

### ISSUE THREAD

**Issue by MartinAngelov** [Azure/arm-ttk#172]
When using -Pester switch the output in line below is missing, $TemplateName value is null.

https://github.com/Azure/arm-ttk/blob/c395ce4e316bed2327753d5447a71a66202c313e/arm-ttk/Test-AzTemplate.ps1#L493

The value should be populated in line:
https://github.com/Azure/arm-ttk/blob/c395ce4e316bed2327753d5447a71a66202c313e/arm-ttk/Expand-AzTemplate.ps1#L162

The variable name is a little misleading as it is actually the name of the Folder containing the template file.

The problem is the scope of the Variable and the way functions are added/imported with **dot sourcing** in arm-ttk.psd1.

As a work around it could be changed to $Global scope variable.

I think if all script `.ps1 ` files that contain separate functionalities will be better to be changed to module `.psm1` files and use `Export-ModuleMember` for more flexibility and explicit control of what is exported and needed outside of the "helper" function itself .

**Comment by bmoore-msft** [comment]
@MartinAngelov - can you provide the version of Pester you're seeing this in?

**Comment by MartinAngelov** [comment]
@bmoore-msft It's 4.10.1.

**Comment by bmoore-msft** [comment]
I'm not sure I understand the issue...  when I run with -pester on 4.10.1 - the output looks as expected.

![Untitled](https://user-images.githubusercontent.com/10090014/89580131-80262200-d7fa-11ea-8c86-c54bc8896258.png)

Pester 5.x is a mess (breaking changes in 5.0) but aside from that what am I missing?

**Comment by MartinAngelov** [comment]
@bmoore-msft , the actuall issue is visble when outputing to NUnit xml format and upload in Azure DevOps.

Here is a sample output of test uploaded in AzDO:
![image](https://user-images.githubusercontent.com/6962522/89622110-2e81a400-d89b-11ea-9e42-db1e66a7705e.png)

And here is a sample when I have set the variable as global  $TemplateName (quotes also added by me to emphasize):
![image](https://user-images.githubusercontent.com/6962522/89622181-4fe29000-d89b-11ea-8e6a-1eeab69f618f.png)

**Comment by bmoore-msft** [comment]
ok, so in NUnit output, you'd like to see the full path (or full path from the root of the test execution)?

Also, how are you getting that NUnit - are you invoking the ttk from within a pester

related to #110

**Comment by StartAutomating** [comment]
This was addressed in improvements to the formatting.
