### ISSUE TITLE
add warning when a template file has incorrect schema (which cause us to skip the file in testing)

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#175]
If I have a template file that mistakenly has an incorrect or missing $schema property, we will skip the file in testing (we use the schema to determine the file type).  In one recent PR we had a template file that used the parameter file schema, so it wasn't tested.

A simple check we can do:
- the file is a json file
- the file has resources array at the root
- the file does NOT have one of the _n_ valid schemas for a template

If those conditions are met, throw an error.

Not this may be too restrictive because it's technically possible to have a json file with a resources array at the root, but that seems rare in practice.  If it causes problems we can turn it into a warning, but for now let's make it an error.

**Comment by StartAutomating** [comment]
@bmoore-msft 👍
