### ISSUE TITLE
Diagnostics settings with VMs failing

### ISSUE THREAD

**Issue by tw3lveparsecs** [Azure/arm-ttk#179]
When adding diagnostic settings to virtual machines as per article: https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/diagnostics-template it fails on test "DeploymentTemplate Must Not Contain Hardcoded Uri". 

This is due to the configuration containing the code below.

```json
"storageAccountEndPoint": "https://core.windows.net"
```

**Comment by lakshayarora476** [comment]
Try implementing Storage Account SAS token instead of storage account key.
"storageAccountSasToken": "SAS access token"


(Append a backslash)"storageAccountEndPoint": "https://core.windows.net/". Also, try if you enclose URI in a parameter.

**Comment by tw3lveparsecs** [comment]
@lakshayarora476 appending a slash and enclosing URI in a parameter still results in a test failure. 
I would expect the SAS token method to work but didn't want to go through the trouble of generating one each time i deploy a VM.

Happy to use SAS tokens if that's the recommended best practice but all current documentation and quick start templates i have found all use storage keys.

**Comment by bmoore-msft** [comment]
For that property you would use:

[environment().suffixes.storage] (returns core.windows.net)

and concat https on the front if needed.

We should update the error message to point folks to the environment() function

**Comment by tw3lveparsecs** [comment]
ok great i will give that a shot and agreed an updated error message would be nice.

**Comment by tw3lveparsecs** [comment]
just closing the loop. The [environment().suffixes.storage] method works and can confirm concat https on the front was also needed.

**Comment by StartAutomating** [comment]
@bmoore-msft: Looks like there's a viable fix for this particular template and that this issue could be closed.
