### ISSUE TITLE
Add feature to skip files and folders

### ISSUE THREAD

**Issue by WouterDeKort** [Azure/arm-ttk#180]
I would like to have a feature where I can not only skip certain tests but skip testing a specific file or a complete folder.

The scenario where I need this is that some tests don't apply to an ARM template (for example, the location of an ActionGroup should be hardcoded to global) or that I have some ARM templates developed by a third party that I don't want to modify.

**Comment by bmoore-msft** [comment]
@WouterDeKort - ack on the first part, excluding a folder (you can already exclude tests)...

Just want to be sure on the second part.  "Global" as a location valid should not be flagged is invalid - if you're seeing that, could you open a separate issue for it?

**Comment by WouterDeKort** [comment]
@bmoore-msft I've submitted a new issue for the 'global' issue: https://github.com/Azure/arm-ttk/issues/185

Can the ask for excluding files and folders be put on the backlog? Any idea if you'll be able to deliver this?

Thanks

**Comment by bmoore-msft** [comment]
yes, this is still a valid ask, just want to separate the two issues...  will keep this on the backlog.

**Comment by StartAutomating** [comment]
@bmoore-msft:  This should be handled by the fixes for #309 ( in PR #413 )

**Comment by bmoore-msft** [comment]
now a duplicate
