### ISSUE TITLE
Error 1530

### ISSUE THREAD

**Issue by JFolberth** [Azure/arm-ttk#181]
Running via Azure Pipeline and the template is passing all checks but logs show: 
`##[error]Invalid object passed in, ':' or '}' expected. (1530): {`

**Comment by bmoore-msft** [comment]
@JFolberth - do you have a repro?  We run this in AzDO for QuickStarts and aren't seeing said issue...

**Comment by JFolberth** [comment]
@bmoore-msft  Yup! Here's the 
ADO pipeline:https://dev.azure.com/jfolberth/HDCDemo/_build/results?buildId=59&view=results

And here's the git repo w/azuredeploy.json:
https://github.com/JFolberth/HDCDevOps/tree/master/Infrastructure/HDCDemoApp/HDCDemoApp

**Comment by JFolberth** [comment]
So that extra " in my variables was the issue.....not sure though if ttk should have passed with invalid deployment file....
