### ISSUE TITLE
Publish to Powershell Gallery

### ISSUE THREAD

**Issue by fowl2** [Azure/arm-ttk#182]
It'd be great if this could be uploaded to PowerShell Gallery so we could `Install-Module` it just like every other cmdlet instead of forking or having to figure out how to download it from github in our devops scripts.

Thanks!

**Comment by bmoore-msft** [comment]
this is planned for this semester

**Comment by Splaxi** [comment]
@bmoore-msft 

Do you have any update on this? Do you need a hand to set it up?

**Comment by asears** [comment]
Any updates on this?  Seems to have been deprioritized?

**Comment by JustinGrote** [comment]
It's not a big deal to publish to the gallery, heck I'll publish it as a pre-release module for you and you can take over the package when you are ready.

**Comment by bmoore-msft** [comment]
@MarcusFelling to see if he can pick this up again...

**Comment by asears** [comment]
How does the installed module work with custom tests, or how can custom tests be injected after import?

**Comment by bmoore-msft** [comment]
Good question... 

@StartAutomating ?

**Comment by StartAutomating** [comment]
@asears
@bmoore-msft 

Looking thru the code, it should be possible to add your own test cases/groups, though not as simple and elegant as we'd like it to be.

Test-AzTemplate -TestCase/-TestGroup will allow you to pass a dictionary of additional test cases and groups.

-TestCase should contain the name/ScriptBlock or Path to test
-TestGroup should contain the list of tests in each group.
Where things get annoying is that while -TestCase is additive, -TestGroup overwrites.  Ergo providing your own test cases _and_ using the built in ones would be annoying.

This could be made more elegant by having something like a -TestDirectory parameter, which would read an additional directory tree's worth of tests (containing it's own /deploymentTemplate and /createUIDefinition subfolders).

I've created Issue #329  to track this specifically.

**Comment by FallenHoot** [comment]
Any update on this? Would be great to have a simple `Install-Module`.

**Comment by kevinCefalu** [comment]
> 
> 
> Any update on this? Would be great to have a simple `Install-Module`.

Seconded! Would be interested in assisting if you are looking for help!

**Comment by drewkg** [comment]
Any update on this? I really need to be able to simply specify the version as just getting the latest is causing my pipelines to fail and I need to manage to update of the module just like any dependency.

**Comment by Splaxi** [comment]
I use this, to download the latest release directly from github, for all my pipelines - while waiting for the publish to powershellgallery.com to happen 🤞

**Comment by StartAutomating** [comment]
We will release on GitHub.
