### ISSUE TITLE
Latest api version of 2018-09-01 rejected.

### ISSUE THREAD

**Issue by Dorus** [Azure/arm-ttk#183]
Right now i get:

```Text
Microsoft.PowerShell.Commands.WriteErrorException: Api versions must be the latest or under 2 years old (730 days) - API version 2018-09-01 of Microsoft.Network/privateDnsZones is 730 days old
Microsoft.PowerShell.Commands.WriteErrorException: Api versions must be the latest or under 2 years old (730 days) - API version 2018-09-01 of Microsoft.Network/privateDnsZones/SOA is 730 days old in template file private-dns-zone.json
Microsoft.PowerShell.Commands.WriteErrorException: Api versions must be the latest or under 2 years old (730 days) - API version 2018-09-01 of Microsoft.Network/privateDnsZones/virtualNetworkLinks is 730 days old in template file vnet-link.json
```

for resources where the latest api version is 2018-09-01. These should be ignored.

**Comment by marrobi** [comment]
Same for `Microsoft.Network/privateDnsZones` . Blocking our pipelines this morning.

**Comment by bmoore-msft** [comment]
The error response from that test should output the valid apiVersions... in this case it looks like the latest apiVersion for those is 2020-01-01

((get-AzResourceProvider -ProviderNamespace 'Microsoft.Network').ResourceTypes | where-object{$_.ResourceTypeName -eq "privateDNSZones"}).apiVersions

**Comment by marrobi** [comment]
Thanks.

I was reading https://docs.microsoft.com/en-us/azure/templates/microsoft.network/privatednszones

**Comment by bmoore-msft** [comment]
ack - unfortunately the things we humans normally consume (specs, docs, schemas) often lag the service (though this one is pretty odd)...

In this case is looks like NRP has not updated the REST API specs (so docs don't know about it)...  If you don't mind filing an issue there it won't hurt.
https://github.com/Azure/azure-rest-api-specs
