### ISSUE TITLE
global default value for location parameter is flagged

### ISSUE THREAD

**Issue by WouterDeKort** [Azure/arm-ttk#185]
The following ARM snippet is flagged:

 "location": {
      "type": "string",
      "defaultValue": "global" , 
      "metadata": {
        "description": "Location where the Action Group is created"
      }
    }

Is this by design? Global is required for deploying an Action Group.

**Comment by bmoore-msft** [comment]
fix in #186

**Comment by WouterDeKort** [comment]
Thanks!

**Comment by bmoore-msft** [comment]
merged
