### ISSUE TITLE
length constraint not detected in regex tests

### ISSUE THREAD

**Issue by amergey** [Azure/arm-ttk#187]
Hello,
in createUiDefinition.json, I have defined following password box with a regex which seems to be valid 
```
{
                                "name": "databaseServerPassword",
                                "type": "Microsoft.Common.PasswordBox",
                                "label": {
                                    "password": "Database server Password",
                                    "confirmPassword": "Confirm password"
                                },
                                "toolTip": "Password for the database server administrator.",
                                "constraints": {
                                    "required": true,
                                    "regex": "^(?=.{8,128})((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])|(?=.*\\d)(?=.*[a-zA-Z])(?=.*[\\W_])|(?=.*[a-z])(?=.*[A-Z])(?=.*[\\W_])).*.*$",
                                    "validationMessage": "Password must have 3 amongs 1 lower case, 1 upper case, 1 number and 1 special character, and must be between 8 and 128 characters."
                                },
                                "options": {
                                    "hideConfirmation": false
                                },
                                "visible": true
                            }
```

But following test is failing even their is a length constraint

_[-] PasswordBoxes Must Have Min Length (169 ms)                                                                                                                                PasswordBox 'databaseServerPassword' regex does not have a length constraint._

similarly 

this 
```
{
                "name": "instanceName",
                "type": "Microsoft.Common.TextBox",
                "label": "xDM Instance name",
                "toolTip": "Prefix used for all resource names in the resource group.",
                "defaultValue": "xdm",
                "constraints": {
                    "required": true,
                    "regex": "^[0-9a-z][0-9a-z-]{1,18}[0-9a-z]$",
                    "validationMessage": "[3..20] chars. Lowercase letters, number and hyphens. Cannot start / end with hyphens."
                },
                "visible": true
            }
```
Is failing with 

_[?] Textboxes Are Well Formed (143 ms)                                                                                                                                         TextBox 'instanceName' regex does not have a length constraint._

It seems regex test is not able to detect length validation when there is one

**Comment by pavelsalamon** [comment]
We have the same issue. Our regex for a datetime is ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$
And test fails with "TextBox 'originalDatabaseTime' regex does not have a length constraint."

**Comment by dserdyuk** [comment]
same issue with regexp:

`"^(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])$"`

**Comment by StartAutomating** [comment]
@bmoore-msft This has been merged, let's close it.

**Comment by ginevragaudioso** [comment]
Has this been released? I am installing following the instructions on https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/test-toolkit , but the issue seems to still be present.

**Comment by bmoore-msft** [comment]
@ginevragaudioso - do you have a createUIdef file that we can use for a repro?

**Comment by ginevragaudioso** [comment]
yes

`
{
    "$schema": "https://schema.management.azure.com/schemas/0.1.2-preview/CreateUIDefinition.MultiVm.json#",
    "handler": "Microsoft.Azure.CreateUIDef",
    "parameters": {
        "basics": [
            {
                "constraints": {
                    "regex": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}$",
                    "required": true,
                    "validationMessage": "Invalid token"
                },
                "defaultValue": "",
                "label": "Token",
                "name": "token",
                "toolTip": "Token",
                "type": "Microsoft.Common.TextBox"
            },
        ],
        "outputs": {
            "token": "[basics('token')]",
        },
        "steps": []
    },
    "version": "0.1.2-preview"
}
`

**Comment by bmoore-msft** [comment]
#548

**Comment by melazrak** [comment]
Hello,

There were 2 examples reported in the issue.
The first one regarding passwordbox has been fixed but this one seems to be still present

```
{
                "name": "instanceName",
                "type": "Microsoft.Common.TextBox",
                "label": "xDM Instance name",
                "toolTip": "Prefix used for all resource names in the resource group.",
                "defaultValue": "xdm",
                "constraints": {
                    "required": true,
                    "regex": "^[0-9a-z][0-9a-z-]{1,18}[0-9a-z]$",
                    "validationMessage": "[3..20] chars. Lowercase letters, number and hyphens. Cannot start / end with hyphens."
                },
                "visible": true
            }
```
Is failing with

[?] Textboxes Are Well Formed (143 ms) TextBox 'instanceName' regex does not have a length constraint.

Thanks

**Comment by ndeeH** [comment]
Still getting this length error for:
> TextBox 'vm_Name' regex does not have a length constraint.

Here the snippet for the Textbox - the length is defined by regex:
```json
      {
        "name": "vm_Name",
        "type": "Microsoft.Common.TextBox",
        "label": "Virtual Machine name",
        "toolTip": "Choose an unique name which identifys your virtual machine.",
        "constraints": {
          "required": true,
          "regex": "^[a-z][a-zA-Z0-9-]{1,12}[a-zA-Z0-9-]$",
          "validationMessage": "The value should not be empty, start with a lowercase character, must be less than 15 characters and must contain only letters, numbers and -."
        },
        "visible": true
      },

```

Snippet in workflow:
```
      - name: Run ARM TTK for SINGLE WIN VM
        uses: aliencube/arm-ttk-actions@v0.3
```
