### ISSUE TITLE
Arrays with only one element is converted into a string

### ISSUE THREAD

**Issue by nbwdk** [Azure/arm-ttk#19]
When passing an TemplateObject to the Format-AzTemplate the following happens

Arrays with only one element is converted into a string when running Format-AzTemplate. This will create dependsOn with a string value, and not an Array with one string element.

I suspect that this is because the Property is being piped (and therefore converted to string by poweshell) to the sortProperties scriptBlock.

` in.$propName | & $MyInvocation.MyCommand.ScriptBlock @recurseSplat`

**Comment by nbwdk** [comment]
Created following work around.

`                        # If the object had that property
                        if ($Recurse -and ($in.$propName -is [Array]) -and ($in.$propName.count -gt 1)) { 
                            $newPropValue = $in.$propName | & $MyInvocation.MyCommand.ScriptBlock @recurseSplat
                        }
                        else {
                            $newPropValue = $in.$propName
                        }`

**Comment by bmoore-msft** [comment]
#222
