### ISSUE TITLE
document how to run unit tests

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#194]

**Comment by bmoore-msft** [comment]
scenarios we talked about:

1) how to run all unit tests before a checkin
2) how to run an individual test on an individual file using Test-AzTemplate
3) how to run all unit tests on a individual test (#2 is a single file, this is all files in pass & fail)

**Comment by StartAutomating** [comment]
@bmoore-msft Given the related item is merged, we can probably close this.
