### ISSUE TITLE
ARM-TTK: Tests are run against all JSON files in a folder when a full file path is provided

### ISSUE THREAD

**Issue by sam-cogan** [Azure/arm-ttk#2]
### Issue Details
When running the ARM TTK and supplying a full path to a json file for the TemplatePath parameter I would expect tests just to run against that specific file. However, if there are other JSON files in that folder, then tests will be run against them anyway.

When you specify a folder rather than a full path, the TTK will only be run against "maintemplate.json" or "azuredeploy.json" but it seems in this scenario where you supply a full path it will run against any JSON file.

I believe this is coming from the "folderfiles" property, but I am not clear why this is used to get all the files.

### Repro steps (*if necessary, delete otherwise*)
1. Create a folder with multiple ARM templates in
2. Run Test-AzTemplate specifying the full path to one of these files for the TemplatePath parameter
3. See tests run against all files

**Comment by bmoore-msft** [comment]
move to arm-ttk repo

**Comment by bmoore-msft** [comment]
wrong one...

**Comment by mgeorgebrown89** [comment]
I have also run into this problem, however, unlike @sam-cogan , I could not get it to work by using a folder in -TemplatePath. I had to use any .json file in the -TemplatePath parameter and use the specific .json file in the -File parameter if I wanted to test any individual template.

**Comment by samrobillard** [comment]
I'm having the same issue as well but providing the folder in TemplatePath and the file name in File parameter results in this error: "No azuredeploy.json or mainTemplate.json"

I have about a dozen ARM templates in this folder. Running tests on all of them works well BTW.
