### ISSUE TITLE
Don't allow root directories as a template path

### ISSUE THREAD

**Issue by whaakman** [Azure/arm-ttk#20]
https://github.com/Azure/arm-ttk/blob/a91c0cd57a4a19784efa5720fb8723ef97ee19f2/arm-ttk/Expand-AzTemplate.ps1#L182

As this uses the -Recurse parameter, storing the .json file in the root of your system will cause unexpected behavior. Windows will just look and eventually go banana's on memory. Linux will return something similar to (for the files it can't deal with):
MethodInvocationException: /arm-ttk/arm-ttk/Expand-AzTemplate.ps1:192
Line |
 192 |                          $fileObject = [Ordered]@{
     |                          ~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "ReadAllText" with "1" argument(s): "Could not find file '/usr/share/man/man1/sh.1.gz'."

Why this matters? If you're running this in a container it is very likely you're doing something similar  to "COPY azuredeploy.json /". I'm not saying this is the best idea but for containers with a short lifespan this happens, specially in dev/test scenarios. Works fine when using a directory such as Test-AzTemplate -TemplatePath /test/

**Comment by bmoore-msft** [comment]
@whaakman - can you try this again, we just merged a fix that should help with the bananas part...

**Comment by bmoore-msft** [comment]
@whaakman - did you get a chance to try this (after the changes went in)?

**Comment by bmoore-msft** [comment]
Closing abandoned
