### ISSUE TITLE
No support for jsonc files

### ISSUE THREAD

**Issue by kilasuit** [Azure/arm-ttk#200]
On a quick scan of this repo there's no support at all for using jsonc files, which whilst uncommon compared to normal json files should be allowed as ARM is happy with accepting deployments that use jsonc files.

**Comment by nerddtvg** [comment]
I would also like to see this!

**Comment by kilasuit** [comment]
Looking more and more into this there are a few parts to this.

-This codebase uses lines like [this](https://github.com/Azure/arm-ttk/blob/81b47c3678176260f68b92be4be5a3eb5263db9c/arm-ttk/Test-AzTemplate.ps1#L286) [this](https://github.com/Azure/arm-ttk/blob/81b47c3678176260f68b92be4be5a3eb5263db9c/arm-ttk/Test-AzTemplate.ps1#L292) & [this](https://github.com/Azure/arm-ttk/blob/81b47c3678176260f68b92be4be5a3eb5263db9c/arm-ttk/Test-AzTemplate.ps1#L373) that could be amended to match on either json/jsonc files 
- Jsonc files can be converted to objects in PowerShell v6= but not in v5.1 - as per discussion in this issue - https://github.com/PowerShell/PowerShell/issues/7436 - which for this tool I think should not be an issue anyway & if we made this a PowerShell v7.0 or above compatable tool this would also allow us to remove this [file](https://github.com/Azure/arm-ttk/blob/master/arm-ttk/ConvertFrom-JSON.ps1) & the overriding `ConvertFrom-Json` funtion completely

So I propose 2 things

- edit all the code that is looking for explicit `.json` to match on both `.json` & `.jsonc`
- make this a PowerShell v7 and above tool - which for build pipelines in other tooling (Azure DevOps / GitHub Actions) is already not an issue & is where most likely run the arm-ttk anyway - I know that is where we would be running it using Sam Cogans extension

**Comment by bmoore-msft** [comment]
Are you asking for jsonc because you want support for comments in the files?  Or because you want no quotes around properties (for example)?

If the former, I don't mind a PR that looks for *.json and *.jsonc - if the latter, ARM doesn't actually like that so............

**Comment by kilasuit** [comment]
My use case is just for comments in series of files where they are complex (lots of linked templates being used)
I'd be happy to add a PR for this `I don't mind a PR that looks for *.json and *.jsonc` and also which ever of these two suggestions at the same time
>
> -    make this a PowerShell v7 and above tool & remove the need for the custom ConvertFrom-Json function.
>  -  rename ConvertFrom-Json to either ConvertFromJson or ConvertFrom-JsonWithComment and update the codebase accordingly as it's better not to override core powershell functionality for others (even if technically it provides better functionality)

**Comment by bmoore-msft** [comment]
I would separate things a bit... 

1) the need to handle comments, which are one "feature" of jsonc that ARM also supports, this should be as simple as looking for .json or .jsonc - maybe slightly more since mainTemplate/azuredeploy are specifically used but I think that should be relatively straightforward.

re: PSv7 - I would separate this work item and probably wait until V7 GAs, we've run into an issue or two in V7 and given ConvertFrom-JSON is working would wait until there is a greater need for that...

Thoughts?

**Comment by kilasuit** [comment]
Yeah I was going to raise as 2 PR's as opposed to one anyway (already have started for in #206 ) & have moved the conversation about clean up into #207
