### ISSUE TITLE
Module should have a build pipeline

### ISSUE THREAD

**Issue by kilasuit** [Azure/arm-ttk#201]
It is standard practice to include a build pipeline that can be run both on a build agent and locally for dev testing purposes

**Comment by bmoore-msft** [comment]
There is a way to run the entire suite of unit tests locally - we have #194 to make that a bit more obvious...

https://github.com/Azure/arm-ttk/blob/master/unit-tests/arm-ttk.tests.ps1

**Comment by StartAutomating** [comment]
@bmoore-msft: 👍  (we could generate a pipeline for others to use within their CI/CD).  We could also consider deploying as a module, a GitHub Action, and an Azure DevOps Extension (this can be code-generated away without too much time)

**Comment by bmoore-msft** [comment]
This should be documentation only for now - we can point to the QuickStarts repos example.
