### ISSUE TITLE
Found hardcoded reference to core.windows.net - private link DNS zone

### ISSUE THREAD

**Issue by marrobi** [Azure/arm-ttk#210]
When creating DNS zones for private endpoints for storage accounts we pass the DNS zone name `blob.core.windows.net`, in as a parameter value.

This is throwing the error: `Found hardcoded reference to core.windows.net`. 

Any suggestions?

Thanks.

**Comment by bmoore-msft** [comment]
Instead of hard-coding you should use:

[concat('blob.', environment().suffixes.storage)]

**Comment by marrobi** [comment]
@bmoore-msft thanks!
