### ISSUE TITLE
[feature request] define an input file and map files/rules/severity

### ISSUE THREAD

**Issue by bobbyangers** [Azure/arm-ttk#225]
It would be most useful a to have an optional input file that would be used to help configure the test to be run.
This file could be in the same folder as the 'azuredeploy.json' and if detected, would help configure how test are run.

For a given file,  list which tests should be "skipped",  or have the option of reporting a test as warning instead of an error.

`
[
  {
       " file": "filenameA.json"
       "skipTests: "rule1, rule2, ... "
   },

   {
      "file": "filenameA.json"
       "testAsWarning: "rule1, rule2, ... "
  }
}

`

**Comment by bmoore-msft** [comment]
are you finding that tests are "inaccurate" for some files?  or just want to have the option to be "less strict" for certain files?

**Comment by bobbyangers** [comment]
One of the example that comes to mind;  is the rule about "empty" object;  sometime you would want to skip that because you want the deployment to "reset" the values.
Another example is is for a logic apps, some values are user defined, not schema related, then it would simply easier to skip a rule check for that file, or just leave, but report it as a warning instead of blocking the deployment pipeline.

Also had some weird cases with apiVersion that were still in preview but were not `"cached" yet;  or the opposite, don`t want to use the preview;  and the last api dates from 2016.

There are many more....
fyi:  I have integrated the arm-ttk as part of our pipelines at work;  for now it`s on an "opt-in" basis;  but we have at least 5 pipelines using them now.    I am pushing to get all of them... 50+ projects.

**Comment by bmoore-msft** [comment]
🥇 I can tell you're giving this stuff a lot of thought (these never seem to be simple conversations)...  Anyway.

So far this sounds like a way to configure certain tests... take for example the empty property test, that has exceptions but what if you want your own list?  And then your scenario sounds more complex that says maybe for a given resource type in a given file this is the test I want?

That would be pretty complex to do generically, but perhaps for each test there is a way to deliver something that scales.

re: The apiVersion test, I thought we had a provision in that the required only the latest non-preview version.  Or are you saying that you may want that just for a given resource type?

Good the hear the adoption is picking up steam...

**Comment by bmoore-msft** [comment]
Going to close this one so we can track in #309
