### ISSUE TITLE
"apiVersions Should Be Recent" is broken

### ISSUE THREAD

**Issue by Splaxi** [Azure/arm-ttk#226]
I'm get false positives for namespace topics and their authorizationRules.

From the AllAzureResources.cache.json file, it clearly states that the following APIs are valid:

```
"Microsoft.ServiceBus/namespaces/topics/authorizationrules": [
    {
      "aliases": null,
      "apiProfiles": [
        {
          "apiVersion": "2017-04-01",
          "profileVersion": "2018-06-01-profile"
        }
      ],
      "apiVersions": [
        "2017-04-01",
        "2015-08-01",
        "2014-09-01"
      ],
      "capabilities": "None",
      "locations": [],
      "properties": null,
      "resourceType": "Microsoft.ServiceBus/namespaces/topics/authorizationrules"
    }
  ],
```

but the logic inside "apiVersions-Should-Be-Recent.test.ps1" resolves the type back up to the parent, which is "Microsoft.ServiceBus/namespaces". It states that the following APIs are valid:
```
"Microsoft.ServiceBus/namespaces": [
    {
      "aliases": null,
      "apiProfiles": [
        {
          "apiVersion": "2017-04-01",
          "profileVersion": "2018-06-01-profile"
        }
      ],
      "apiVersions": [
        "2018-01-01-preview",
        "2017-04-01",
        "2015-08-01",
        "2014-09-01"
      ],
      "capabilities": "CrossResourceGroupResourceMove, CrossSubscriptionResourceMove, SystemAssignedResourceIdentity, SupportsTags, SupportsLocation",
      "defaultApiVersion": "2017-04-01",
      "locations": [
        "Australia East",
      ...
      ],
      "properties": null,
      "resourceType": "Microsoft.ServiceBus/namespaces"
    }
  ],
```

So the unit test fails like this:

![image](https://user-images.githubusercontent.com/8750181/97107971-b1601100-16ca-11eb-810d-bf61915f954c.png)

I did try to look into the code, but it is a bit unclear where the logic that resolves back the parent is and where the validation is happening for real.

I would argue that we should look for the inner object type, and if that isn't present in the cache file, then we base our test on the parent object and its type. Happy to help with the fix, if I can get some pointers.

**Comment by Splaxi** [comment]
Hi @bmoore-msft 

Looking at this code:
https://github.com/Azure/arm-ttk/blob/55f6a92e4eb0e873c84ccc59d9e3aa9991a26f67/arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1#L93-L106

Looking at my sample template:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "type": "Microsoft.ServiceBus/namespaces",
            "apiVersion": "2018-01-01-preview",
            "resources": [
                {
                    "type": "Microsoft.ServiceBus/namespaces/queues/authorizationRules",
                    "apiVersion": "2017-04-01"
                }
            ]
        }
    ]
}
```

The issue I'm hitting is that resourceTypeName is constructed incorrectly:
```
$resourceTypeName = $FullResourceTypes[0..$i] -join '/'
```
This yields `Microsoft.ServiceBus/namespaces/Microsoft.ServiceBus/namespaces/queues/authorizationRules`
That resource name is incorrect and therefor the logic doesn't find a matching api version, and never adding the api to the `$validApiVersions` variable and then the logic later fails, because it looks at the parent. 

If we were to change the code into:
```
$validApiVersions = # This is made a little tricky by the fact that some resources don't directly have an API version
@(for ($i = $FullResourceTypes.Count - 1; $i -ge 0; $i--) {
        # so we need to walk backwards thru the list of items
        # Some resources use a full resource type name, even when they are nested childs / grands
        if ($FullResourceTypes[$i].StartsWith("Microsoft")) {
            $resourceTypeName = $FullResourceTypes[$i]
        }
        else {
            $resourceTypeName = $FullResourceTypes[0..$i] -join '/' # construct the resource type name
        }

        $apiVersionsOfType = $AllAzureResources.$resourceTypeName | # and see if there's an apiVersion.
        Select-Object -ExpandProperty apiVersions |
        Sort-Object -Descending
  
        if ($apiVersionsOfType) {
            # If there was,
            $apiVersionsOfType # set it and break the loop
            break
        }
    })
```
Then my issue goes away.

We actually also need to implement the same logic here:
https://github.com/Azure/arm-ttk/blob/55f6a92e4eb0e873c84ccc59d9e3aa9991a26f67/arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1#L75-L76

and have it to be like this:
```
if ($av.type.StartsWith("Microsoft")) {
        $FullResourceType = $av.type
    }
    else {
        # To get the full type name, join them all with a slash 
        $FullResourceType = $FullResourceTypes -join '/'
    }

```


I'm happy to do the PR and add some unit tests around it, but I saw that you have the following code:
https://github.com/Azure/arm-ttk/blob/55f6a92e4eb0e873c84ccc59d9e3aa9991a26f67/arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1#L124-L132

It gives me a feeling that you have some templates in the different Microsoft repos, that might fail, when being tested using arm-tkk, and that is why you had to silence it. But it is also affecting the rest of us, because invalid api for nested childs / grands are being skipped.

Consider the following sample:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "type": "Microsoft.ServiceBus/namespaces",
            "apiVersion": "2018-01-01-preview",
            "resources": [
                {
                    "type": "Microsoft.ServiceBus/namespaces/queues/authorizationRules",
                    "apiVersion": "2014-04-01"
                }
            ]
        }
    ]
}
```
Running that as part of the unit test `apiversions-should-be-recent.tests.ps1` doesn't throw an error, as it should. The reason for that is the above mentioned code, where you don't throw an error, even when you should. I totally get that you need this to work for all the templates that you need to support from the Microsoft repo, but having it so silence like this, does harm the rest of the community, because we get false report stating that there isn't anything wrong with our template.

If we could do the PR, so my templates stops from breaking, then we can look into how to solve the rest of the issue - with the silencing of the errors in another PR.

**Comment by bmoore-msft** [comment]
I think there are 2 separate issues here: 1) the construction of the child resource type and 2) the test failing when the manifest is out of date.

For #1, I don't think we can simply check for ```startswith('Microsoft')``` because there can be 3rd party resource providers.  What we'd want to do (I think) replace the parent resourceType in the child resource with empty string and then do the join.  Something like:
```
$resourceType = $childResource.type.replace($parentResource.type, '')
```
I'd have to think about where that would need to be placed in the code, but that's the general idea.

For #2 - this is a case where the manifest (which is where we build the apiVersion cache from) hasn't been updated to support a new apiVersion.  So not really specific to any set of template, it's generic problem.  Perhaps the proper way to fix that one is to say: if the apiVersion isn't found *and* it's later than the latest apiVersion, assume it's ok.

Thoughts?

**Comment by Splaxi** [comment]
Thanks for taking the time so share some more details.

For the first issue:
First impression on your suggestion is that it should work for most cases that we face. It will support multiple providers (which I failed to recognize) and it should solve the nested childs / grands, and support mixed type definitions. I would say it should be fairly easy to test out, and I'm up for testing it on my scenario and share it with you, then you can see if it meets the bar or not.

For the second issue:
If the module supports or offers the capability for the user to update the cache file, and there is an endpoint which will be able to give the user a complete and valid list of api versions, that would help. I'm more for the strict validation, but then add logic that can see they added a newer version than was found in the cache file and write a message that they should try to update the cache file. If they update and the cache file doesn't include the api version they specified (at it is valid), they have 2 options. File an issue here and we will look into it or skip the test, because they are in an edge case.

To support the second issue even further, we would come up with a Github action / Azure Pipeline, that pulled a complete cache file daily and compared it against the version available in the module (via Powershell Gallery) and if the newly pulled cache file contains new api versions, we can auto create a PR / Issue and we should be able to uptake that fast and easy. We could go even further and run all unit tests, and if they pass, auto release a new version directly.

**Comment by bmoore-msft** [comment]
For #1, I'd be more than happy to have a PR with that fix ;)

For #2....
I think that might actually be easier than I think... i.e. just allow the apiVersion if it's newer than the newest listed.  The intent of the test is not to catch a deployment failure (though it currently would if the manifest were complete). If we were ok with that (ttk would not catch an invalid, later apiVersion) then we're done.

A more frequent cache update would help, but still wouldn't be a 100% solution - some of these lag quite a bit, esp across clouds.  Though it's an interesting conversation about how to better get these versions to the TTK.  We could call the service at run-time but that would require authn/authz.  We could pull from github (slightly better) but requires connectivity (though we could make that an option)...  That would save having to update the gallery module (once we get it there) on a regular basis.  

You can use your own cache in the ttk today, but have to stuff it in the TTK's cache folder.  Would be a simple change to parameterize that though I don't think it changes the workflow a ton - you still have to build it, copy it before running the ttk.

**Comment by bmoore-msft** [comment]
#2 we should do - see the test for this code:

```powershell
    if ($howOutOfDate -eq -1 -and $validApiVersions) {
        # Removing the error for this now - this is happening with the latest versions and outdated manifests
        # We can assume that if the version is indeed invalid, deployment will fail
        # Write-Error "$fullResourceType is using an invalid apiVersion." -ErrorId ApiVersion.Not.Valid
        # Write-Output "ApiVersion not found for: $fullResourceType and version $($av.apiVersion)" 
        # Write-Output "Valid Api Versions found:`n$recentApiVersions"
    }
```

**Comment by bmoore-msft** [comment]
Change was reverted so re-opening the issue
