### ISSUE TITLE
AdminUsername should allow for keyvault reference

### ISSUE THREAD

**Issue by mgeorgebrown89** [Azure/arm-ttk#23]
Basically the title. If I define an adminUsername like so:

    "adminUsername": {
                            "reference": {
                                "keyvault": {
                                    "id": "[variables('keyvault').resourceId]"
                                },
                                "secretName": "[parameters('integration').adminUsernameSecretName]"
                            }
                        },
it should be valid (at least I think so).

I tried messing with the regex like this: `\[[^\]]+\]` to this: `[\[|\{]+[^\]|\}]+` and that pass for the above example, but I'm not sure if that's the best way to account for a case like this..

**Comment by bmoore-msft** [comment]
@mgeorgebrown89 - Can you zoom out a bit in you sample?  Is that in a template, parameters file, nested deployment?  I.e. how can you attach a repro?

**Comment by bmoore-msft** [comment]
@mgeorgebrown89 - gentle ping

**Comment by bmoore-msft** [comment]
Closing abandoned - @mgeorgebrown89 let us know if you're still setting this (and how :))
