### ISSUE TITLE
False positive on 'apiVersions Should Be Recent'

### ISSUE THREAD

**Issue by martin77s** [Azure/arm-ttk#242]
When testing a template that contains a Microsoft.StreamAnalytics/StreamingJobs resource, the 'apiVersions Should Be Recent' test fails with an error:
```
-] apiVersions Should Be Recent (116 ms) 
        Microsoft.StreamAnalytics/StreamingJobs uses a preview version ( 2017-04-01-preview ) and there are more recent versions available.
        Valid Api Versions:
        2019-06-01

        Api versions must be the latest or under 2 years old (730 days) - API version 2017-04-01-preview of Microsoft.StreamAnalytics/StreamingJobs is 1336 days old
        Valid Api Versions:
        2019-06-01
```
But the latest api version for Microsoft.StreamAnalytics/streamingjobs **is** '2017-04-01-preview'. See https://docs.microsoft.com/en-us/azure/templates/microsoft.streamanalytics/streamingjobs

**Comment by andrew-stephens-insight** [comment]
Another example is Microsoft.Sql/servers/firewallRules.  The latest api version is 2015-05-0-preview.  Instead of just calculating the number of days, the test should be looking up the latest version of the resource too.

**Comment by bmoore-msft** [comment]
@martin77s - For ```Microsoft.StreamAnalytics/StreamingJobs``` the ttk is correct, the latest version is 2019-06-01.  The TTK pulls apiVersions from a cache that's built from the service manifest.  The docs usually lag that.  If you run ``(Get-AzResourceProvider -ProviderNamespace Microsoft.Storage).ResourceTypes``` you can see the information that's in the manifest.

@andrew-stephens-insight - what's the issue with fw rules?  that there is a later version or there isn't?  firewall rules aren't actually specified in the manifest, so the apiVersion is taken from the parent (which is not always correct)

**Comment by martingbrown** [comment]
I've just hit another instance of this. "Api versions must be the latest or under 2 years old (730 days) - API version 2018-09-15 of Microsoft.DevTestLab/schedules is 870 days old in template file". As far as I can tell the 2018-09-15 version is the latest version. I'm not sure it is a great idea to enable this rule if it throws lots of false positives.

**Comment by LordHMX** [comment]
Same issue here with 'Microsoft.Network/dnsZones' whereas the latest version is "2018-05-01". Unless the script validates that there is an actual, more recent, version to the api version, I would disable this rule.

**Comment by bmoore-msft** [comment]
@martingbrown @LordHMX - can you supply a full template with a repro?  I'm not seeing either issue in the latest version.
