### ISSUE TITLE
arm-ttk support for powershell core

### ISSUE THREAD

**Issue by glloyd2010f** [Azure/arm-ttk#252]
We have a growing presence of linux build agents. It would be beneficial if we this was available for powershell core in addition to Desktop

**Comment by bmoore-msft** [comment]
ttk will run on PS Core (that's what we run it on in our pipelines but most are windows)...  Are you running into a particular error on nix?

**Comment by glloyd2010f** [comment]
this is likely a cart before the horse scenario. Just saw the module only show desk version when I did a get-module against it. We have not tested this on our azure devops ubuntu containers yet. But thank you for the information.

**Comment by bmoore-msft** [comment]
ok, thanks for confirming...  I'll close this one out, feel free to open another if you run into any issues...
