### ISSUE TITLE
Allowed-Values-Should-Actually-Be-Allowed does not handle nested steps

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#253]
On this LoC:

    $lookingFor= if ($stepName) { "*steps(*$stepName*).$controlName*"} else {"*basics(*$($controlName)*"} 

It doesn't look like we'll handled groupcontrols/nested steps.

**Comment by StartAutomating** [comment]
@bmoore-msft  : 👍 Given how commonly we hit this sort of pita, it's probably prudent to write a better expression in the new form so we can use it consistently within various tests.
