### ISSUE TITLE
ResourceId function has correct parameters

### ISSUE THREAD

**Issue by allanmoller** [Azure/arm-ttk#255]
The test case fails when using concat! if I for example have a loop of keyvaults, where I want to output vaulturi, I would be unable to to this:

In my view using a function within a reference function is not an error, why is this the case then?

"outputs": { "keyvaultUris" : { "type": "array", "copy": { "count": "[length(parameters('keyVaults'))]", "input": "[reference(concat(parameters('keyVaults')[copyIndex()].keyVaultNamePrefix, uniqueString(resourceGroup().id))).vaultUri]" } } }

**Comment by bmoore-msft** [comment]
The "best practice" here is to use the full resourceId (even though the resource name short-hand is perfectly valid).  There is an option here to allow for concat when the concat function contains the copyIndex() function but would need to add that to the list of enhancements...

Also see #257
