### ISSUE TITLE
Test "IDs-Should-Be-Derived-From-ResourceIDs" is failed for "Locations" property of microsoft.insights/webtests resource

### ISSUE THREAD

**Issue by reaver89** [Azure/arm-ttk#256]
This test is broken for resource "microsoft.insights/webtests", becuase it has property "Locations" which **should** contain list of hardcoded ids:
[GitHub Example](https://github.com/Azure/azure-quickstart-templates/tree/master/201-dynamic-web-tests)

"properties": {
        "Locations": [
          {
            "Id": "[variables('location1')]"
          },
          {
            "Id": "us-tx-sn1-azr"
          },
          {
            "Id": "us-il-ch1-azr"
          },
          {
            "Id": "us-va-ash-azr"
          },
          {
            "Id": "us-fl-mia-edge"
          }
        ],
But test failed because "Id" contains hardcoded value. And event if we create variable for each location and use it inside, it is still failed because after Expand command the real value from variable is validated against RegExp:

 "variables": {        
	"location1" : "us-ca-sjc-azr"
  },
"Locations": [
          {
            "Id": "[variables('location1')]"
          },

**Comment by bmoore-msft** [comment]
This is our generic problem where we want to exempt certain paths - right now it's just properties, but we need to look at the lineage when excepting as well...
