### ISSUE TITLE
DependsOn Best Practices Rule should allow starting with concat for any use when referencing resources using Copy loops

### ISSUE THREAD

**Issue by kilasuit** [Azure/arm-ttk#257]
Using a concat for a depends on for items like a VM in a copy loop like the below is a valid and sensible approach  & as such this rule shouldn't fire an error on it

```json
"dependsOn": [
                "[concat(parameters('VMName'), CopyIndex(1))]"
            ],
```

So if the concat test can look for `CopyIndex` in the definition and then ignore it that would be much better

**Comment by bmoore-msft** [comment]
You're right this is a valid scenario.... we've been leaning towards a BP that uses the full loop or the resourceId(), e.g.

resourceId('Microsoft.Compute/virtualmachines', concat(parameters('VMName'), copyindex(1)))

both are more common.  I'm not opposed to the solution you proposed but such a change might be a bit down the list from the other bugs.  Certainly open to a PR if you want to take a stab at it...

**Comment by bmoore-msft** [comment]
another option would be to flag "concat" when a resourceType follow it... 

e.g.
concat('Microsoft.Resources/someResourceType', ...)

**Comment by Splaxi** [comment]
I just got bite by this.

Trying to learn, but it seems that I picked up the trait of using the concat function in the dependsOn property. Don't know why.

But for a simple dependsOn, would you recommend the resourceId() as the alternative?

[concat('Microsoft.ServiceBus/namespaces/', parameters('ServiceBusNamespaceName'))]

vs 

[resourceId('Microsoft.ServiceBus/namespaces', parameters('ServiceBusNamespaceName'))]

**Comment by bmoore-msft** [comment]
resourceId is the formal way - a dependsOn needs a resource (i.e. resourceId).

In templates there is a shortcut of just using the resource name but that only works if the resource name is unambiguous, so can work one day and then bite you later one.  So the full resourceId is the best practice.
