### ISSUE TITLE
Find-JsonContent gets confused on roleAssignments

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#269]
Try on the following - the return object of Find-JSONContent returns both properties in the same object instead of separate objects.

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Authorization/roleAssignments",
            "apiVersion": "2020-04-01-preview",
            "name": "some guid",
            "properties": {
                "roleDefinitionId": "[concat('Microsoft.Authorization/roleDefinitions/', 'some roledef')]", //this should be flagged by ttk
                "principalId": "[reference('some UAI', '2018-11-30').principalId]"
            }
        }
    ]
}

```

**Comment by bmoore-msft** [comment]
make sure we have a unit test that covers this case (and comment why it's there since we don't have unit tests for the framework)

**Comment by bmoore-msft** [comment]
Need to see if Find-JsonContent finds one or many objects (targetKey or the parent object)

**Comment by StartAutomating** [comment]
@bmoore-msft  I'm waring of changing the return signature of this function too much.  How about we have a [switch] indicating if you would like to return each wiildcard/regex match?

**Comment by bmoore-msft** [comment]
yes we can use a switch - will need to scrub for the tests that need it

IDs-should-be-derived...
uris-should-be...

**Comment by StartAutomating** [comment]
@bmoore-msft:  I decided to check the impact of simply returning multiple matches by default, and it does not appear to impact CI/CD.

With this in mind I retract my suggestion about a [switch] (and have retracted the stub of the [switch])
