### ISSUE TITLE
VS Code suddenly not Showing Tests

### ISSUE THREAD

**Issue by NickBishop2112** [Azure/arm-ttk#272]
From yesterday the Test-AzTemplate is no longer showing passing tests within VS Code.

In Powershell ISE, the test results are clearly shown below:

![image](https://user-images.githubusercontent.com/30340714/103642605-4bee9300-4f4b-11eb-9052-46e9293eee9f.png)

However, in VS Code the test results are no longer shown:
![image](https://user-images.githubusercontent.com/30340714/103642822-9f60e100-4f4b-11eb-9388-a7e1dedf2dd0.png)

VS Code version is 1.52.1

**Comment by bmoore-msft** [comment]
@NickBishop2112 - I just tried the latest TTK in VS Code with pwsh.exe version 7 and I do see the passing results as expected - also using 1.52.1 on Windows.  I suspect some local config issue?

**Comment by bmoore-msft** [comment]
Closing abandoned
