### ISSUE TITLE
Results Feedback

### ISSUE THREAD

**Issue by DillyBabu** [Azure/arm-ttk#277]
Hi,
Could you please help in posting how to get a result file(*-armttk.xml') in linux environment.
Sorry for writing this under issue section as I am not able find any other section.

Thanks

**Comment by bmoore-msft** [comment]
@StartAutomating - can we take this issue as a work item to update the doc for this scenario?

**Comment by DillyBabu** [comment]
We can close this issue. I used Invoke-pester to get result files. Thank you so much for this nice tool 👍

**Comment by bmoore-msft** [comment]
Thx for the update @DillyBabu - but I think you have a good issue/improvement for us here...
