### ISSUE TITLE
Can not find the old version of arm-ttk on this repository

### ISSUE THREAD

**Issue by hoangmnsd** [Azure/arm-ttk#289]
Hi everyone, 

When I publish my ARM templates to Azure Marketplace, It fire an error as:  
```
"subnet" must use one of the following expressions for an resourceId property:

(resourceId(), subscriptionResourceId(), tenantResourceId(), if(), extensionResourceId(), parameters(), variables())
```
My ARM templates is using below convention for subnet properties:  
```
"subnet": {
  "id": "[reference(resourceId('DEPLOYMENT_NAME').outputs.SUBNET_ID.value]"
 },
```

The latest version of arm-ttk doesn't fire the error.
But It seem Azure Marketplace Certification step is using old version of arm-ttk.
And I can not find the old version on this repository to re-procedure the error at my local machine.

**Comment by bmoore-msft** [comment]
@hoangmnsd - since this is fixed in the current version, I'm going to close out the issue... send me email and I will put you in touch with the MP folks to help get the tool in the MP pipeline updated.
