### ISSUE TITLE
 Templates should be named azureDeploy.json or mainTemplate.json.

### ISSUE THREAD

**Issue by SuperKoelle** [Azure/arm-ttk#295]
We have several folders with several ARM templates and we have naming standards for these files. Why can't i run arm-ttk without creating an empty azureDeploy.json file in the folder I want to test files in?

And even if i provide the file to test with the -File parameter i get this error.

**Comment by bmoore-msft** [comment]
Does it work as you expect with the -MainTemplateFile param?

-File will test a single file, -MainTemplateFile should let you "retarget" the "initial template" in the deployment.

**Comment by SuperKoelle** [comment]
I don't have an "initial template". I have multiple templates, that is deployed independently.

**Comment by ReneRebsdorf** [comment]
To elaborate on this:

In order to reproduce create the following folder and file structure:

- parentFolder
  - childFolder1
    - azureDeploy.json
  - childFolder2
    - azureDeploy.json


If you want to scan the two azureDeploy.json files you would expect to run: 
``` pwsh
Test-AzTemplate -TemplatePath ".\parentFolder"
```

However this returns the following error message:

``` text
Expand-AzTemplate: C:\users\rre\source\repos\Azure\arm-ttk\arm-ttk\Test-AzTemplate.ps1:441
Line |
 441 |  …      $expandedTemplate =Expand-AzTemplate -TemplatePath $templatePath
     |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No azuredeploy.json or mainTemplate.json found beneath .\source\repos\ProActive\Azure DevOps CoP\connectivity\
```

**Comment by SuperKoelle** [comment]
I don't have the nested childFolders. I only have parentFolder with several templates in.

parentFolder (name of resourceGroup)
- template 1: same name as resource
- parameters for template 1: same name as resource + environment
- parameters for template 1: same name as resource + environment
- parameters for template 1: same name as resource + environment
- template 2: same name as resource
- parameters for template 2: same name as resource + environment
- parameters for template 2: same name as resource + environment
- parameters for template 2: same name as resource + environment
-etc.

**Comment by bmoore-msft** [comment]
and each file is deployed independently?  i.e. each file would be considered azuredeploy/mainTemplate?

**Comment by SuperKoelle** [comment]
Yes. 

The deployment is organized by a powershell script. The templates are all independent.

Today I add an empty azureDeploy.json file and run the test cmd file on the whole folder to check all files independent files I one run.

**Comment by bmoore-msft** [comment]
ok got it - you should be able to do:

```Get-ChildItem -recurse *.json | Test-AzTemplate # remove recurse if you don't have folders```

lmk if that works...

**Comment by SuperKoelle** [comment]
Sorry to say. But it didn't do the trick. It results in same error.

**Comment by bmoore-msft** [comment]
ok, I think you'll have to get us a zip file with a repro...  doable?

**Comment by bmoore-msft** [comment]
@SuperKoelle - just wanted to ping on this (we're planning our next milestone)

**Comment by SuperKoelle** [comment]
Here are the files for one of our many projects. I have cut out some parts, so maybe it will fail validation.
[cor-app-cvr.zip](https://github.com/Azure/arm-ttk/files/6223781/cor-app-cvr.zip)

**Comment by bmoore-msft** [comment]
@SuperKoelle - I'm not seeing anything unexpected when running

```Get-ChildItem -recurse *.json | Test-AzTemplate # remove recurse if you don't have folders```

the azuredeploy in your zip is empty and that caused and issue - as well cor-af-cvr.json had a json syntax error.. but aside from that seems to be working as expected.  It's possible we fixed something in the area, but for now can't see the error you're seeing with the above cmd.

lmk if you're still seeing it (and how ;))

**Comment by bmoore-msft** [comment]
@SuperKoelle - assuming this unblocked you so going to close for now - feel free to reopen if it's still not working for you.
