### ISSUE TITLE
IDs Should Be Derived From ResourceIDs on dashboard template

### ISSUE THREAD

**Issue by nsucheninov** [Azure/arm-ttk#296]
The test fails on defaultMenuItemId and menuid.
Samples from the template:
`
                          "openBladeOnClick": {
                            "openBlade": true,
                            "destinationBlade": {
                              "extensionName": "HubsExtension",
                              "bladeName": "ResourceMenuBlade",
                              "parameters": {
                                "id": "[variables('applicationInsightsResourceId')]",
                                "menuid": "segmentationUsers"
                              }
                            }
                          }
`

`
                  "type": "Extension/AppInsightsExtension/PartType/MetricsExplorerBladePinnedPart",
                  "asset": {
                    "idInputName": "ComponentId",
                    "type": "ApplicationInsights"
                  },
                  "defaultMenuItemId": "browser"
`

The template is attached.
[dashboard.zip](https://github.com/Azure/arm-ttk/files/5959095/dashboard.zip)

**Comment by bmoore-msft** [comment]
s/b fixed in #305
