### ISSUE TITLE
Broken formatting in Azure Pipelines

### ISSUE THREAD

**Issue by suic86** [Azure/arm-ttk#300]
# Description

When running `Test-AzTemplate` in Azure Pipeline, there's no linebreak between `Validating ...` line and the following line.

## Actual behavior
```
Validating configurationsStore\template.json  deploymentTemplate
    [+] adminUsername Should Not Be A Literal (12 ms)

    [+] apiVersions Should Be Recent (18 ms)
    [+] artifacts parameter (4 ms)
    ...
```
## Expected behavior
```
Validating configurationsStore\template.json
  deploymentTemplate
    [+] adminUsername Should Not Be A Literal (13 ms)
    [+] apiVersions Should Be Recent (15 ms)
    [+] artifacts parameter (3 ms)
    ...
```
# Repro steps

The behavior is reproducible locally by setting the `AGENT_ID` environment variable.

```powershell
PS > Get-ChildItem -Recurse template*.json | select -first 1 | % { Test-AzTemplate $_.FullName.ToString() }
# ... expected behavior ....
PS > $env:AGENT_ID = 1
PS > Get-ChildItem -Recurse template*.json | select -first 1 | % { Test-AzTemplate $_.FullName.ToString() }
# ... actual behavior ...
```

# Root cause
Explicit `-NoNewLine` in:
https://github.com/Azure/arm-ttk/blob/de89383afcaa8b52f8f0e67823242dc4ccf9ed28/arm-ttk/ttk.ezformat.ps1#L28

**Comment by bmoore-msft** [comment]
Thanks - do you mind submitting a PR for this one?

**Comment by suic86** [comment]
The PR (https://github.com/Azure/arm-ttk/pull/306) is ready.
