### ISSUE TITLE
IDs Should Be Derived From ResourceIDs on Microsoft.OperationalInsights/workspaces/dataSources template

### ISSUE THREAD

**Issue by nsucheninov** [Azure/arm-ttk#301]
The test fails on the DataTypeId property.

`
"type": "Microsoft.OperationalInsights/workspaces/dataSources",
"apiVersion": "2020-08-01",
"name": "[Concat(parameters('workspaceName'), '/ChangeTrackingDataTypeConfiguration_Software')]",
"location": "[parameters('workspaceLocation')]",
"kind": "ChangeTrackingDataTypeConfiguration",
"properties": {
    "DataTypeId": "Software",
    "Enabled": "true"
}
`
The template is attached.
[changeTrackingSettings.zip](https://github.com/Azure/arm-ttk/files/5971482/changeTrackingSettings.zip)

**Comment by bmoore-msft** [comment]
s/b fixed in #305
