### ISSUE TITLE
New feature request: ignore

### ISSUE THREAD

**Issue by SuperKoelle** [Azure/arm-ttk#309]
As a manual user or a user of the tfs/azureDevOps integation

I would like to have an "ignore" file inside a project, where I can maintain a list of positions in the json files where I would like to ignore specific or unspecific tests.

ie.
azureDeploy.json variables.location "Resources Should Have Location" 
_// "Resources Should Have Location" tests for variables.location element in azureDeploy.json_

azureDeploy.json resources[1].resources.[0].properties.subnetResourceId "IDs Should Be Derived From ResourceIDs"
_// "IDs Should Be Derived From ResourceIDs" test for resources[1].resources.[0].properties.subnetResourceId element in azureDeploy.json_

azureDeploy.json resources[1].resources * 
_// All tests for resources[1].resources element in azureDeploy.json_

azureDeploy1.json * * 
_// All test for all elements in azureDeploy1.json_

**Comment by bmoore-msft** [comment]
What's the scenario - i.e. what specific cases are you finding that you want to ignore?

**Comment by SuperKoelle** [comment]
Right now we would like to implement arm-ttk as a build task to verify the templates before deploy.

This is blocked by #281. 

We are only using a small part of the features in arm and I would be surprised if we would not encounter another blocking problem in the future.

**Comment by bobbyangers** [comment]
Hi @bmoore-msft ,
This is very similar to #225

**Comment by asears** [comment]
This suppression flag would be very useful as a JSON comment (similar to NOQA in python or SuppressMessage in powershell) for quickly ignoring false positives coming from other other known Arm-TTK issues.  A couple I would like to ignore in certain files are Concat Location check and hard coded location check which are thowing false positives.

There could be a warning option for surfacing suppressed warning messages to revisit them later or in another stricter build.

Additionaly, some additional documentation on how best to delete the false positive rule during a build pipeline, or run all rules one at a time except a rule would be helpful.

.editorconfig is where some current rules are suppressed within VSCode, this might be an entry point in addition to having an .arm-ttk-config.json (or preferably yaml) file in a parent or current folder.

**Comment by bmoore-msft** [comment]
ACK - the distinction I'm interested in is between a false positive and a bug.  I.e. if there is a bug in the TTK and users can just mask it with a comment, we end up with a crappy toolkit and/or users not trying to understand what the test is saying (e.g. IDK what this means so I'm just going to block it).

Not that we can't/shouldn't do it, but it needs a bit of thinking through.  Features I'm hearing across threads.

- skip a on all files
- skip a test on a file
- skip a test on a line occurrence of a in issue perhaps via code comment (we'd also need a way to ignore this comment)
- turn a test from a fail to warn

Any others I missed?

**Comment by SuperKoelle** [comment]
Good points.

You miss the most stupid one, but in a CI env you might want to use i to override:

Ignore all tests on all files 😔

**Comment by bmoore-msft** [comment]
3rd option seems to have the most bang/buck - the others seem to be possible in some fashion today (thinking about it for only a short time)

**Comment by konjp** [comment]
3rd option reminds me of java [@SuppressWarnings](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/SuppressWarnings.html), where people start using it to mask potential errors instead to fixing them, just as @bmoore-msft mention above.

@bmoore-msft In context of user of TTK toolkit what is difference between 'false positive' and bug?

**Comment by bobbyangers** [comment]
I do agree, but I did encounter situation, with existing arm templates that are working, the ttk want to apply a rule that i might choose i don’t want to apply, for the time being.  ended in some case having to disable the step altogether..... which is worse in my opinion.

Let’s keep in mind that the tool is tool apply best practices, for example, an unused variable, is really grounds to abort a build ?

Yes it might underline another error, but might not also, in this case a warning would be more appropriate.

--Robert Angers

Sent from my iPhone

On Mar 19, 2021, at 03:04, konjp ***@***.***> wrote:

﻿

3rd option reminds me of java @SuppressWarnings<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.oracle.com%2Fen%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2Fjava.base%2Fjava%2Flang%2FSuppressWarnings.html&data=04%7C01%7C%7Cacd5f09787434f0ab29008d8eaa5499a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637517342909842079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Hvok%2F4GMKFlFnGgPBkOqI%2Bd1WW7GE65mJEPCSIuGY24%3D&reserved=0>, where people start using it to mask potential errors instead to fixing them, just as @bmoore-msft<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbmoore-msft&data=04%7C01%7C%7Cacd5f09787434f0ab29008d8eaa5499a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637517342909842079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yjkn%2BNlcOGssQoXgRu%2Bbfhss4iuwe%2FywI%2BDjpQBo0go%3D&reserved=0> mention above.

@bmoore-msft<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbmoore-msft&data=04%7C01%7C%7Cacd5f09787434f0ab29008d8eaa5499a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637517342909852072%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dQMOrcxcSaPGneoqMyz6O3wFXEKe927pMATFCp033ug%3D&reserved=0> In context of user of TTK toolkit what is difference between 'false positive' and bug?

**Comment by bmoore-msft** [comment]
@konjp 

> @bmoore-msft In context of user of TTK toolkit what is difference between 'false positive' and bug?

I tried for a bit to come up with a really clever answer to this...  I couldn't.
