### ISSUE TITLE
"adminUsername Should Not Be A Literal" error generated when using literal variable in an expression

### ISSUE THREAD

**Issue by tristan-earl** [Azure/arm-ttk#317]
I have an `azuredeploy.json` template containing the following:

```
...
"variables": {
  "deploymentName": "Deployment-1.0"
},
"resources": [
  ...
  "properties": {
    ...
    "parameters": {
      "adminUsername": {
        "value": "[reference(resourceId('Microsoft.Resources/deployments', variables('deploymentName')), '2019-10-01').outputs.accountSettings.value.accountAdminName]"
      },
     ...
    }
    ...
  }
  ...
]
```

EXPECTED:
In this case, I'm not setting `adminUsername` to a literal value.  Rather, I'm using a literal variable to reference the output of a previous deployment and setting that to `adminUsername`.  The _"adminUsername Should Not Be A Literal"_ test should pass.

ACTUAL
Running the ARM template tests generates the following failure:
```
[-] adminUsername Should Not Be A Literal (25 ms)
AdminUsername references variable 'deploymentName', which has a literal value. 
```

This seems to be related to this issue: https://github.com/Azure/arm-ttk/issues/37

**Comment by bmoore-msft** [comment]
fixed
