### ISSUE TITLE
Using ListKeys NOT in outputs triggering rule  Outputs-Cannot-Echo-ListKeys-With-Concat

### ISSUE THREAD

**Issue by cicorias** [Azure/arm-ttk#322]
Can you explain how this ARM use of listkeys violates the rule -- it is NOT in the outputs section in the template.

https://github.com/Azure/arm-ttk/blob/master/unit-tests/Outputs-Must-Not-Contain-Secrets/Fail/Outputs-Cannot-Echo-ListKeys-With-Concat.json
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1080406/110704831-841c8700-81c3-11eb-92fb-1a063fb1fdbf.png)

**Comment by bmoore-msft** [comment]
@cicorias - I'm not able to repro this, can you attached the full template/repro?

**Comment by cicorias** [comment]
@bmoore-msft  I sent via internal mail

**Comment by bmoore-msft** [comment]
Ah, got it - thanks... the test that's flagging that code is this one: https://github.com/Azure/arm-ttk/blob/master/arm-ttk/testcases/deploymentTemplate/ResourceIds-should-not-contain.test.ps1#L30 - I was thinking it was a different test.

The correct syntax would be:

```json
"value": "[listkeys(resourceId('Microsoft.Web/sites/host', variables('functionAppName'), 'default'),'2016-08-01').functionKeys.default]"
```

Try that and lmk...

**Comment by cicorias** [comment]
@lgtm
