### ISSUE TITLE
When returning an object via createUiDefinition.json, the tooling reports error Cannot find an overload for "Matches" and the argument count: "1".

### ISSUE THREAD

**Issue by scseely** [Azure/arm-ttk#323]
If the output of the createUiDefintion.json contains an object instead of just a value, the tooling reports the error:
    [-] Controls In Outputs Must Exist (6 ms)
         Cannot find an overload for "Matches" and the argument count: "1".    

Example file attached here: 
[createUiDefinition.json.txt](https://github.com/Azure/arm-ttk/files/6119425/createUiDefinition.json.txt)

**Comment by bmoore-msft** [comment]
@scseely - thx for the repro...

**Comment by bmoore-msft** [comment]
@StartAutomating for debug
