### ISSUE TITLE
False positive IDs Should Be Derived From ResourceIDs in "Microsoft.Web/sites/config/appsettings"

### ISSUE THREAD

**Issue by konjp** [Azure/arm-ttk#324]
Any property that ends with "id" will trigger test to fail. I think solution should be to ignore all 'ID's in properties section.

` {
      "type": "Microsoft.Web/sites/config",
      "name": "[concat(variables('AppServiceName'), '/appsettings')]",
      "apiVersion": "2020-09-01",
      "location": "[parameters('location')]",
      "dependsOn": [
        "[variables('AppServiceName')]"
      ],
      "properties": {
         "SOMEONES_ID": "495f6d91-cceb-4916-bf29-c07bea002443"
      }
    }`

**Comment by SuperKoelle** [comment]
Similar to #281

**Comment by konjp** [comment]
It is similar to #281 in sense that is the same test case failing, but is different in sense of context. Because, in most cases, 'appsettings' are connected to specific application domain resources, not necessary to Azure resources.

**Comment by bmoore-msft** [comment]
I think the thing that will unify the 2 bugs is:

- allow an exclusion list based on resourceType (when type contains *backends*, skip resourceId) - this is #281
- the exclusionList should allow for wild cards (e.g. when I'm in sites/config, skip *ID) - this bug
