### ISSUE TITLE
Template Should Not Contain Blanks in "Microsoft.Web/sites/config/appsettings"

### ISSUE THREAD

**Issue by konjp** [Azure/arm-ttk#325]
I think that empty properties in "Microsoft.Web/sites/config/appsettings" should be ignored, because there are scenario where we want to initialize value of some property for App Service to "empty/blank".

One more argument is in most cases these properties are very application domain specific, therefore empty values should be perfectly legal here.

` {
      "type": "Microsoft.Web/sites/config",
      "name": "[concat(variables('AppServiceName'), '/appsettings')]",
      "apiVersion": "2020-09-01",
      "location": "[parameters('location')]",
      "dependsOn": [
        "[variables('AppServiceName')]"
      ],
      "properties": {
         "SIGNAL_TO_SOMEBODY_THAT_DEFAULT_VALUE_IS_EMPTY": ""
      }
    }`

**Comment by bmoore-msft** [comment]
We should look at this in conjunction with #324 - ideally we use the same approach here...

Another option for fixing these (or unblocking) would be to (see #309 )
