### ISSUE TITLE
Improve error handling when deserializing json

### ISSUE THREAD

**Issue by asears** [Azure/arm-ttk#326]
If a JSON file with incorrect format is in the same folder as an ARM template, the following error is produced.

## Scenario
Create a valid arm template called azuredeploy.json
Create an invalid json file called testrequest.json
Invoke Arm TTK tests.

```powershell
$TemplatePath = ".\arm\mytemplate"
Test-AzTemplate -Verbose -TemplatePath $TemplatePath -MainTemplateFile $MainTemplateFile
```

Result

```powershell
Import-Json: C:\Azure\arm-ttk\arm-ttk\Expand-AzTemplate.ps1:216
Line |
 216 |  …                 $fileObject.Object = Import-Json $fileObject.FullPath
     |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Conversion from JSON failed with error: Unexpected end when deserializing object. Path 'content', line 52, position 5.
```
## Suggestion

It would be useful to include the actual path from $fileObject.FullPath in the above error message, and provide some verbose toggle for details on errors.

In addition, unclear why this file is being picked up at all other than it has a json extension...

**Comment by bmoore-msft** [comment]
@asears - what's the scenario where you want invalid json to be used in your project but ignored by ttk?

I could envision a scenario where we wrap in a try-catch (we don't parse the json, pwsh does) but then we need to make sure we don't catch an error that we didn't want to catch.

**Comment by asears** [comment]
Not necessarily ignored, just surface the specific filename under inspection or throwing error.  Took a bit of time to figure out which file was causing an issue - there was a partial json template causing problems.  I wasn't clear why it was searching every json file instead of just the arm templates and parameters files either...

**Comment by bmoore-msft** [comment]
So throw a warning if we can't parse the json?  or just output the filename?

**Comment by bmoore-msft** [comment]
I'm going to propose we throw an error with the filename in the error.
