### ISSUE TITLE
Validate Template Parameter File

### ISSUE THREAD

**Issue by amorabito2w** [Azure/arm-ttk#337]
I think it would be useful to add support for validating a template's parameter file, similar to how Test-AzDeployment works. Are there any plans to implement such a feature?

**Comment by bmoore-msft** [comment]
We have some in #240 - what kinds of things would you want to test for?

**Comment by amorabito2w** [comment]
- If a deployment template has a parameters template, make sure the parameters template contains all the parameters listed in its deployment template. Must be a 1:1 match.
- Verify that the parameters file has the correct JSON structure and syntax.

I think covering these things would be sufficient for most cases.

**Comment by bmoore-msft** [comment]
Thanks - for the first bullet (matching the template & param file) - would you expect a default (like the example in your 3rd bullet) or always expect that param to be supplied?

**Comment by amorabito2w** [comment]
I think it would make sense for the default behavior to auto locate a deployment template's param file by naming convention, like how it works now. If the ttk param `-TemplateParametersPath` is specified, override the default behavior and expect the `-TemplatePath` param to take a single deployment template file. In this case, maybe have the tool verify that the deployment template file is really a deployment template by ensuring its $schema key matches a proper deployment URI (e.g., https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#).

**Comment by amorabito2w** [comment]
Also, for the 1:1 param match, here's an excerpt of code I made to accomplish what I'm describing:

```
<#
Assume the following:
$template and $paramTemplate contain the current json objects represented as hash tables in a foreach loop
$currentTemplate contains the json file name of the template currently being processed
#>

# If the deployment template doesn't have a parameters key, skip all this
    if ($template.parameters) {    
        # Check that parameters template contains all params listed in the main template
        if ($paramTemplate) {
            $missingParams = Compare-Object `
                -ReferenceObject ($template.parameters.GetEnumerator().Name | Sort-Object) `
                -DifferenceObject ($paramTemplate.parameters.GetEnumerator().Name | Sort-Object) `
                -IncludeEqual

            if ($missingParams.SideIndicator -match '<=|=>') {
                $missingParams | ForEach-Object {
                    if ($_.SideIndicator -eq "<=") {
                        Write-Output "The parameter '$($_.InputObject)' was present in deployment template '$currentTemplate' but was missing from the parameters template '$currentParamTemplate'"
                    }
                    if ($_.SideIndicator -eq "=>") {
                        Write-Output "The parameter '$($_.InputObject)' was present in parameters template '$currentParamTemplate' but was missing from the deployment template '$currentTemplate"
                    }
                }

                Write-Output "Please fix the parameters mismatch and try again"
                Exit
            } else {
                Write-Output "The parameters template matches the deployment template"
            }
        }
    } else {
        Write-Log "The deployment template '$currentTemplate' doesn't have parameters to process"
    }
```

**Comment by bmoore-msft** [comment]
Hang on to this and you can send a PR for it when the other one gets merged ;)

**Comment by StartAutomating** [comment]
Closed as parameter file testing is now possible
