### ISSUE TITLE
Variables Must Be Referenced test improperly flagging copy variable

### ISSUE THREAD

**Issue by scseely** [Azure/arm-ttk#338]
The attached file demonstrates a case where running ARM-TTK will generate a failure for the test Variables Must Be Referenced:

[-] Variables Must Be Referenced (20 ms)
        Unreferenced variable: diskConfig

Variable is declared, using copy. Normally, the number of copies would be passed in as a parameter. Using a hard coded 2 to keep the repro small. DiskConfig is used by variables('allDisks'):
```
    "variables": {
        "disks": {
            "copy": [
                {
                    "name": "diskConfig",
                    "count": 2,
                    "input": {
                        "name": "[format('metadisk-{0,2:D2}', copyIndex('diskConfig',1))]",
                        "diskSizeGB": "120"
                    }
                }
            ]
        },
        "allDisks" : "[variables('disks').diskConfig]"
    },

```

The attachment includes the template in mainTemplate.json and the result of deploying the template in deployment.json.

Expected output: all ARM-TTK tests on the ARM template should pass.

[test.zip](https://github.com/Azure/arm-ttk/files/6239761/test.zip)

**Comment by StartAutomating** [comment]
If we do not find a direct match for a copy variable, we will need to find matches to the variable the copy is within, and then check the surrounding context to determine if it is referencing the correct property.
