### ISSUE TITLE
 Allowed Values Should Actually Be Allowed show errors also for location/allowedValues

### ISSUE THREAD

**Issue by danielecazzari** [Azure/arm-ttk#345]
In my createUiDefinition.json I'm defining the allowed location as shown below.
This seems to be correct according to documentation but arm-ttk report this error

 [-] Allowed Values Should Actually Be Allowed (61 ms)                                                                       
CreateUIDefinition parameter  with value eastus is not allowed in the main template parameter createOrUpdate            CreateUIDefinition parameter  with value eastus2 is not allowed in the main template parameter createOrUpdate           CreateUIDefinition parameter  with value southcentralus is not allowed in the main template parameter  
.....

I'm wondering if config/basics tags are confused with "basics" steps by scripts.

Regards,

Daniele

My code:
            "basics": { 
                "location": {
                    "allowedValues": [
                        "eastus",
                        "eastus2",
                        "southcentralus",
                        "westus2",
                        "australiaeast",
                        "southeastasia",
                        "northeurope",
                        "uksouth",
                        "westeurope",
                        "centralus",
                        "northcentralus",
                        "westus",
                        "southafricanorth",
                        "centralindia",
                        "eastasia",
                        "japaneast",
                        "koreacentral",
                        "canadacentral",
                        "francecentral",
                        "germanywestcentral",
                        "uaenorth",
                        "brazilsouth",
                        "centralusstage",
                        "eastusstage",
                        "eastus2stage",
                        "northcentralusstage",
                        "southcentralusstage",
                        "westusstage",
                        "westus2stage",
                        "asia",
                        "asiapacific",
                        "australia",
                        "brazil",
                        "canada",
                        "europe",
                        "global",
                        "india",
                        "japan",
                        "uk",
                        "unitedstates",
                        "eastasiastage",
                        "southeastasiastage",
                        "centraluseuap",
                        "eastus2euap",
                        "australiasoutheast",
                        "japanwest",
                        "southindia",
                        "westindia",
                        "canadaeast",
                        "ukwest",
                        "uaecentral",
                        "brazilsoutheast"                        
                    ]
                }
            }

**Comment by bmoore-msft** [comment]
@danielecazzari - can you attach an entire file with a repro? (original or a paired down version)

**Comment by danielecazzari** [comment]
Hi,

I'm sorry for the long waiting, but I had to find time to develop a paired down version that you could find here:
[createUiDefinition.json.txt](https://github.com/Azure/arm-ttk/files/6304934/createUiDefinition.json.txt)

Reagards,

Daniele

**Comment by bmoore-msft** [comment]
[mainTemplate.json.txt](https://github.com/Azure/arm-ttk/files/6305489/mainTemplate.json.txt)

np - thanks this is very helpful...  would have never figured that one out on my own ;)

**Comment by bmoore-msft** [comment]
@StartAutomating - the "location" control is in a "config" object and has no "name" property so maybe....

if the $parent.name property is empty, see if the parent property is named "location" - and then use the location() function to find the output to match in mainTemplate

**Comment by danielecazzari** [comment]
Hi, 
do you have any update on when this issue will be fixed?

Thanks a lot

Daniele

**Comment by bmoore-msft** [comment]
This is slated for M6 closer to end of month

**Comment by bmoore-msft** [comment]
@danielecazzari - I'm not seeing anything in my inbox - did you send to "bmoore" ?

**Comment by danielecazzari** [comment]
@bmoore-msft yes. I just sent now another email without an attachment to see if this works.

**Comment by bmoore-msft** [comment]
@StartAutomating - Let's make sure we have a test case for this one

**Comment by StartAutomating** [comment]
@bmoore-msft will do

**Comment by bmoore-msft** [comment]
Entered a new issue for this... in #526
