### ISSUE TITLE
apiVersions Should Be Recent masked in templates

### ISSUE THREAD

**Issue by lr90** [Azure/arm-ttk#351]
I was chasing something else when I spotted this.

main.bicep
```
param privatelinkDnsZoneName string

module dns 'dns.bicep' = {
  name: 'dnsDeploy'
  params: {
    privatelinkDnsZoneName: privatelinkDnsZoneName
  }
}
```

and dns.bicep
```
param privatelinkDnsZoneName string

resource privatelinkDnsZone 'Microsoft.Network/privateDnsZones@2018-09-01' = {
  name: privatelinkDnsZoneName
  location: 'Global'
}
```

If I transpile & test dns.bicep the out of date API is correctly failed.

However if I transpile main.bicep and test no tests fail and I'm not alerted to the out of date API being used by the module?

**Comment by bmoore-msft** [comment]
Got it - this is due to bicep putting everything into a single file - the TTK does not handle nested/inline templates well (or at all in many tests...

**Comment by bmoore-msft** [comment]
#557
