### ISSUE TITLE
Tooltip requirement validation incorrectly selects non-control elements

### ISSUE THREAD

**Issue by ascott18** [Azure/arm-ttk#353]
Tooltips-Should-Be-Present.test.ps1 is performing the following, very naive search to find resource elements: https://github.com/Azure/arm-ttk/blob/807e9428d0d3f9db124a95df2e7b9c5cbe02f10e/arm-ttk/testcases/CreateUIDefinition/Tooltips-Should-Be-Present.test.ps1#L18-L19

This is incorrectly picking up the "body" request parameter of a `Microsoft.Solutions.ArmApiControl` control.

The following is an example that incorrectly causes a validation failure:

``` json
      {
        "name": "dbServerNameCheck",
        "type": "Microsoft.Solutions.ArmApiControl",
        "toolTip": "https://github.com/Azure/arm-ttk/issues/352",
        "request": {
          "method": "POST",
          "path": "[concat(subscription().id, '/providers/Microsoft.Sql/checkNameAvailability?api-version=2014-04-01')]",
          "body": {
            "name": "[basics('database_server_name')]",
            "type": "Microsoft.Sql/servers"
          }
        }
      },
```
 
The failure occurs when the validation script sees `"type": "Microsoft.Sql/servers"`. This matches `Microsoft.*` that the tooltip validation test is looking for.

This can be worked around in a silly way by adding an extraneous "toolTip" parameter to the request body:

``` json
          "body": {
            "name": "[basics('database_server_name')]",
            "type": "Microsoft.Sql/servers",
            "toolTip": "https://github.com/Azure/arm-ttk/issues/353"
          }
```

**Comment by bmoore-msft** [comment]
Should be done in #357 - thanks for both of these...
