### ISSUE TITLE
Template/Repo Complexity Scoring

### ISSUE THREAD

**Issue by kilasuit** [Azure/arm-ttk#360]
I was wondering if there would be any desire to build either into ARM-TTK natively or as a standalone tool an optional mechanism that will programaticaly determine a complexity score for a Template/series of templates/whole repo.

This may help with people understand what they do in ARM that is hard today, that they perhaps could do with more easily maintained code by using a combination of other tooling Bicep/PSArm, Template Specs, PowerShell Scripts, CLI scripts etc as opposed to native ARM. 

It would likely be biased and only give an indicative score but would give a quick overview without reading hundreds/thousands lines of code.

**Comment by kilasuit** [comment]
A complexity score would be calculated based looping through a template and assigning a predefined number of points for particular aspects of the template.

You'd score each parameter based on what type they are & whether they have defaults/min/max/allowed ranges, description & whether they make use of any ARM Functions in a default value
You'd score each variable based on what type they are (int, string or object) if an object it'll need to score each property (& sub property) individually & whether they make use of any ARM Functions
You'd score each resource based each property of that resource (& sub properties) individually and whether they make use of any ARM Functions. You'd also score based on whether it has dependencies or is conditionally deployed.
You'd score each output based on what type they are (int, string or object) if an object it'll need to score each property (& sub property) individually & whether they make use of any ARM Functions
You'd then need to score each custom function but I'd initially just suggest that you query how many are defined and give a set score for each.

Overall you'd then get a score that would dictate how complex a template is - which could be simplified to show a textual output along the lines of `Simple`,`Moderate`,`Complex but maintainable`,`Complex & likely unmaintainable`

**Comment by StartAutomating** [comment]
@kilasuit as this project is switching into maintenace mode, we are unlikely to add new sets of features.

**Comment by kilasuit** [comment]
This is complete as of releasing this repo - https://github.com/kilasuit/ARMTemplateComplexity
