### ISSUE TITLE
Secure parameter defaults containing newGuid() should pass but don't

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/arm-ttk#367]
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "psContainsNewGuid": {
      "type": "secureString",
      "defaultValue": "[concat(newGuid(), 'hello')]"
    }
  },
  "functions": [],
  "resources": []
}
```

  [-] Secure String Parameters Cannot Have Default (3 ms)                                                                                                                                       Parameter psContainsNewGuid is a SecureString and must not have a default value unless it is an expression that contains the newGuid() function.

**Comment by StephenWeatherford** [comment]
The docs don't mention newguid at all: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/test-cases#declared-parameters-must-be-used

**Comment by bmoore-msft** [comment]
@StartAutomating need a unit test for this as well

**Comment by StartAutomating** [comment]
This looks fairly easy to workaround with ?<ARM_Template_Function>

**Comment by bmoore-msft** [comment]
#549
