### ISSUE TITLE
adminUsername-Should-Not-Be-A-Literal does not catch hardcoded variables

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#37]
Taking a note while reviewing a PR... if the adminUsername property uses a variable and the variable is not an expression, this test won't find it... it looks like we are excluding top-level properties (technically second level properties) so we aren't finding vars with Find-JSONContent.

**Comment by StartAutomating** [comment]
Just an FYI on this one:  because it uses the new Regex goodness, and the one expression that had an import issue, you'll need to approve #259 before this test will pass.
