### ISSUE TITLE
The "apiVersions Should Be Recent In Reference Functions" test fails for any version but preview

### ISSUE THREAD

**Issue by nsucheninov** [Azure/arm-ttk#381]
It looks like that the "apiVersions Should Be Recent In Reference Functions" test fails for any version but preview.

[loadFunction.zip](https://github.com/Azure/arm-ttk/files/6570924/loadFunction.zip)

Microsoft.Storage/storageAccounts supports the following API versions:
`
(Get-AzResourceProvider -ProviderNamespace Microsoft.Storage).ResourceTypes | Where-Object ResourceTypeName -eq storageAccounts

ResourceTypeName : storageAccounts
Locations        : {East US, East US 2, West US, West Europe...}
ApiVersions      : {2021-04-01, 2021-02-01, 2021-01-01, 2020-08-01-preview...}
`

If I specify any of 2021-04-01, 2021-02-01, 2021-01-01 I get "Microsoft.Storage/storageAccounts is using an invalid apiVersion".
It works with 2020-08-01-preview onlt.

`
            {
              "name": "AzureWebJobsDashboard",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', variables('storageAccountName'), ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', variables('storageAccountName')), '2020-08-01-preview').key1)]"
            },
            {
              "name": "AzureWebJobsStorage",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', variables('storageAccountName'), ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', variables('storageAccountName')), '2020-08-01-preview').key1)]"
            },
            {
              "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', variables('storageAccountName'), ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', variables('storageAccountName')), '2020-08-01-preview').key1)]"
            }
`

The same is true for 'Microsoft.Automation/automationAccounts'.

**Comment by bmoore-msft** [comment]
@nsucheninov I'm not able to repro with your file on the latest version of the TTK - can you try pulling the latest and see if it still repros (https://aka.ms/arm-ttk-latest)

Failing that - can you look at your cache folder and see what it has for the /storageAccounts and /automationAccounts?

**Comment by nsucheninov** [comment]
@bmoore-msft sorry, I've uploaded a "fixed" template with the preview API version. Here is the right one.
[loadFunction.zip](https://github.com/Azure/arm-ttk/files/6593207/loadFunction.zip)

The test fails for the all 3 API versions:  '2021-04-01, 2021-02-01 and 2021-01-01. I run ARM TTK in a pipe so it always downloads and uses the latest ARM TTK.
The cache is on the MS hosted agent. What should I look for in the /storageAccounts folser?
`
            {
              "name": "AzureWebJobsDashboard",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', variables('storageAccountName'), ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', variables('storageAccountName')), '2021-04-01').keys[0].value)]"
            },
            {
              "name": "AzureWebJobsStorage",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', variables('storageAccountName'), ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', variables('storageAccountName')), '2021-02-01').keys[0].value)]"
            },
            {
              "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', variables('storageAccountName'), ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', variables('storageAccountName')), '2021-01-01').keys[0].value)]"
            },
`

**Comment by bmoore-msft** [comment]
it still comes back clean for me - I did another cache update and publish to the https://aka.ms/arm-ttk-latest endpoint...  Can you confirm that's where you're downloading from (and try with this mornings refresh)

**Comment by nsucheninov** [comment]
Looks like someone fixed the issue. ) 
Yesterday, it was here
![image](https://user-images.githubusercontent.com/26557011/120840384-9e2bf280-c583-11eb-9467-7b716bf43823.png)
But today's run completed with a different message that makes sense.
![image](https://user-images.githubusercontent.com/26557011/120840449-b3088600-c583-11eb-8946-6c30a2bf9d08.png)

Thank you, @bmoore-msft!

**Comment by bmoore-msft** [comment]
Cool - thanks for confirming... we've been messing about trying to get an automated cache refresh going... may actually be there...
