### ISSUE TITLE
AllAzureResources.cache.json outdated

### ISSUE THREAD

**Issue by anwojcie** [Azure/arm-ttk#383]
Hi,

My Issue is the outdated Cache (AllAzureResources.cache.json)

for "Microsoft.Storage/storageAccounts"
in master
```json
...
  "Microsoft.Storage/storageAccounts": [
    {
      "aliases": null,
      "apiProfiles": [
      ],
      "apiVersions": [
        "2020-08-01-preview",
        "2019-06-01", // which is now failing the less than 2 year old requirement
        "2019-04-01",
...
```

if I manually update the Cache
```json
...
  "Microsoft.Storage/storageAccounts": [
    {
      "aliases": null,
      "apiProfiles": [
      ],
    "apiVersions": [
        "2021-04-01",
        "2021-02-01",
        "2021-01-01",
        "2020-08-01-preview",
        "2019-06-01",
        "2019-04-01",
...
```

it is somewhat similar for roleassignments.
I'd love to see the cache being updated.
I'd even more love the cache to be decoupled and updateable on its own.
unfortunately running the Update-TTKCache within pipelines would cost too much time next to the need of az cmd being authenticated.
An regularly/automated updated json somewhere downloadable would be highly appreciated. Maybe a Branch "Cachelatest" and the appropriate changes in Update-TTKCache.

Thanks,
Andre

**Comment by bmoore-msft** [comment]
Have been trying to get this working https://github.com/Azure/arm-ttk/actions/workflows/update-cache.yml - I think we may finally have it.  So we'll get a PR on a schedule (though the diff doesn't seem to be working as expected) but if it sticks, we'll have a bi-weekly update.

I also commented out the VM Image cache update - I don't think that's used anywhere... that was taking up the bulk of the time. Though if you're not authenticated this still isn't a route to take.

With the bi-weekly update - you could download from master's raw location...  that way if we slow down on other updates in the TTK you'd still have the latest.

Try that, lmk what you think - feel free to reopen if it still doesn't seem right...

**Comment by anwojcie** [comment]
Hi Brian,

Thanks!
I simply added
        Import-Module "$SCRIPT:Tempfolder/arm-template-toolkit/arm-ttk/arm-ttk.psd1"
        #Update ttk cache (Api Versions...)
        Invoke-WebRequest -Method Get -Uri https://github.com/Azure/arm-ttk/raw/master/arm-ttk/cache/AllAzureResources.cache.json -OutFile "$((Get-Module -Name arm-ttk).ModuleBase)\cache\AllAzureResources.cache.json"

worked well!

In regards to your pipeline, instead of iterating through *.cache.json to diff,  you could use
(git status --porcelain=v1) -match "^ M (?<ChangedFile>.*.cache.json$)"
if (!$Matches) {
    "nothing to do"
    break
}
else {
    $Matches.ChangedFile | ForEach-Object {
        git add $_
        git commit -m "Updating $_"

    }
    "PR"

}


Cannot remember where, but I used something similar to update docs for a pwsh module with platyPS and created a PR only if md files were updated.

Thanks again,
Andre


________________________________
