### ISSUE TITLE
DeploymentParameters-Should-Have... has an incorrect regular expression

### ISSUE THREAD

**Issue by etpedror** [Azure/arm-ttk#384]
The regular expression on line 28 is 
```
'^(\d+\\.\d+\\.\d+\\.\d+)$'
```
which doesn't match "1.0.0.0", for example.
It should be
```
'^(\d+\.\d+\.\d+\.\d+)$'
```
which does match "1.0.0.0"

**Comment by bmoore-msft** [comment]
@StartAutomating any idea how the unit-tests missed this?  I can repro running directly on 100-marketplace-sample, but when running just these tests it's not flagged?

**Comment by StartAutomating** [comment]
The Regex change looks good.

It would not fail tests because it's currently emitting a warning.

We should consider adding a "Warn" folder to our Pass/Fail folders list, so that we can have tests that validating a warning is produced.

**Comment by bmoore-msft** [comment]
Looks like unit tests miss the case because this throws a warning and not an error...

I'm going to fix the regex, but leave this bug open, to track the unit-test issues.
