### ISSUE TITLE
cannot debug individual tests that use Find-JsonContent or Expand-AzTemplate

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#41]
tests that use one of our shared functions (e.g. Find-JsonContent) cannot be run and debugged individually because the function is not found/loaded when running scripts individually...

We'd need to conditionally load the fn before running

```powershell
# First, find all objects with an ID property in the MainTemplate.
$ids = $TemplateObject  | Find-JsonContent -Key *id <#-Value *#> -Like
```

**Comment by bobbyangers** [comment]
Hi @bmoore-msft ,

Is this still pertinent ?

If so, how would I only run one unit-test.

**Comment by StartAutomating** [comment]
@bmoore-msft  @bobbyangers  I don't believe this is still pertinent, and it has an easy workaround:

Import the module first.
