### ISSUE TITLE
Check to flag preview VM versions is inaccurate

### ISSUE THREAD

**Issue by VeraBE** [Azure/arm-ttk#416]
"Virtual machines should not be preview" is checking for "-preview" in a "Version" property, and doesn't check for the text in "offer" properties

**Comment by bmoore-msft** [comment]
@VeraBE - are you seeing cases of -preview being in offer and not version?

**Comment by VeraBE** [comment]
@bmoore-msft We received feedback from the private preview saying that. Maybe @JohnathonMohr or @yane3628 can provide more details

**Comment by JohnathonMohr** [comment]
If you look at the template schema for VMs, I believe it's an object, so doing a string comparison doesn't really make sense.

**Comment by yane3628** [comment]
It was brought up to us that this rule should likely check the offer field and not the version field.

**Comment by bmoore-msft** [comment]
It may make sense to have the customer leave the feedback here - I suspect it's "both" that need to be checked but don't know that I have a working example anymore...

**Comment by bmoore-msft** [comment]
@VeraBE - do you have an example template we can use to repro?

**Comment by VeraBE** [comment]
I don't :/ @JohnathonMohr or @yane3628 maybe have one?

**Comment by yane3628** [comment]
I haven't been able to find one...

**Comment by bmoore-msft** [comment]
ok, I updated the test to check all properties - it's a little broader than the initial intent of the test but feels correct... we'll see.
