### ISSUE TITLE
Test 'URIs Should Be Properly Constructed' limits usage of templates

### ISSUE THREAD

**Issue by pavelsalamon** [Azure/arm-ttk#417]
With newly added test **URIs Should Be Properly Constructed**, it's impossible to produce url as template output dynamically.

I was producing template output in this way:
```
"outputs": {
    "ServerUrl": {
      "type": "string",
      "value": "[concat('http://', reference(variables('publicIPAddressName')).dnsSettings.fqdn, '/somepath')]"
    }
  }
```

This doesn't pass through the test because of usage of concat function.

However, I can't produce the url without using concat function - trying to use uri() instead is not possible because uri() is too restrictive on its first parameter. Any attempt to use uri() function fails with errors like these:
```
The template language function 'uri' expects its first argument to be a uri string. The provided value is 'http://'
```
Here's an example of my attempt with uri:
```
"outputs": {
    "ServerUrl": {
      "type": "string",
      "value": "[uri(uri('http://', reference(variables('publicIPAddressName')).dnsSettings.fqdn), 'somepath')]"
    }
}
```

I tried putting various strings as first parameter of uri: `http`, `http:`, `http://` and they all fail. It only accepts uri with some path in it, but I can only produce that using concat function.

**Comment by bmoore-msft** [comment]
We are also incorrectly flagging concat/format in the value - it should be disallowed at the beginning of the expression only.

@pavelsalamon - the proper format for your case would be:

```
"outputs": {
    "ServerUrl": {
      "type": "string",
      "value": "[uri(concat('http://', reference(variables('publicIPAddressName')).dnsSettings.fqdn), 'somepath')]"
    }
}
```

But the test will also flag that (you may have tried already) - so the test is to broad in it's assumptions and needs to be fixed.

**Comment by bmoore-msft** [comment]
I've commented out the test for now...

**Comment by bmoore-msft** [comment]
#564

**Comment by grube** [comment]
A few days ago our ARM template validation tests started failing with this error:
![arm fail 1](https://user-images.githubusercontent.com/6074005/151512658-199a794c-0f43-462e-ab95-8fb8df0f95f8.png)

We are creating a dynamic URL like this:
` "myURL": "[concat('https://mydownloaddeployment=', guid(deployment().name))]",`
could it be related to this change?

**Comment by grube** [comment]
Yes, using of Concat() inside of URI() function works, and passes validation.
Just needed to tweak a bit my Uri and split it in base and relative parts, something like this:

`   "myURL": "[uri('https://',concat('mydownloaddeployment=', guid(deployment().name)))]"`
