### ISSUE TITLE
Unclear Allowed Values Should Actually Be Allowed error

### ISSUE THREAD

**Issue by danielecazzari** [Azure/arm-ttk#424]
Hi,

I'm receiving the below error but I'm not really able to understand what I did wrong.
Could you help me?

I could share my template via mail if needed.  

 CreateUIDefinition
  [-] Allowed Values Should Actually Be Allowed (2848 ms)
  CreateUIDefinition parameter  is not allowed in the main template parameter clusterName
  CreateUIDefinition parameter postgreSQLTier is not allowed in the main template parameter postgreSQLserverName
  CreateUIDefinition parameter managedClustersDropDown is not allowed in the main template parameter clusterName
  CreateUIDefinition parameter userAssignedIdentitiesDropDown is not allowed in the main template parameter clusterName  

Regards,

Daniele

**Comment by jvhoof** [comment]
Hi,

Running into the same issue as the original post. The parameter 'instanceType' doesn't have to relation with the parameters 'fortiGateImageSKU' or 'fortiGateImageVersion'. Adding a allowValues in constraints in the instanceType of the createUIDefinition didn't help.


```
Validating A-Single-VM\createUiDefinition.json                                                                                                                                           CreateUIDefinition                                                                                                                                                                       [-] Allowed Values Should Actually Be Allowed (189 ms)                                                                                                                                     CreateUIDefinition parameter fortiGateImageSKU with value fortinet_fg-vm is not allowed in the main template parameter instanceType
CreateUIDefinition parameter fortiGateImageSKU with value fortinet_fg-vm_payg_20190624 is not allowed in the main template parameter instanceType
CreateUIDefinition parameter fortiGateImageVersion with value 6.2.0 is not allowed in the main template parameter instanceType
CreateUIDefinition parameter fortiGateImageVersion with value 6.2.2 is not allowed in the main template parameter instanceType
CreateUIDefinition parameter fortiGateImageVersion with value 6.2.4 is not allowed in the main template parameter instanceType
CreateUIDefinition parameter fortiGateImageVersion with value 6.2.5 is not allowed in the main template parameter instanceType
CreateUIDefinition parameter fortiGateImageVersion with value 6.4.0 is not allowed in the main template parameter instanceType
CreateUIDefinition parameter fortiGateImageVersion with value 6.4.2 is not allowed in the main template parameter instanceType
CreateUIDefinition parameter fortiGateImageVersion with value 6.4.3 is not allowed in the main template parameter instanceType
CreateUIDefinition parameter fortiGateImageVersion with value 6.4.5 is not allowed in the main template parameter instanceType
CreateUIDefinition parameter fortiGateImageVersion with value 7.0.0 is not allowed in the main template parameter instanceType
CreateUIDefinition parameter fortiGateImageVersion with value latest is not allowed in the main template parameter instanceType
```
Links to the templates:
https://github.com/40net-cloud/fortinet-azure-solutions/blob/main/FortiGate/A-Single-VM/createUiDefinition.json
https://github.com/40net-cloud/fortinet-azure-solutions/blob/main/FortiGate/A-Single-VM/azuredeploy.json

The below commit causes this issue to appear. Trying to understand what should change in the template.
https://github.com/Azure/arm-ttk/commit/1abc32bfa857d0398396096abff5621c4ae08295#diff-19ba764d0919554305f765fa1edaf1b5a0eb3dc008d5208a7ab6455a36d46ffa

Regads,

Joeri

**Comment by danielecazzari** [comment]
@bmoore-msft Just as a note the template shared via mail is valid also for this issue

**Comment by matijahanzic** [comment]
Same issue, it can confirm this worked before this commit:
https://github.com/Azure/arm-ttk/commit/1abc32bfa857d0398396096abff5621c4ae08295#diff-19ba764d0919554305f765fa1edaf1b5a0eb3dc008d5208a7ab6455a36d46ffa

We tried to change our template to pass the validation but it is completely mismatching the parameters.
