### ISSUE TITLE
Validation scripts request to move to new api even if just in preview

### ISSUE THREAD

**Issue by danielecazzari** [Azure/arm-ttk#425]
The arm-ttk suite on eventHubTemplate.json report an "apiVersions Should Be Recent" error even if the most recent API available is only in preview.
As per my understanding, new API should usage should be forced only if there is a more recent non-preview version.

 @bmoore-msft the template shared via mail is valid also for this issue.

Regards,

Daniele

-------------------------------
Validating templates\eventHubTemplate.json

[+] adminUsername Should Not Be A Literal (167 ms)
[+] apiVersions Should Be Recent In Reference Functions (123 ms)
[-] apiVersions Should Be Recent (215 ms)
                   Api versions must be the latest or under 2 years old (730 days) - API version 2017-04-01 of Microsoft.EventHub/namespaces is 1542 days old
                   Valid Api Versions:
                   2021-01-01-preview
                    Api versions must be the latest or under 2 years old (730 days) - API version 2017-04-01 of Microsoft.EventHub/namespaces/eventhubs is 1542 days old            Valid Api Versions:
                   2021-01-01-preview
                    Api versions must be the latest or under 2 years old (730 days) - API version 2017-04-01 of Microsoft.EventHub/namespaces/eventhubs/authorizationRules is 1542 days old             Valid Api Versions:
                   2021-01-01-preview
                    Api versions must be the latest or under 2 years old (730 days) - API version 2017-04-01 of Microsoft.EventHub/namespaces/eventhubs/authorizationRules is 1542 days old             Valid Api Versions:
                   2021-01-01-preview
                    Api versions must be the latest or under 2 years old (730 days) - API version 2017-04-01 of Microsoft.EventHub/namespaces/eventhubs is 1542 days old            Valid Api Versions:
                   2021-01-01-preview
                    Api versions must be the latest or under 2 years old (730 days) - API version 2017-04-01 of Microsoft.EventHub/namespaces/eventhubs/authorizationRules is 1542 days old             Valid Api Versions:
                   2021-01-01-preview
                    Api versions must be the latest or under 2 years old (730 days) - API version 2017-04-01 of Microsoft.EventHub/namespaces/eventhubs/authorizationRules is 1542 days old             Valid Api Versions:
                   2021-01-01-preview
                    Api versions must be the latest or under 2 years old (730 days) - API version 2017-04-01 of Microsoft.EventHub/namespaces/AuthorizationRules is 1542 days old   Valid Api Versions:
                   2021-01-01-preview

**Comment by bmoore-msft** [comment]
@danielecazzari - your understanding is correct (this is a bug)

**Comment by bmoore-msft** [comment]
@StartAutomating - simple repro:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "apiVersion": "2017-04-01",
            "name": "namespace",
            "type": "Microsoft.EventHub/namespaces",
            "location": "global",
            "properties": {
            }
        }
    ]
}
```

**Comment by bmoore-msft** [comment]
Also, I'm guessing this needs to be fixed in both apiVersion tests...

**Comment by bmoore-msft** [comment]
probably related to #226

**Comment by palchak** [comment]
@bmoore-msft I get validation error while using ARM-TTK which has the API Version Test. The test is flagging the resource Microsoft.DevTestLab/schedules [](https://docs.microsoft.com/en-us/azure/templates/microsoft.devtestlab/2018-09-15/schedules?tabs=bicep). The latest API version is 2 years old and there is no latest version available

**Comment by bmoore-msft** [comment]
@palchak - thanks...  

for the repro:

```json

{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "apiVersion": "2018-09-15", // is the latest non-preview version - "2018-10-15-preview" is the latest preview version
            "name": "namespace",
            "type": "Microsoft.DevTestLab/schedules",
            "location": "global",
            "properties": {
            }
        }
    ]
}

```

**Comment by bmoore-msft** [comment]
#558
