### ISSUE TITLE
api Version test output is displaying all lines/columns for all error instances

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#431]
Running the test on this sample:
- produces multiple errors for what should be a single error
- uses the wrong apiVersion for comparison on the HDInsights/clusters resource (so there should actually be no errors)

https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.hdinsight/hdinsight-custom-ambari-db/azuredeploy.json

**Comment by bmoore-msft** [comment]
I think I got most of what was happening here, it wasn't so much the test as the output was leading to the wrong conclusion.  That should be cleaned up with #435 - leaving this open so we have something to track cleaning up this:

![image](https://user-images.githubusercontent.com/10090014/123169141-81763280-d43e-11eb-8a86-47c6342f8cc1.png)

There should be exactly 1 line/column for each error...

**Comment by bmoore-msft** [comment]
Ok, now the above sample doesn't even complain about the apiVersion - manually update to ```2015-03-01-preview``` doesn't cause the TTK to throw an error.  So something else to look into.

**Comment by StartAutomating** [comment]
@bmoore-msft:  That's weird.  Please assign to me and I'll dig in to our favorite test.
