### ISSUE TITLE
TTK should be able to provide guidance about api versions to use that will also work for US-Gov or other environments

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/arm-ttk#434]
The TTK rule encourages us to use the most recent apiversion available, but then I find I have to downgrade once I run against US-Gov because it's too recent.  I don't like the back-and-forth required.  Can we can more specific guidance on api versions available that will be okay for both the recent-apiversion rule and US gov or whatever environment?  thx.

**Comment by bmoore-msft** [comment]
I like this, we'd need to have separate caches and the TTK would have to intake an environment() param (to know which cache to use) - probably not required by default.

The flip side is the TTK is occasionally a canary that tells us we're missing an update in other clouds though probably not the best solution for such a discovery.

**Comment by bmoore-msft** [comment]
We're going to leave this as is - partially due to the low use for FF and partially to keep the canary in the coal mine.
