### ISSUE TITLE
JSon Parsing Error, nested template

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#443]
When I embed an empty nested template I receive teh following error

ConvertFrom-Json: C:\Users\ARM\Source Code\GitHub\drewkg\Azure\ARM\Policy\DiagnosticSettings\LogAnalytics\ARM-TTK\arm-ttk\Expand-AzTemplate.ps1:304:51                                                                                                                                                 LLine |                                                                                                                                                304 |                  $TemplateObject = $TemplateText | ConvertFrom-Json                                                                                |                                                    ~~~~~~~~~~~~~~~~                                                                                | Conversion from JSON failed with error: Additional text encountered after finished reading JSON content: :. Path '', line 1,                       | position 10. 

The nested section, taken from a Bicep repository, converted into ARM, is as follows

  "resources": [
    {
      "name": "getManagementGroupName",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2019-10-01",
      "location": "[parameters('location')]",
      "properties": {
        "expressionEvaluationOptions": {
          "scope": "inner"
        },
        "mode": "Incremental",
        "template": {
          "$schema": "https://schema.management.azure.com/schemas/2019-08-01/managementGroupDeploymentTemplate.json#",
          "contentVersion": "1.0.0.0",
          "resources": []
        }
      }
    },

This provides the ability to retrieve the current Management Group name that the deployment is being run against.

**Comment by nsucheninov** [comment]
The same issue. We have some ARM templates that contains nested templates. ARM TTK generates two errors for these templates:
`Conversion from JSON failed with error: Additional text encountered after finished reading JSON content: :. Path '', line 1, position 10."`
`Empty property:  {} found on line: 50"`
A sample template is attached.
[applicationInsights.zip](https://github.com/Azure/arm-ttk/files/6753947/applicationInsights.zip)

**Comment by drewkg** [comment]
I am not sure if this is related, but this template https://raw.githubusercontent.com/drewkg/Azure/feature/ARMTTK/ARM/Policy/DiagnosticSettings/LogAnalytics/azuredeploy.json

is still causing issues when parsing the json, the error message from AzDO pipeline is ##[error]ConvertFrom-Json : Invalid JSON primitive:  {}{

**Comment by bmoore-msft** [comment]
@drewkg - can you open a new issue for this one?  Feel free to cross ref this one...

**Comment by drewkg** [comment]
@bmoore-msft will do, I am trying to distil down to the smallest possible reproducible.

**Comment by bmoore-msft** [comment]
appreciated for sure...
