### ISSUE TITLE
template with nested deployment gives wrong errors for an adjacent template (e.g. rbac/azuredeploy.json) 

### ISSUE THREAD

**Issue by ReneRebsdorf** [Azure/arm-ttk#447]
Some resources, such as microsoft.insights/actionGroups only support having the location as "Global".
As a result I don't see a good reason why it should be enforced to be referenced from a parameter.

May I suggest the "Location Should Not Be Hardcoded" test is ammended with a check on whether the value is 'Global', in which case the check should not fail?

**Comment by ReneRebsdorf** [comment]
The error we get is: "Conversion from JSON failed with error: Additional text encountered after finished reading JSON"
While the error message here is an issue in it self, I am guessing it occurs due to the above descrepency.

Full exception:

``` text
System.ArgumentException: Conversion from JSON failed with error: Additional text encountered after finished reading JSON content: :. Path '', line 1, position 10.
---> Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: :. Path '', line 1, position 10.
at Newtonsoft.Json.JsonTextReader.Read()
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, JsonSerializerSettings settings)
at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable, Nullable1 maxDepth, ErrorRecord& error) in /PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs:line 179 --- End of inner exception stack trace --- at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable, Nullable1 maxDepth, ErrorRecord& error) in /PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs:line 209
at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input) in /PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertFromJsonCommand.cs:line 116
at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.EndProcessing() in /PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertFromJsonCommand.cs:line 76
at System.Management.Automation.Cmdlet.DoEndProcessing() in /PowerShell/src/System.Management.Automation/engine/cmdlet.cs:line 187
at System.Management.Automation.CommandProcessorBase.Complete() in /PowerShell/src/System.Management.Automation/engine/CommandProcessorBase.cs:line 592 in template file azureDeploy.json


Stack trace
at &lt;ScriptBlock&gt;, /home/vsts/work/_temp/arm-ttk/arm-ttk/testcases/deploymentTemplate/Location-Should-Not-Be-Hardcoded.test.ps1: line 25
at Test-Case, /home/vsts/work/_temp/arm-ttk/arm-ttk/Test-AzTemplate.ps1: line 268
at Test-Group, /home/vsts/work/_temp/arm-ttk/arm-ttk/Test-AzTemplate.ps1: line 308
at Test-FileList, /home/vsts/work/_temp/arm-ttk/arm-ttk/Test-AzTemplate.ps1: line 540
at Test-AzTemplate&lt;End&gt;, /home/vsts/work/_temp/arm-ttk/arm-ttk/Test-AzTemplate.ps1: line 685
at &lt;ScriptBlock&gt;, /home/vsts/work/_temp/60d9f0bd-90bc-4f8b-8256-dda60cfe18b2.ps1: line 16
at &lt;ScriptBlock&gt;, &lt;No file&gt;: line 1
```

**Comment by bmoore-msft** [comment]
Can you provide a template for repro?

**Comment by ReneRebsdorf** [comment]
> Can you provide a template for repro?

Certainly - I am on annual leave at the moment though, will get back to you as soon as I am able.
Thanks

**Comment by bmoore-msft** [comment]
perfect - thx...

**Comment by ReneRebsdorf** [comment]
@bmoore-msft 

I've attached a [zip file](https://github.com/Azure/arm-ttk/files/6854453/arm.zip)

In the files I've taken out a lot of irrelevant content, and their associated parameter files. I hope this helps in narrowing down the problem.

the zip file consists of these files:
./azureDeploy.json
./rbac/azureDeploy.json

I reproduce by using "Test-AzTemplate ." in the root folder of the extracted content.

Interested things I found:

- Testing with "Test-AzTemplate ./rbac" does not reproduce the error
- Removing the rbac folder and content causes the error to go away, despite not being reproducable directly on the rbac folder
- I observe the following unexpected errors: 
  - Cannot find an overload for "Matches" and the argument count: "2" (Test-AzTemplate.ps1:324 & Test-AzTemplate.ps1:328)
  - Conversion from JSON failed with error: Additional text encountered after finished reading JSON content: :. Path '', line 1, position 10. (for the error "Location Should Not Be Hardcoded" - it seems to do this for *nested deployments* only.

**Comment by bmoore-msft** [comment]
Ah - ok, thanks... I'm pretty sure this is coming from the nested deployment and is the same as #439...  I commented out the nested deployment and everything passes.

The odd part I don't understand is why the rbac/azuredeploy.json deployment test is returning errors for resources it does not contain - though I suspect related to the mishandling of nesting.

@StartAutomating - this looks to be the same as #439 but the extra/unexpected behavior makes me want to leave this open so we can be sure there's not more going on with this particular repro.

@ReneRebsdorf - I did copy/paste your resource (that has the location = global) to the parent of the template and it seems to work just fine... so I'm going to update the title of this one.

**Comment by ReneRebsdorf** [comment]
I agree, thank you for the quick review.

**Comment by bmoore-msft** [comment]
Thanks for the repro ;)

**Comment by bmoore-msft** [comment]
@ReneRebsdorf - can you check with the latest bits - should be fixed, if not please reopen.

**Comment by ReneRebsdorf** [comment]
> @ReneRebsdorf - can you check with the latest bits - should be fixed, if not please reopen.

Will do

**Comment by ReneRebsdorf** [comment]
@bmoore-msft 

Unfortunately I am still able to reproduce using the provided zip:

``` text
Line |                                                                                                                                                                                     509 |  …                    $TemplateObject = $TemplateText | ConvertFrom-Json                                                                                                                |                                                         ~~~~~~~~~~~~~~~~                                                                                                                | Conversion from JSON failed with error: Additional text encountered after finished reading JSON content: :. Path '', line 1, position 10.
```

Reproduced using this command:
Test-AzTemplate -TemplatePath "./"
