### ISSUE TITLE
Setup releases for arm-ttk 

### ISSUE THREAD

**Issue by kilasuit** [Azure/arm-ttk#448]
It would be useful to set up releases for arm-ttk that did the following 

- Update module version
- create a Zip of arm-ttk module
- Publish module to PowerShell Gallery
- Publish the zip as a release to this repository

This would be helpful as it would allow for organisations & individual developers to make use of arm-ttk much easier in their local & hosted build pipelines

**Comment by ReneRebsdorf** [comment]
Yes please!
Or at least made the zip file available that is available [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/test-toolkit) come from a github release, so that we can be sure the zip file is updated with the latest from the master branch.

**Comment by bmoore-msft** [comment]
Certainly the gallery is the correct place (we have a task for that) - will take a look at option 4 above and see if we can automate that...
