### ISSUE TITLE
Template Should not contain Blanks, Inner Scope

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#465]
This simple template

{
	"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
	"resources": [
		{
			"name": "NestedDeployment",
			"type": "Microsoft.Resources/deployments",
			"apiVersion": "2021-04-01",
			"properties": {
        "mode": "Incremental",
				"expressionEvaluationOptions": {
					"scope": "Inner"
				},
				"template": {
					"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
					"contentVersion": "1.0.0.0",
          "resources": [ ],
					"outputs": {
            "testOutput": {
              "type": "string",
              "value": "bob"
            }
          }
				}
			}
		}
	]
}

Will trigger the Template should not contain blank issue.  Changing the scope to outer means the template will pass with no issues

Similar to #437

**Comment by bmoore-msft** [comment]
should be fixed in #474
