### ISSUE TITLE
Resources Should Not Be Ambiguous - Unclear error

### ISSUE THREAD

**Issue by danielecazzari** [Azure/arm-ttk#477]
Hi,

after a recent test update, I'm receiving a lot of "Resources Should Not Be Ambiguous" errors.
Many of the below-used syntaxes come from examples so I'm not really sure what it's wrong.

Those errors could be reproduced with the template shared previously.

Thanks 

Daniele

    [-] Resources Should Not Be Ambiguous (436 ms)                                                                              At least one parameter must preceed the resource type in:                                                       resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', variables('identityName')) Line: 245, Column: 15                 At least one parameter must preceed the resource type in:                                                       resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', variables('identityName')) Line: 264, Column: 23                 At least one parameter must preceed the resource type in:                                                       resourceId('Microsoft.Authorization/roleAssignments', variables('roleDefinitionName')) Line: 277, Column: 20                    At least one parameter must preceed the resource type in:                                                       resourceId('Microsoft.ContainerRegistry/registries',parameters('registryName')) Line: 337, Column: 107                          At least one parameter must preceed the resource type in: resourceId('Microsoft.ContainerRegistry/registries',  parameters('registryName')) Line: 339, Column: 111                                                                              At least one parameter must preceed the resource type in: resourceId('Microsoft.ContainerRegistry/registries',  parameters('registryName')) Line: 345, Column: 15                                                                               At least one parameter must preceed the resource type in: resourceId('Microsoft.Resources/deploymentScripts',   variables('preUpdatScriptName')) Line: 346, Column: 15                                                                          At least one parameter must preceed the resource type in: resourceId('Microsoft.Resources/deploymentScripts',   variables('AKSPatchVerScriptName')) Line: 387, Column: 15                                                                       At least one parameter must preceed the resource type in:                                                       resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', variables('identityName')) Line: 453, Column: 73                 At least one parameter must preceed the resource type in:                                                       resourceId('Microsoft.ContainerRegistry/registries',parameters('registryName')) Line: 459, Column: 722                          At least one parameter must preceed the resource type in: resourceId('Microsoft.ContainerRegistry/registries',  parameters('registryName')) Line: 459, Column: 1115                                                                             At least one parameter must preceed the resource type in: resourceId('Microsoft.Resources/deployments',         'eventHubTemplate') Line: 469, Column: 15                                                                                       At least one parameter must preceed the resource type in: resourceId('Microsoft.Resources/deployments',         'AKSTemplate') Line: 470, Column: 15                                                                                            At least one parameter must preceed the resource type in: resourceId('Microsoft.Resources/deployments',         'vmTemplate') Line: 471, Column: 15                                                                                             At least one parameter must preceed the resource type in: resourceId('Microsoft.Resources/deployments',         'postgreSQLTemplate') Line: 472, Column: 15                                                                                     At least one parameter must preceed the resource type in:                                                       resourceId('Microsoft.Authorization/roleAssignments', variables('roleDefinitionName')) Line: 473, Column: 15                    At least one parameter must preceed the resource type in: resourceId('Microsoft.Resources/deploymentScripts',   variables('preUpdatScriptName')) Line: 475, Column: 15

**Comment by bmoore-msft** [comment]
@danielecazzari - are you seeing anything different than in #478?  if not, I'll close this one and track there...

**Comment by danielecazzari** [comment]
I'm not sure if I saw there the case that test fails when you are using a variable inside resourceId like this:
   resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', variables('identityName')) 
Could you confirm that also this will be covered?
Thanks

**Comment by bmoore-msft** [comment]
it could have been - just that it depends on where that's found (e.g. in a nested deployment)... nested deployments is where I was seeing most of the unexpected errors.  So yes, we need to cover that scenario before lighting it up again.

Will close this for now, feel free to reopen if you think we're missing something...
