### ISSUE TITLE
Resources Should Not Be Ambiguous - Clarification

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#478]
The template at - https://raw.githubusercontent.com/drewkg/Azure/main/ARM/Resource/AppServiceWithMSIAppInsights/azureDeploy.json

Will trigger a Resource Should Not Be Ambiguous test, this is due to the resourceid function within the nested template, but at the same scope of the containing template e.g. resource group.  I am presuming this is triggered because the resource is not deployed within the same template (nested, it is deployed in the outer template) and thus cannot be found.

Should we.

1. Pass the resource id into the nested template via a parameter
2. or add the recourse group name to the resourceid function call, this seems against the documentation.

**Comment by bmoore-msft** [comment]
The spirit of the test is that you should have a resourceGroup name parameter in the resourceId function.  Because the resource is not defined in the template that contains the resourceId() call, it could be interpreted as an "existing" resource, which could be in another resourceGroup.  Adding the param ensures each scenario is covered.  So you would pass in a RG name for that resourceId.

However, I think in your case it's a little more nuanced - you're deploying everything to the same RG, that's just not immediately obvious between the nested deployments.

In your "fix" either #1 or #2 would be correct - but in the case of an outer scoped deployment I think the same error would be thrown and the fix seems more unnecessary there.  We may have to roll this one back and think through it some more.

Aside - where are you seeing your #2 contrary to docs?

**Comment by drewkg** [comment]
quote from - https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-

Parameter - resourceGroupName
"Default value is current resource group. Specify this value when you need to retrieve a resource in another resource group. Only provide this value when deploying at the scope of a resource group."

As I am using a nested template, with inner scope, to get around another ARM limitation but all within the same resource group I read this as not requiring the extra parameter of a resource group.

To be fair, this is probably an extreme edge case as its to do with creating App Insight Dashboards within ARM .  The only reason for the nested template is so we can use the reference function to retrieve values to specify the dashboard name, which you can only use within certain areas of an ARM template.

Thinking about this though, in an incremental deployment, this issue could trigger within a single template with no nesting.

**Comment by pavelsalamon** [comment]
Unless I'm missing someting, any template that combines **dependsOn** and conditional deployment (like standard 'newOrExisting' pattern) will be flagged by this test. Example is https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/quickstarts/microsoft.compute/vm-new-or-existing-conditions/azuredeploy.json

We use the same patterns in our templates. Usage of resourceId() function inside **dependsOn** seems to cause the issue. When resource depends on a conditionally deployed resource, it's flagged by this test.

**Comment by jarradbrown** [comment]
Any suggestions how to update dependsOn code with resource IDs of resources that are not deployed in the template? We are using the same resourceid() function

**Comment by pavelsalamon** [comment]
For conditionally deployed resources, workaround we use for now is a variable:
```"thisResourceGroupName": "[resourceGroup().name]"```

If you use this variable as first parameter in problematic dependsOn[...resourceId()...] places, it tricks the test into passing.
I hope this gets rolled back or fixed so we can get rid of this hacky solution.

**Comment by bmoore-msft** [comment]
yes - don't work around this I'm going to pull the test for now... there are a bunch of cases we didn't think through (going to start to list them here:

- dependsOn for conditional resources (dependsOn never needs the add'l param)
- outer scope deployments that do not change scope (scope property, rg property or sub property)
- add more as we find 'em

**Comment by drewkg** [comment]
Please Add, Inner scope templates that deploy to the same resource group.

**Comment by bmoore-msft** [comment]
I've updated https://aka.ms/arm-ttk-latest with #480 to remove the test for now...  lmk if you're still seeing issues.
