### ISSUE TITLE
apiVersions Should Be Recent In Reference Functions - diagnosticSettings

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#479]
This might be an impact of teh warnings if the API version does not exist in the cache, as it was not reporting anything previously.

But when creating a policy for deploying diagnostic settings we are using the following :-

"type": "Microsoft.Automation/automationAccounts/providers/diagnosticSettings",
"apiVersion": "2017-05-01-preview",

in the nested template, no matter the value we use here we are always getting :-

[+] apiVersions Should Be Recent In Reference Functions 14ms
WARNING: The apiVersion 2016-09-01 was not found for the resource type: Microsoft.Insights

Looking at the cache I presume we should be using on of :-

  "microsoft.insights/diagnosticSettings": [
    {
      "aliases": null,
      "apiProfiles": [
        {
          "apiVersion": "2016-09-01",
          "profileVersion": "2018-06-01-profile"
        }
      ],
      "apiVersions": [
        "2021-05-01-preview",
        "2017-05-01-preview",
        "2016-09-01",
        "2015-07-01"
      ],

A full example of a template that triggers the issue can be found at https://raw.githubusercontent.com/drewkg/Azure/main/ARM/Policy/DiagnosticSettings/LogAnalytics/diagnostics-aa-deploy-policy.json

**Comment by drewkg** [comment]
@bmoore-msft thinking about this one, and working with Bicep, I am now questioning if this is the right bug?

My reasoning, in Bicep all extension resources are deployed as a resource in its own right, with a scope.  So for diagnosticsSettings we would deploy the equivalent of -

      "type": "Microsoft.Insights/diagnosticSettings",
      "apiVersion": "2017-05-01-preview",

instead of a child resource.  So while the bug report is correct for ARM, is not the true issue here that we should not be deploying extension resources as a child resource?

**Comment by bmoore-msft** [comment]
extension and child resources are different things even though they are authored similiarly.  An extension resource will always have ```/providers/``` in the type and a namespace in the name.  Children share the same namespace with the parent.

The authoring pattern using ```/providers/``` was the only way to author extension resources prior to introducing the scope property (which works in bicep and json).  So one potential "fix" here is to author extension resources with the scope property (in json, in bicep that's the only way to do it) and then the complexity here becomes throw away.

Sooooo.... we could "fix" this as you suggest, just by not supporting the obsolete authoring pattern... which tbh I kinda like, even though it's a little more disruptive as a fix.

Let's see if others chime in...

**Comment by drewkg** [comment]
I have just moved a load of policy templates, in ARM and BICEP to the new scope pattern and it makes a lot more sense in my mind, people could always disable the new rule for legacy templates until they migrate.

This is on the assumption that ARM-TTK is promoting best practice :)  But as you said lets see if anyone else has strong opinions.

**Comment by bmoore-msft** [comment]
s/b fixed in 559
