### ISSUE TITLE
do we need an -isQuickStart switch (staging and other practices)

### ISSUE THREAD

**Issue by marrobi** [Azure/arm-ttk#48]
I'm using ARM-TTK to validate templates outside of the quickstart repository. Firstly please confirm that this is a valid use case?

Linked templates are staged prior to deployment to a storage account.

This means the default values specified here: https://github.com/Azure/arm-ttk/blob/5c3127d66cbd58c81bc7f43c8a2b083e83ec3357/arm-ttk/testcases/deploymentTemplate/artifacts-parameter.test.ps1#L43 are not appropriate. 

The staging location needs to be specified at deploy time. 

Of the two, a GitHub URL is not appropriate, and if I use `[deployment().properties.templateLink.uri]` the templates are not deployable for obvious reasons.

Is this a case of needing  an `isQuickstart` switch or similar?

Thanks.

**Comment by StartAutomating** [comment]
@bmoore-msft  : I don't think it would be a good idea to get into the game of special casing tests to a given repo.  It would be better to look at #329 and making quickstart integrate quickstart specific tests this way.
