### ISSUE TITLE
[?] apiVersions Should Be Recent - The apiVersion 2019-06-01 was not found for the resource type:  Microsoft.Storage/storageAccounts/blobServices/containers

### ISSUE THREAD

**Issue by ccvaillant1992** [Azure/arm-ttk#482]
When I execute the tests of my arm template, I'm getting this as a result 
 
![image](https://user-images.githubusercontent.com/56896573/127525800-e7005c67-a19c-4e76-835a-88cde3658fec.png)

If I go to this **_/arm-ttk-master/arm-ttk/arm-ttk/cache_** directory in my local from the clone of the arm-ttk repository
in this file AllAzureResources.cache.json, the type **_"Microsoft.Storage/storageAccounts/blobServices/containers_**" does not exists

**Comment by bmoore-msft** [comment]
I think this is by design... if we don't find the apiVersion (i.e. not returned by the /providers api) then we throw a warning.  This will be benign in the case where something is simply undocumented but an error in the case if the code is actually wrong.

LMK if that doesn't sound right...
