### ISSUE TITLE
defaultValue of resourceGroup().location should be a warning in nested templates

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#490]
in json a nested template generally wants to ensure that the location property is passed from the parent deployment through...

in a module world (e.g. bicep) having that default value makes module usage simpler by not requiring the value - though it also increases the change of failure.  these two "rules" conflict.

We could
- turn the nested defaultValue case into a warning
- flip the logic to see if the parameter is passed through (in a bicep file it's all one template)
- skip it for nested (which essentially regress the test/scenario entirely)

Other ideas?

**Comment by spoelly** [comment]
please make this a warning.
