### ISSUE TITLE
CreateUiDefinition - NestedTemplates - Outputs Must Be Present In Template Parameters - Requires un-needed parameters

### ISSUE THREAD

**Issue by stephenpope** [Azure/arm-ttk#492]
*As there are a few files involved i have created a Gist to help out -> https://gist.github.com/stephenpope/790a88595efa698e70cd73c31e476084*

## Setup 

I have a simple bicep structure a `main` file with two `modules` (that create nested templates) .. 

```
main.bicep
  another.bicep
  yetanother.bicep
```

these can be built into a `azuredeploy.json` with `bicep build main.bicep --output azuredeploy.json`

There is also `createUiDefinition.json` .. this has two textboxes which have `outputs` defined as `oneParameter` + `twoParameter` to match the input `params` of the `azuredeploy` script.

## Error

The script shows errors even though `oneParameter` and `twoParameter` are defined in the `main.bicep` file (and appear in the main `parameters` section in the `json`).

```bicep
//filename: main.bicep
param oneParameter string = 'defaultValue'
param twoParameter string = 'anotherValue'
//<snip>
```

```
NestedTemplate my-thing my-thing my-other-thing my-other-thing [ Lines 44 - 74 ]
  [-] Outputs Must Be Present In Template Parameters (21 ms)
      output oneParameter does not exist in template.parameters
      output twoParameter does not exist in template.parameters
      output oneParameter does not exist in template.parameters
      output twoParameter does not exist in template.parameters
```

## Discussion

These parameters are not defined in the nested modules because they are *not needed*. The nested modules have their own parameters.

This seems like an error in working out the constraints (unless I am mistaken :)

**Comment by StartAutomating** [comment]
It looks like the current PR #535 touches on the same case.

If a test has parameters that indicate it was a maintemplateobject, those parameters should be cleared.  If any of them were required, the test should be skipped (quietly).

e.g. if there was a test requring MainTemplateObject, it should not run when evaulating inner templates of the mainTemplateObject.

Skipping of tests can be indicated with Write-Verbose, but would be too noisy otherwise.

**Comment by StartAutomating** [comment]
We should back out some of the changes to $TemplateObject if #535 is merged, once a fix for this bug is available.

**Comment by stephenpope** [comment]
I have noticed with the latest version (2021.11.05) it thinks secure `param` values are required in nestedTemplates. So if I have a nested template (module in bicep) with..

```bicep
@secure()
@description('Specifies the SSH RSA public key string for the Linux nodes.')
param aksClusterSshPublicKey string
```
.. results in ..
```
NestedTemplate ...
    [-] Parameters Without Default Must Exist In CreateUIDefinition (80 ms)                                                 
        aksClusterSshPublicKey does not have a default value, and is not defined in CreateUIDefinition.outuputs  
```
.. but obviously putting a default value in a secure valueis not allowed.

It should probably skip this check like it does in other parts.

I can raise a separete bug for this if you think its necessary. Thanks for all your work with this :)

**Comment by bmoore-msft** [comment]
@stephenpope - can you go ahead and open a new bug for your new case?
