### ISSUE TITLE
API Versions must be the latest of under 2 years old - geoBackupPolicies

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#505]
When adding geoBackupPolicies as a child resource to a database there appears to be no possible way to satisfy the Api Version must be latest rule.

Using the last none preview version of the last preview version the rule gets triggered

Api versions must be the latest or under 2 years old (730 days) - API version 2014-04-01 of Microsoft.Sql/servers/Microsoft.Sql/servers/databases/Microsoft.Sql/servers/databases/geoBackupPolicies is 2708 days old 

Api versions must be the latest or under 2 years old (730 days) - API version 2015-05-01-preview of Microsoft.Sql/servers/Microsoft.Sql/servers/databases/Microsoft.Sql/servers/databases/geoBackupPolicies is 2313 days old 

Cache Extract 

"Microsoft.Sql/servers/databases/geoBackupPolicies": [
    {
      "aliases": null,
      "apiProfiles": null,
      "apiVersions": [
        "2015-05-01-preview",
        "2014-04-01-preview",
        "2014-04-01"
      ],

ARM Snippet

"resources": [
  {
    "type": "Microsoft.Sql/servers/databases/geoBackupPolicies",
    "apiVersion": "2014-04-01",
    "name": "[concat(variables('sqlServerName'), '/keithdrew.net/Default')]",
    "location": "[parameters('resourceLocation')]",
    "dependsOn": [
      "[resourceId('Microsoft.Sql/servers/databases', variables('sqlServerName'), 'keithdrew.net')]"
    ],
    "properties": {
      "state": "Enabled"
    }
  }
]

**Comment by bmoore-msft** [comment]
We had a recent change that made this slightly better - you can now use the 2014 version, but it will still complain if you need the latest preview (which is more than 2 years old).

The rule here should be (I think we can simplify):

- create 2 lists of valid apiVersions that are less than 2 years old (preview and non-preview).  
- If there are none in any list that are less than 2 years old, then take the latest one from each list
- I am allowed to use the latest from either list, unless I'm choosing the latest from the preview list and there exists a later non-preview version

If we take this refactor, we should update apiVersion and reference/list apiVersion test

**Comment by drewkg** [comment]
@bmoore-msft 

Just to play devils advocate here, many places frown upon using preview API versions and discourage the use.  Would it be possible to have the rule say

Use latest non preview version, even if it over 2 years old if no later non preview versions exist
If using a preview version and there is a later non preview version then should use the non preview version

**Comment by bmoore-msft** [comment]
We'd have to introduce a flag for it... sometimes preview versions are required for certain functionality - and RPs are not the best at "printing" non preview versions (SQL being one of the worst offenders as you can see).

I think it's pretty easy to do in the FW, just would have to be non-default due to the breaking change.

@StartAutomating
