### ISSUE TITLE
"Location Should Not Be Hardcoded" test catching errors in good templates

### ISSUE THREAD

**Issue by palchak** [Azure/arm-ttk#508]
I am running ARM TTK and one of the tests that i am using is : Location Should Not Be Hardcoded which is mentioned in the link : [https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-test-cases](url).

My template file name is  "winvm-arm.json"

Location is defined in parameters like below :

```
"location": {
      "type": "string",
      "defaultValue": "[resourceGroup().location]",
      "metadata": {
        "description": "Location for all resources."
      }
```

 I also have the reference to this parameter in my resource block like shown below :

```
resources": [
    {
      "apiVersion": "2020-05-01",
      "type": "Microsoft.Network/networkInterfaces",
      "name": "[concat(variables('vmName'), '-nic')]",
      "location": "[parameters('location')]",
      "properties": {
        "ipConfigurations": [
          {
            "name": "ipconfig1",
            "properties": {
              "privateIPAllocationMethod": "Dynamic",
              "subnet": {
                "id": "[variables('subnetRef')]"
              }
            }
          }
        ]
      }
    },  
```

The error i get is : 

```
-] Location Should Not Be Hardcoded (12 ms) 
        The location parameter of nested templates must not have a defaultValue property. It is "[resourceGroup().location]" 

```
If i rename my template from "winvm-arm.json" to "mainTemplate.json" i don't get the error anymore. So is there anyway or is it mandatory to put all the template names to either "mainTemplate.json" or "azuredeploy.json"  as i have multiple templates in a particular folder with their own names
If i don't name my template by those two names, the test is thinking that my winvm-arm.json file is a linked template which it is not actually and highlighting the error which i mentioned

The command that i am running is : 
`get-childitem -Recurse "C:\Pallab\ARM Templates\*.json" | Test-AzTemplate `

I also tried this command : 

`get-childitem -Recurse "C:\Pallab\ARM Templates" *.json | Test-AzTemplate`  which is according to Sam Cogan's article : 

[https://samcogan.com/azure-resource-manager-template-tool-kit/](url)

Still the same results.

This is added as one of the tasks in my Azure Devops Pipeline and we are using Azure Repos where a branch policy is configured that before a PR is merged, ARM TTK pipeline will run and do a unit test validation of all the *.JSON file/files.
So right now i have many JSON files in "ARM Templates" folder and i don't have any file by the name of azuredeploy.json or mainTemplate.json. 
Different people write ARM templates, put their own names and push them to the main branch in Azure Repos

**Comment by bmoore-msft** [comment]
this is because anything that is not the "main template" is assumed to be a nested template... main template is determined by the filename (unless you specify otherwise).

I think short term you'll have to follow the pattern - until we have a more standard way of determining name / nested.

NOTE: to check for duplicate on this issue of "better way to determine nested templates"
