### ISSUE TITLE
Latest NON preview resource Azure Keyvault older then 730 days

### ISSUE THREAD

**Issue by RichioProg** [Azure/arm-ttk#510]
Since a couple of days the `apiVersions Should Be Recent In Reference Functions` script reports the error that the used KeyVault API version is older then the minimum required age. The latest KeyVault API version is: 2019-09-01, according to Microsofts docs: [Link to Microsofts API Keyvault Docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/allversions)

However, there are some more recent API versions which can be used, but they are all preview versions. Currently I am forced to use these Keyvault preview version, otherwise our pipeline will fail. I am not a very experienced ARM user and I was just wondering how other users deal with this situation. 

I can see that we could exclude this test (apiVersions-Should-Be-Recent.test.ps1). But it will be applied to all resources used in the template. As far as I can see it is not possible to exclude only one (keyvault resource) from that specific test? 

The conclusion so far is that I am forced to use the preview resource API which is not really a problem because everything works fine, but I am always a bit hesitant to use preview versions. Soo what should you recommend? Modify the test script, just use the preview resource API or is there something else?

**Comment by jlevine-aba** [comment]
I ran into this too - working on a fix and will open a PR soon.

**Comment by jakelevinez** [comment]
@bmoore-msft I didn't quite do what the #505 algo says - but I did find a way to ensure the latest stable API is always acceptable in  PR  #516 which seems to be most of the source of the problems people run into.

I can look into something more along the lines of the algo - not sure about how to dedup that code across the normal test and reference test but I can try and dig into that this weekend.

**Comment by bmoore-msft** [comment]
Sounds like the original issue (in this issue) is resolved/merged...  I'll close this one out and if you get a chance on the other PR we can pick up discussion there...
