### ISSUE TITLE
Neither of the versions available for Microsoft.Synapse/workspaces/kusoPools/databases/dataConnections is recognized

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/arm-ttk#530]
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Synapse/workspaces/kustoPools/databases/dataConnections",
      "apiVersion": "2021-06-01-preview",
      "name": "a/a/a/a",
      "kind": "EventGrid"
    }
  ]
} 
```
2021-06-01-preview and 2021-04-01 both give:
```sh
 [?] apiVersions Should Be Recent (73 ms)
The apiVersion 2021-06-01-preview was not found for the resource type: Microsoft.Synapse/workspaces/kustoPools/databases/dataConnections         
```
Bicep shows:
![image](https://user-images.githubusercontent.com/6913354/137793516-db237b28-774d-4384-a4f2-3e597c11193a.png)

**Comment by bmoore-msft** [comment]
Same as #531 - if we're seeing types then the problem is the manifest in ARM...

Perhaps a longer discussion about whether the manifest should be the source of truth, but the /providers api is public so seems like that should work as well?

**Comment by StartAutomating** [comment]
Probably handled by improvements to api version validation.  Re-open if this is still broken.
