### ISSUE TITLE
Resource type parsing for modules is incorrect

### ISSUE THREAD

**Issue by jakelevinez** [Azure/arm-ttk#532]
I have a module containing a keyvault, using API version 2019-09-01 (latest stable).

The api versions must be recent test fails with the following:

` Api versions must be the latest or under 2 years old (730 days) - API version 2019-09-01 of
Microsoft.Resources/deployments/Microsoft.KeyVault/vaults/secrets is 779 days old
        Valid Api Versions:
        2021-01-01
        2021-01-01
        2020-10-01
        2020-06-01`

It appears to be using Microsoft.Resources/deployments as the resource type when checking the API version - the list it gives for valid api versions is correct for Microsoft.Resources/deployments but not for vaults/secrets.

**Comment by bmoore-msft** [comment]
@jakelevinez - can you attach a template to repro?

**Comment by StartAutomating** [comment]
This looks like it has some regression potential and I'd like to take a look sooner rather than later.

**Comment by jakelevinez** [comment]
@bmoore-msft this is where I have seen it - worth noting the keyvault itself is a bicep module but for the sake of simplicity here is a simplified version of the final ARM after transpilation which should repro.

`{
  "$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "metadata": {
    "_generator": {
      "name": "bicep",
      "version": "0.4.1008.15138",
      "templateHash": "3553005352917001265"
    }
  },
  "parameters": {
    "environment": {
      "type": "string",
      "allowedValues": [
        "prod",
        "dr"
      ]
    },
    "location": {
      "type": "string",
      "defaultValue": "[deployment().location]"
    },
    "rg": {
      "type": "string"
    }
  },
  "functions": [],
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Resources/resourceGroups",
      "apiVersion": "2021-01-01",
      "name": "[parameters('rg')]",
      "location": "[parameters('location')]"
    },    
    {
      "condition": "[equals(parameters('environment'), 'prod')]",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2020-06-01",
      "name": "supKeyvault",
      "resourceGroup": "[parameters('rg')]",
      "properties": {
        "expressionEvaluationOptions": {
          "scope": "inner"
        },
        "mode": "Incremental",
        "parameters": {
          "location": {
            "value": "[parameters('location')]"
          }
        },
        "template": {
          "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
          "contentVersion": "1.0.0.0",
          "metadata": {
            "_generator": {
              "name": "bicep",
              "version": "0.4.1008.15138",
              "templateHash": "14232794883062858383"
            }
          },
          "parameters": {
            "location": {
              "type": "string"
            }
          },
          "functions": [],
          "variables": {
            "kv_name_var": "[format('kv-sup-{0}', substring(uniqueString(subscription().id), 0, 4))]"
          },
          "resources": [
            {
              "type": "Microsoft.KeyVault/vaults",
              "apiVersion": "2019-09-01",
              "name": "[variables('kv_name_var')]",
              "location": "[parameters('location')]",
              "properties": {
                "sku": {
                  "family": "A",
                  "name": "standard"
                },
                "tenantId": "[subscription().tenantId]",
                "enabledForDeployment": true,
                "enabledForDiskEncryption": true,
                "enabledForTemplateDeployment": true,
                "enableSoftDelete": true,
                "accessPolicies": []
              }
            }
          ]
        }
      },
      "dependsOn": [
        "[subscriptionResourceId('Microsoft.Resources/resourceGroups', parameters('rg'))]"
      ]
    }
  ]
}`

**Comment by jakelevinez** [comment]
Latest version does not repro anymore.

**Comment by bmoore-msft** [comment]
Cool - thanks for confirming...
