### ISSUE TITLE
CreateUiDefinition - Nested Templates - Secure parameters are marked as required

### ISSUE THREAD

**Issue by stephenpope** [Azure/arm-ttk#542]
I have noticed with the latest version (2021.11.05) the script thinks secure `param` values are required in nestedTemplates. 

So if I have a nested template (module in bicep) called from `main.bicep` ..

```
main.bicep
	mycoolmodule.bicep
```

In `mycoolmodule.bicep` ..

```bicep
@secure()
@description('Specifies the SSH RSA public key string for the Linux nodes.')
param aksClusterSshPublicKey string
```
.. results in ..
```

NestedTemplate ...
    [-] Parameters Without Default Must Exist In CreateUIDefinition (80 ms)                                                 
        aksClusterSshPublicKey does not have a default value, and is not defined in CreateUIDefinition.outuputs  
```
.. but obviously putting a default value in a secure value is not allowed.

Side-note: This is a bug but for my specific use-case I dont want *any* nestedTemplate parameters to have to have default values when not in createUiDefintion - they should only validate against at the top-level template only. I am trying to use sub-modules as a re-usable library that could be called from multiple top-level scripts that need different combinations of features. Slightly off-topic but just wanted to give the context just-in-case :)

**Comment by bmoore-msft** [comment]
re: the sideNote just want to make sure I understand...  when you have a bicep module (that turns into a nested deployment in the json) you don't want *any* defaultValues in that scenario?
