### ISSUE TITLE
Feature request: Template expression checks

### ISSUE THREAD

**Issue by locatelucas** [Azure/arm-ttk#546]
I find the place where I'm most likely to start at the template to determine if it is correct are in the template expressions.  It would be helpful to have some checks on template expressions.  Perhaps:
- Template expressions are well formed
- Template expressions use only defined functions 
- Template expressions have the correct return type
- ```resourceGroup```, ```resourceId```, and ```subscription``` are only used at the appropriate scope
- Template functions receive all required arguments & the arguments are of the right type

**Comment by bmoore-msft** [comment]
@locatelucas - we had talked about this in the "early days" and the main reason why we didn't do this is because the dev tooling (i.e. VS Code) does this well... and we didn't want to spend the effort to duplicate.  Bicep is doing this as well - so that's the rationale.

Thoughts?

**Comment by StartAutomating** [comment]
Closing due to complexity levels and lack of response.
