### ISSUE TITLE
The "Parameters Must Be Referenced" test throws an error working with big nested templates

### ISSUE THREAD

**Issue by baldcorp** [Azure/arm-ttk#563]
We have faced the issue with this test works with big nested template. It is always one unreferenced parameter at the end, however the parameter is properly referenced.

[sqlaon.zip](https://github.com/Azure/arm-ttk/files/7854740/sqlaon.zip)

Steps to reproduce: 
1) Extract files from the attached archive
2) Run Test-AzTemplate -TemplatePath "your-path-to-the-extracted-files\\**sqlaon.json**" -Test deploymentTemplate -ErrorAction Continue
3) Observe the error: 
               NestedTemplate Deploy_WitnessStorageAccount [ Lines 99 - 100 ]
                  [-] Parameters Must Be Referenced (272 ms)
                      Unreferenced parameter: storName
                deploymentTemplate

In order to prove that the "storName" parameter is referenced properly, run short version of arm template 
4)  Run Test-AzTemplate -TemplatePath "your-path-to-the-extracted-files\\**sqlaon-short.json**" -Test deploymentTemplate -ErrorAction Continue 
5) Pay attention to the absence of errors.

**Comment by baldcorp** [comment]
[CH1-ARMTemplateExport-Dev-short.zip](https://github.com/Azure/arm-ttk/files/7856307/CH1-ARMTemplateExport-Dev-short.zip)

The same issue happens with Azure policy definition if we have more than two policies with deployIfNotExist effect and described resources in one file. Please find the example file in the attachment.

The issue can be reproduced the same way as for **sqlaon.json** file.

**Comment by bmoore-msft** [comment]
@baldcorp thanks for the 2 repro, there are 2 different issues here...

@StartAutomating 

With sqloan.json, we don't seem to be handling the expressionEvaluationOptions correctly.  This uses inner scope but if I change it to outer scope then we find the parameter.  So we actually have the logic backwards (at least for inner scope).

With CH1-ARMTemplateExport-Dev-short.json - there's actually a template in this that isn't using the param.  The policyDefinition with the name: 4D3CF186A40A7C2C481B645A540C1C7C does not use the logsEnabled parameter.  The other 2 policyDefs do use it - however when that third def does not use it, we report the error 3 times in the output.  We may want to open a separate bug for this one (will let you decide).

**Comment by baldcorp** [comment]
Thank you for investigation. I do not mind to open separate bug for issue with the policy. Origin policy definition file contains more than 20 policies. If you would like to check origin file, please let me know.

**Comment by bmoore-msft** [comment]
Yeah, if you can open a separate bug that would be helpful...

re: the repro, I think we have what we need for this one, I was able to repro

**Comment by bmoore-msft** [comment]
Should be fixed in 2022.03.04 by #589
