### ISSUE TITLE
2022.01.18 - Variables must be referenced errors

### ISSUE THREAD

**Issue by stephenpope** [Azure/arm-ttk#567]
Lots (lots) of these unreferenced variable errors when the variables are clearly referenced.

One example : Nested template (bicep module) ..

```bicep
var contributorRoleDefinitionName = 'b24988ac-6180-42a0-ab88-20f7382dd24c'
var contributorRoleId = '/subscriptions/${subscription().subscriptionId}/providers/Microsoft.Authorization/roleDefinitions/${contributorRoleDefinitionName}'

resource id_identityName_roleDefinitionOwner 'Microsoft.Authorization/roleAssignments@2020-04-01-preview' = {

  name: guid(resourceGroup().id, identityName, contributorRoleId)
  properties: {
    roleDefinitionId: contributorRoleId
    principalId: user_identity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
```

.. results in ..

```
 NestedTemplate identity-creation [ Lines 516 - 1318 ]
    [-] Variables Must Be Referenced (77 ms) 
        Unreferenced variable: contributorRoleDefinitionName
        Unreferenced variable: contributorRoleId
        .....
```

**Comment by bmoore-msft** [comment]
@stephenpope do you have a more complete repro we can try - I tried something and wasn't able to repro.

@StartAutomating - I think this may be related #563 and the inner scope eval.

**Comment by ReneRebsdorf** [comment]
@bmoore-msft Here's a file which repro - is it perhaps related to only using a variable in the deployment name?

[azureDeploy.zip](https://github.com/Azure/arm-ttk/files/8110628/azureDeploy.zip)
s

**Comment by bmoore-msft** [comment]
Got it - thanks...  yes I think related to the regressing we had in innerScope nested templates.

**Comment by bmoore-msft** [comment]
s/b be fixed in the latest release
