### ISSUE TITLE
2022.01.18 - 'URIs Should Be Properly Constructed' issue

### ISSUE THREAD

**Issue by KakuBB** [Azure/arm-ttk#569]
With the latest release (2022.01.18) properly constructed URIs are failing on the URI check with following error:

[-] URIs Should Be Properly Constructed (11 ms)
        Cannot index into a null array.

An example template that should pass, but it fails:

`
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "uriParam": {
            "type": "string",
            "defaultValue": "[deployment().properties.templateLink.uri]"
        }
    },
    "functions": [],
    "variables": {
        "varUri": "[uri(parameters('uriParam'), 'Configuration.zip')]"
    },
    "resources": [],
    "outputs": {
        "output1": {
            "type": "string",
            "value": "[variables('varUri')]"
        }
    }
}
`

**Comment by bmoore-msft** [comment]
Think we got it in #573
