### ISSUE TITLE
2022.01.18 - 'URIs Should Be Properly Constructed' issue when using reference

### ISSUE THREAD

**Issue by atyourservers** [Azure/arm-ttk#570]
With release 2022.01.18, properly constructed URIs are failing the URI validation when you use a reference function instead of a concat. The following URIs should pass I believe:

`"[uri(reference(resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName')), '2021-04-01').primaryEndpoints.blob, 'vulnerability-assessment')]"`
`"[uri(reference(resourceId('Microsoft.KeyVault/vaults/keys', parameters('keyVaultName'), parameters('keyName')), '2021-06-01-preview').keyUri, parameters('keyVersion'))]"`

**Comment by bmoore-msft** [comment]
Thanks - this looks to be the same as 569, the extra repro is handy... So we'll track with #569
