### ISSUE TITLE
Provide a 'latest' GitHub release

### ISSUE THREAD

**Issue by ReneRebsdorf** [Azure/arm-ttk#586]
Given the staleness of [issue 448](https://github.com/Azure/arm-ttk/issues/448) and [issue 182](https://github.com/Azure/arm-ttk/issues/182)

Could we get a tag of 'latest' to the [github releases](https://github.com/Azure/arm-ttk/releases)?

This way we can opt to download specific releases, or just to get the latest maintained one?
This release could also by linked to from [this ms docs article](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/test-toolkit)

This way it won't be needed to update whichever zip file that article refers to, and we can get transparency on the content of that release, for any given date (as it would match the newst versioned release at the time?

Ideally I would rather have a PSGallery solution, but I believe this would be a decent alternative solution.

**Comment by bmoore-msft** [comment]
Ok, try this - if we name the zip consistently (instead of by date/tag) the built-in ```latest``` tag should work?

https://github.com/Azure/arm-ttk/releases/latest/download/arm-ttk.zip

**Comment by ReneRebsdorf** [comment]
Beautiful.
Will start using this link instead of https://aka.ms/arm-ttk-latest as the github release link provides better insight into which release we are using at the point of download.

Thank you.

**Comment by bmoore-msft** [comment]
np - good catch... now we just have to remember to name the binary that way consistently ;)
