### ISSUE TITLE
Arm-ttk validation is failing in arm templates if I use hide confirmation = true for passwordbox control

### ISSUE THREAD

**Issue by Tichandr** [Azure/arm-ttk#594]
Hello Arm-ttk,

For passwordbox control type if I use "hideConfirmation": true in the options object in the passwordbox schema arm-ttk arm template validation is getting failed.

Sample Schema:-

{
  "name": "element1",
  "type": "Microsoft.Common.PasswordBox",
  "label": {
    "password": "Password",
    "confirmPassword": "Confirm password"
  },
  "toolTip": "",
  "constraints": {
    "required": true,
    "regex": "^[a-zA-Z0-9]{8,}$",
    "validationMessage": "Password must be at least 8 characters long, contain only numbers and letters"
  },
  "options": {
    **"hideConfirmation": true**
  },
  "visible": true
}

Please take a look at this issue and provide me the resolution or fix for this issue.

Thanks,
Sarath

**Comment by bmoore-msft** [comment]
@Tichandr - this is intentional, that's what the test checks for...  You can skip the test if it's not appropriate for your scenario...

**Comment by bmoore-msft** [comment]
going to close this feel free to reopen as needed
