### ISSUE TITLE
Error on large template files

### ISSUE THREAD

**Issue by RenePingen** [Azure/arm-ttk#60]
Hi,

I have found an issue with Import-Json that errors out in case of large template files (tested with >300KB). (In case you are wondering, i am trying to run the tests on exported templates, not writing large templates :) )

Splitting up
```powershell
[IO.File]::ReadAllText("$resolvedPath") | 
            ConvertFrom-Json -ErrorAction SilentlyContinue -ErrorVariable ConvertProblems
```
Into
```powershell
$content=[IO.File]::ReadAllText("$resolvedPath");
        ConvertFrom-Json -ErrorAction SilentlyContinue -ErrorVariable ConvertProblems -InputObject $content
```
seems to fix it, although I am not sure what the limit of this new approach is. Probably some powershell limitations..

**Comment by bmoore-msft** [comment]
What version of PS are you using?

**Comment by bmoore-msft** [comment]
@RenePingen - can you check your PS version, also if you have a sample template that repros would be helpful (if you're still seeing this)

**Comment by RenePingen** [comment]
Hi Brian,

Sorry for the late response, my version is 5.1. Ill try upgrading later and retry the analysis.

Regarding the sample repo, unfortunately it is a client repository, so im not able to share it.

René

**Comment by bmoore-msft** [comment]
@RenePingen thanks - re: the template - understood.

**Comment by bmoore-msft** [comment]
@RenePingen - did you get a chance to check this with a new PS version?

**Comment by bmoore-msft** [comment]
Closing abandoned
