### ISSUE TITLE
"Virtual Machines Should Not Be Preview" fails for scale set

### ISSUE THREAD

**Issue by amergey** [Azure/arm-ttk#61]
When a template is creating a scale set, following test is failing :

_Virtual Machines Should Not Be Preview (1 ms)                                                                                                                                                               Virtual machine resource [variables('vScaleSetName')] has no image to reference_

It should not, my guess is in scale set image reference is given through 
_"virtualMachineProfile": {
          "storageProfile": {
            "osDisk": {
              "caching": "ReadWrite",
              "createOption": "FromImage"
            },
            "imageReference": "[variables('customImage')]"
          }_

The test is probably looking for **storageProfile** as it is defined for vm

**Comment by bmoore-msft** [comment]
This is true for VMs as well

@StartAutomating  #4054 in the old AzDO repo

**Comment by bmoore-msft** [comment]
I think we finally fixed this one #215
