### ISSUE TITLE
Location must not be Hardcoded Regression

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#610]
In the very latest release of ARM TTK for The Location must not be hardcoded rule.

TTK Release - https://github.com/Azure/arm-ttk/releases/tag/20220311

Repo Template - https://github.com/drewkg/Azure/blob/main/ARM/Resource/AutomationAccountWebHook/azureDeploy.json

I have confirmed that the previous version of ARM TTK did fail this template, but the latest version the template fails the Location rule.

**Comment by danielecazzari** [comment]
I'm also experiencing the same issue with latest version.
I got:
    [-] Location Should Not Be Hardcoded (944 ms)  
         mainTemplate.json must use the location parameter, not resourceGroup().location or deployment().location        (except when used as a default value in the main template)    

On mainTemplate.json where resourceGroup().location is only used as default value.

**Comment by Lkraehen** [comment]
Also seeing this test fail this morning 

      [-] Location Should Not Be Hardcoded 49ms
        WriteErrorException: azuredeploy.json must use the location parameter, not resourceGroup().location or deployment().location (except when used as a default value in the main template)
        at <ScriptBlock>, D:\a\1\a\arm-ttk\arm-ttk\testcases\deploymentTemplate\Location-Should-Not-Be-Hardcoded.test.ps1: line 94
        at Test-Case, D:\a\1\a\arm-ttk\arm-ttk\Test-AzTemplate.ps1: line 254
        at <ScriptBlock>, D:\a\1\a\arm-ttk\arm-ttk\Test-AzTemplate.ps1: line 471

**Comment by v-rucdu** [comment]
Hey, Even we are facing same issue since 2 days and found the fix with the recent code changes.
The variable is named as **paramSection** instead of param**s**Section. 

![image](https://user-images.githubusercontent.com/73389082/158592547-ee111070-5dc6-45fd-9b4e-e32f456295fa.png)

**Comment by spoelly** [comment]
Why wait and just create a PR ;)

**Comment by bmoore-msft** [comment]
fixed in #611 - the unit tests for this particular test where not running, so that was fixed in #612

@v-rucdu - thanks for the debug
@spoelly - thanks for the PR

**Comment by bmoore-msft** [comment]
oh - and this is in 0.5
