### ISSUE TITLE
arm-ttk reports unexpected error - "A parameter cannot be found that matches parameter name 'ErrorId'".

### ISSUE THREAD

**Issue by KrishnaG-MSFT** [Azure/arm-ttk#616]
arm-ttk reports unexpected error - "A parameter cannot be found that matches parameter name 'ErrorId'".

CreateUIDefinition
[-] Outputs Must Be Present In Template Parameters (22 ms)
A parameter cannot be found that matches parameter name 'ErrorId'.
A parameter cannot be found that matches parameter name 'ErrorId'.
A parameter cannot be found that matches parameter name 'ErrorId'.

I have tested using the attached files and was getting the error. However, I was able to overcome the error if I remove below 3 lines under the outputs property.

"startIP": "[steps('clusterDetails1').startIP]",
"nodeCount": "[steps('clusterDetails2').nodeSection.nodeCount]",
"storagePoolSize": "[steps('clusterDetails2').storageSection.storagePoolSize]",

Note that startIP, nodeCount and storagePoolsize are the only int parameters in mainTemplate.json. So, 2 questions here:

1. Why is the error not descriptive enough to clarify that the error is related to above highlighted 3 lines? What does 'ErrorId' mean? It doesn't help to understand why the error is.
2. Why outputs property doesn't allow to map these (startIP, nodeCount and storagePoolsize) int parameters related elements from steps property? What is the reason behind it?

Please provide your insights on the above 2 questions. Thanks.

[mainTemplate.json.txt](https://github.com/Azure/arm-ttk/files/8324780/mainTemplate.json.txt)
[createUiDefinition.json.txt](https://github.com/Azure/arm-ttk/files/8324782/createUiDefinition.json.txt)

**Comment by bhavenst** [comment]
Same error here and unable to figure out where it is coming from.

  CreateUIDefinition
    [-] Outputs Must Be Present In Template Parameters (195 ms)
        A parameter cannot be found that matches parameter name 'ErrorId'.

**Comment by bmoore-msft** [comment]
it's should be coming from a type mismatch error between a CUID output and a template param type...

#615 should have a fix

**Comment by bhavenst** [comment]
Thanks!  I did subsequently figure out which param it was coming from and fix it by trial and error, but good to know the error msg should be improved in the future.
