### ISSUE TITLE
False Positive: 'IDs Should Be Derived From ResourceIDs' when using Microsoft.insights/webtests

### ISSUE THREAD

**Issue by NickSpag** [Azure/arm-ttk#620]
In an [app insights webtest template](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/webtests?tabs=json), the `Locations` property requires an array of `Id`s, which come from a set of [population tags](https://docs.microsoft.com/en-us/azure/azure-monitor/app/monitor-web-app-availability#location-population-tags). 

I cannot find a way to access those population tags in any way other than hardcoding them, so the test fails.

Another note: this test is mandatory as part of the marketplace pipeline. Given the nature of it (simply checks anything ending in id as I understand it?), is it reliable enough to be included as a gatekeeping test?

**Comment by bmoore-msft** [comment]
s/b fixed in #627
