### ISSUE TITLE
TestTemplate.sh does not exit with a non-zero exit code when a test fails

### ISSUE THREAD

**Issue by malscent** [Azure/arm-ttk#633]
On MacOS, when executing TestTemplate.sh against a template with a failed test (Fails:  1) the TestTemplate.sh file does not exit with a non-zero exit code.

I've also experienced this in a ubuntu docker container and a powershell (Ubuntu) docker container from Microsoft.

**Comment by bmoore-msft** [comment]
s/b fixed in #634 (and an adjacent push to master)
