### ISSUE TITLE
[parameters('anyParameter')[copyIndex()]] is incorrectly treated as an array and throws type mismatch error

### ISSUE THREAD

**Issue by sahitya-bhandarkar** [Azure/arm-ttk#635]
I am passing an object parameter to the nested template example array[i] (with copyIndex in picture).
The ARM ttk test thinks of this parameter as an array.
 
The bicep files I have mentioned below are for reference only. I am running the ARM ttk **Test-AzTemplate** on the the compiled json file.

---------------------------------------------------------------
moduletest.bicep
---------------------------------------------------------------

module roleAssignments './roleAssignments.bicep' = [for (roleAssignment,index) in roleAssignmentCollection: {
  name: 'roleAssignments-${index}'
  scope: resourceGroup(roleAssignment.resourceGroupName)
  params: {
    roleAssignment: roleAssignment
  }
  
---------------------------------------------------------------
roleAssignments.bicep
---------------------------------------------------------------
param roleAssignment object

var storageAccountRole = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleAssignment.roleId)

resource storageRoleAssignment 'Microsoft.Authorization/roleAssignments@2020-10-01-preview' = {
 .
 .
 .
 
 
 ---------------------------------------------------------------
 az bicep build - converted json
 ---------------------------------------------------------------
 .
 .
 .
 {
  "copy": {
	"name": "roleAssignments",
	"count": "[length(parameters('roleAssignmentCollection'))]"
  },
  "type": "Microsoft.Resources/deployments",
  "apiVersion": "2020-10-01",
  "name": "[format('roleAssignments-{0}', copyIndex())]",
  "resourceGroup": "[parameters('roleAssignmentCollection')[copyIndex()].resourceGroupName]",
  "properties": {
	"expressionEvaluationOptions": {
	  "scope": "inner"
	},
	"mode": "Incremental",
	"parameters": {
	  **"roleAssignment": {
		"value": "[parameters('roleAssignmentCollection')[copyIndex()]]"
	  },**
	  "webAppPrincipalId": {
		"value": "[reference(resourceId('Microsoft.Web/sites', parameters('webAppName')), '2021-01-15', 'full').identity.principalId]"
	  },
	  "webAppName": {
		"value": "[parameters('webAppName')]"
	  }
	},
	"template": {
	  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
	  "contentVersion": "1.0.0.0",
	  "metadata": {
		"_generator": {
		  "name": "bicep",
		  "version": "0.5.6.12127",
		  "templateHash": "7013217532408887024"
		}
	  },
	  "parameters": {
		**"roleAssignment": {
		  "type": "object"**
		},
.
.
.

 ---------------------------------------------------------------
 ARM TTK error
 ---------------------------------------------------------------
 
 D:\a\1\s\arm-template-toolkit\arm-ttk\testcases\deploymentTemplate\Parameter-Types-Should-Be-Consistent.test.ps1 : Type Mismatch: Parameter 'roleAssignment' in nested template '[format('roleAssignments-{0}', copyIndex())]' is defined as object, but the parent template defines it as array).
At D:\a\1\s\arm-template-toolkit\arm-ttk\Test-AzTemplate.ps1:252 char:21
+                     . $myModule $TheTest @testInput 2>&1 3>&1
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (@{JSONPath=resource…ers.roleAssignment}:PSObject) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Inconsistent.Parameter,Parameter-Types-Should-Be-Consistent.test.ps1
##[error]Script failed with exit code: 1

**Comment by bmoore-msft** [comment]
Notes from triage:

Type mismatch is the TTK error (not a PS error)... we're only finding the array param reference, not the case of looking up an element.  So...

If we find a parameter that is of type ```array``` *and* that reference is followed by an index, then at the point we have to skip the check, since we have no type information:

```json
"parameters": {
  "roleAssignment": {
  "value": "[parameters('roleAssignmentCollection')[copyIndex()]]"
},
```

Note this will also be true of object property references:

```json
"parameters": {
  "roleAssignment": {
  "value": "[parameters('someObject').someProperty]"
},
```
and dictionary objects:

```json
"parameters": {
  "roleAssignment": {
  "value": "[parameters('someDictionary')['someKey']]"
},
```

So if we ever see ```[``` or ```.``` follow the param reference - we should stop evaluating.
