### ISSUE TITLE
groupName in output is replaced with folderName whenever a test fails

### ISSUE THREAD

**Issue by jeffpatton1971** [Azure/arm-ttk#639]
Team,

Using this tool within one of my repos (https://github.com/ArmReference/storage-storageAccounts) I believe it correctly detects the azuredeploy.json and finds the referenced files, and iterates over them all, but there are a few issues I'm running into:

1. Error messages are output with no indication of which file the error occurred in. While this repo has only 22 templates, there will be repos with significantly more, and tracking down which file had an issue will become tedious.
2. It would be nice to suppress the pass messages to allow me to focus on where I need to perform actual work. The cmdlet lacks documentation, so I'm unsure if I can suppress those; a cursory look over the get-help -full output, and I don't see a parameter that implies this.

**Comment by bmoore-msft** [comment]
re #1 - the file being tested is at the start of the output - so the path to the file is shown once.  Nested templates will show the deploymentName.  One thing I did notice though, is that any time there is a failure in a test, the group name is replaced with the folder name.  The text of the magenta line should be the same as the next line (pass or fail) but when an error is found it reverts to the foldername - which for these tests is ```deploymentTemplate``` which is pretty ambiguous.  I took a quick look at the code and I can't figure out how that's happening so we'll have to throw this on the backlog.

![image](https://user-images.githubusercontent.com/10090014/169610118-fb0cadb5-1425-4f61-9425-8c8aa3c1abff.png)

re #2 - I don't know that we'd want to allow suppression but you can programmatically reason over the output if you wanted to add that layer... so dump the output to a var, then go through that var.

LMK if you're seeing anything different to the above...

**Comment by jeffpatton1971** [comment]
I can get behind writing some one-off logic for suppressing success messages. Would you have an eta on the first issue you placed on the backlog? Is there something i can do to assist?

**Comment by bmoore-msft** [comment]
> I can get behind writing some one-off logic for suppressing success messages. Would you have an eta on the first issue you placed on the backlog? Is there something i can do to assist?

You mean #1 above where the group name is getting replaced?  I'm happy to have a PR for that one if you want to dig into the bowels for it...

**Comment by bmoore-msft** [comment]
@StartAutomating

**Comment by StartAutomating** [comment]
@bmoore-msft this looks interesting.  Let's determine if the framework is returning the wrong data for the failure, or if the failure is being incorrectly formatted (it should be one or the other)

**Comment by StartAutomating** [comment]
We should close this out as the fix went in in June.
