### ISSUE TITLE
False Alarm: "Property: "connectorId" must use one of the following expressions for an resourceId property

### ISSUE THREAD

**Issue by Chandu5140** [Azure/arm-ttk#640]
In the following segment, we are popping this error, Property: "connectorId" must use one of the following expressions for an resourceId property

Changing this to something redrived from resoureceId, makes the template fail to run. I believe there is a regex bug here, triggered by the presence of "Id", in the "connectorId" field.

![image](https://user-images.githubusercontent.com/93767495/163706503-72bb408b-9cc5-401e-8e73-286948211cec.png)

**Comment by bmoore-msft** [comment]
@Chandu5140 - this should have been fixed in #641 which was merged few days after this...  should be released in 0.9 later today
