### ISSUE TITLE
Test case for roleDefinitionId is failing in IDs-Should-Be-Derived-From-ResourceIDs.test.ps1. Getting error despite using "variables"

### ISSUE THREAD

**Issue by msopariw** [Azure/arm-ttk#647]
Getting error 
  deploymentTemplate
    [-] IDs Should Be Derived From ResourceIDs (65 ms)
        Property: "roleDefinitionId" must use one of the following expressions for an resourceId property:
            extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid

Despite roleDefinitionId is using "variables" while assigning role in ARM Template

                            "properties": {
                                "roleDefinitionId": "[variables('contributorRole')]",
                                "description": "Contributor access",
                                "principalId": "[reference(resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', variables('userMgdIndentity'))).principalId]",
                                "principalType": "ServicePrincipal"
                            }

**Comment by bmoore-msft** [comment]
@msopariw - can you share the entire template?  Or the minimum for a repro?

**Comment by StartAutomating** [comment]
@msopariw it's possible that the variable this points to uses concat.  If you can provide a whole template or a partial repro we can investigate.

**Comment by bmoore-msft** [comment]
Going to go ahead and close this - feel free to reopen if you can attach a repro template
