### ISSUE TITLE
ARM-TTK should support skipping tests based on metadata in templates

### ISSUE THREAD

**Issue by ReneRebsdorf** [Azure/arm-ttk#663]
When using ARM-TTK it would be great to be able to skip tests, but only for partial sections of the templates.

While most linters support skipping tests for a portion of the file based on comments, this doesn't work for bicep as comments are not kept due to the bicep-to-arm conversation.

Instead I suggest a metadata is established, and scoped at the deployment scopes, so that we when we create nested deployments where we can as an example allow 'hard-coded location' for one bicep module file, but not all files (or one deployment scope but not all when working directly with arm template files).

To allow for better control this should either support disable and enable behavior and inherit through scopes, or not support inheritance of skipped tests at all.

**Comment by bmoore-msft** [comment]
@ReneRebsdorf - what granularity are you thinking?  skip a certain line of the file?  skip a test one the file? etc?

**Comment by ReneRebsdorf** [comment]
@bmoore-msft Just realised I never replied to this, almost 2 years ago now. Sorry.

I'm thinking the scope would be for the affected resource, so maybe a metadata property could be used.
Maybe an implementation has already been made since July 10, 2022?

**Comment by ReneRebsdorf** [comment]
We have since this post moved to Bicep which has disable-next-line and moved to rely on bicep's rule tests + psrule is favor of arm-ttk

I recommend others to do the same, and as this repos readme states:
"
Note: Starting with the 0.10 release, [Bicep](https://github.com/Azure/bicep) now contains all of the deploymentTemplate test cases included in the TTK. We will begin moving the investment in new tests to the Bicep linter. The TTK will remain available to support available JSON and createUiDefinition scenarios.
"
I thus see no value in this issue and is closing it.
