### ISSUE TITLE
Microsoft.OperationalInsights/workspaces uses a preview version ( 2021-12-01-preview ) and there are more recent versions available.

### ISSUE THREAD

**Issue by kaigalmane** [Azure/arm-ttk#674]
While executing the unit test with Log Analytics Workspace ARM template, an error was thrown as below. As per [Microsoft documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/workspaces?pivots=deployment-language-arm-template) we could see that the latest version is the one we used as of now.

![image](https://user-images.githubusercontent.com/60817964/185384079-d40e245f-e3e4-400a-b9af-b2d46c15f6b1.png)

**Comment by bmoore-msft** [comment]
@kaigalmane - can you attach the template or a resource snippet

**Comment by bhamorszky-kx** [comment]
Azure/bicep#8172

**Comment by bhamorszky-kx** [comment]
@adrianmo @anagyzambo-kx

**Comment by bhamorszky-kx** [comment]
Documentation and bicep:

- 2020-03-01-peview
- 2020-08-01
- 2020-10-01
- 2021-12-01-preview

arm-ttk:

- 2021-12-01-preview
- 2022-10-01
- 2022-10-01

arm-deploy:

- 2017-04-26-preview
- 2020-03-01-preview
- 2020-08-01
- 2021-12-01-preview
- 2022-10-01

check the bicep issue for screenshots

**Comment by kaigalmane** [comment]
> @kaigalmane - can you attach the template or a resource snippet

```
resource loganalytics_workspace_resource 'Microsoft.OperationalInsights/workspaces@2021-12-01-preview' = {
  name: loganalyticsName
  location: location
  tags: tags
  properties: {
    retentionInDays: 30
    sku: {
      name: 'PerGB2018'
    }
  }
}
```

**Comment by bmoore-msft** [comment]
Got it - thanks...  It looks like the TTK is reporting accurately in this case.  The TTK pulls apiVersions from the service, specifically the [```/providers```](https://docs.microsoft.com/en-us/rest/api/resources/providers/get?tabs=HTTP) api...  You can query a specific resourceType by:

```powershell
(Get-AzResourceProvider -ProviderNamespace Microsoft.OperationalInsights | select -expand resourceTypes | where-object{$_.resourceTypeName -eq "workspaces/tables"}).apiVersions
```

Though it is a bit strange that the latest is in the future.  Does it work if you use that version?

FWIW, both docs and bicep use published specs/types...  given this version is in the future I could see those not being live yet.

**Comment by bhamorszky-kx** [comment]
we had a lot of tries with it. it will take some time to look it up, but I think that future had a concurrency issue.

**Comment by bhamorszky-kx** [comment]
![2022-08-29_21-51](https://user-images.githubusercontent.com/107194215/187286305-3ac838e1-0628-4da9-bd39-2204aa1897bc.png)

**Comment by bhamorszky-kx** [comment]
so workspace and tables have a different version if you split it up?

**Comment by bhamorszky-kx** [comment]
this looks fine in the VSCode:
![2022-08-29_22-03](https://user-images.githubusercontent.com/107194215/187288246-aed04c47-4519-42f8-8b60-4f96b23f1061.png)
(but it is failing)
but if I choose the latest stable:
![2022-08-29_22-05](https://user-images.githubusercontent.com/107194215/187288426-e22c9af4-dfaa-4dd0-88f6-a22d0ac86432.png)

**Comment by bmoore-msft** [comment]
Oh sorry - I meant whether you're allowed to use the ```2022-10-01``` apiVersion against the service. IOW, if you use ```2022-10-01```, does the deployment succeed?

re: the bicep error saying you have to use the ```existing``` keyword - I have not seen that before can you add that to the bicep issue?

**Comment by anagyzambo-kx** [comment]
It does not work for `Microsoft.OperationalInsights/workspaces/tables@2022-10-01`
We get:
```
  "error": {
    "code": "BadRequest",
    "message": "Unsupported api version - 2022-10-01"
  }
```

**Comment by bmoore-msft** [comment]
@anagyzambo-kx - thanks... that's a different error message than what is normally shown when an apiVersion isn't available (that error message will tell you what is available).  I think what we're seeing, given the apiVersion is in the future and not working, is that it's only available to customers that enable the feature (whether that's private or public IDK).

A few options I can think of:
1) special case this apiVersion in the TTK (can of worms)
2) ignore the TTK error for now as it should resolve when the apiVersion goes public
3) contact support to let them know the apiVersion is "live" but not working - this will probably take a ton of explaining to the support rep and the Insights team will probably ignore if it's transient.

I'd like to go with #2 for the time being but open to other suggestions...
