### ISSUE TITLE
{Microsoft.SecurityInsights/dataConnectors uses a preview version (              2022-08-01-preview ) and there is a non-preview version for that a             piVersion available.

### ISSUE THREAD

**Issue by JonasCordsen** [Azure/arm-ttk#679]
Our ArmTTK test are failing because of the following error:
Errors    : {Microsoft.SecurityInsights/dataConnectors uses a preview version (
             2022-08-01-preview ) and there is a non-preview version for that a
            piVersion available.}
Warnings  : {}
Output    : {Valid Api Versions:
                    2022-08-01
                    2022-08-01-preview
                    2022-08-01
                    2022-07-01-preview
                    2022-06-01-preview
                    2022-05-01-preview
                    2022-04-01-preview
                    2022-01-01-preview
                    2021-10-01-preview
                    2021-10-01
                    2021-09-01-preview
                    2021-03-01-preview

The issue is, that we need to preview version of the API as there are funktions that are only in that API
Can we get so that we can get the preview api without disabling all API tests?
https://docs.microsoft.com/en-us/azure/templates/microsoft.securityinsights/2022-08-01/dataconnectors?pivots=deployment-language-bicep

**Comment by bmoore-msft** [comment]
Not sure I understand the config you want... some bg, the pattern is a bit odd, that the preview version of a GA'd version has more/necessary functionality.  That would be an anti-pattern in ARM, but it's not the first I've seen (however rare).

In the TTK we wouldn't want a global rule for allowing the preview, so how would you envision excepting the case?

**Comment by JonasCordsen** [comment]
Hello @bmoore-msft 

I want to still be able to run the api version checks, is there a possibility to use some kind og exclude when you need a specific API version for some resource?

**Comment by bmoore-msft** [comment]
Ok, in #687 I have a prototype of something that may work for this specific test case, if you want to take a look at that PR - specifically the test case: https://github.com/Azure/arm-ttk/blob/master/unit-tests/apiversions-should-be-recent/Pass/old-apiVersion-skipped.json#L9

Feel free to reopen if needed.
