### ISSUE TITLE
cannot extract innerTemplates with prereqs

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#686]
Run ttk on this sample:

https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.machinelearningservices/machine-learning-job-create-sweep-job

It seems to treat the prereq.azuredeploy.json file as a main template and perhaps a nested template.  The pattern is not uncommon in quickstarts but with a quick test I could not repro it on another/similar sample.

**Comment by bmoore-msft** [comment]
@StartAutomating

**Comment by StartAutomating** [comment]
@bmoore-msft looks interesting, please assign it to me.

**Comment by bmoore-msft** [comment]
maybe related to #685 as well... that test case should fail and it's not failing... thinking we may believe we're mainTemplate still.
