### ISSUE TITLE
More information on the error "output location does not exist in template.parameters" 

### ISSUE THREAD

**Issue by mwilcox12014** [Azure/arm-ttk#693]
We are running:

PS Test-AzTemplate -TemplatePath D:\Documents\ARMTest

the ARMTest file: 

ARMTest

{
    "$schema": "https://schema.management.azure.com/schemas/0.1.2-preview/CreateUIDefinition.MultiVm.json#",
    "handler": "Microsoft.Azure.CreateUIDef",
    "version": "0.1.2-preview",
    "parameters": {
        "outputs": { 
            "location": {
                "type": "string",
                "defaultValue": "[resourceGroup().location]"
              },
              "location": "[location()]"
        }
    }
}

and receiving this error: 

 Outputs Must Be Present In Template Parameters                                                                            
[-] Outputs Must Be Present In Template Parameters (4 ms)                                                                   
output location does not exist in template.parameters  

Can the team provide more information on how to resolve this error ? thank you

**Comment by mwilcox12014** [comment]
I read the doc (https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/createuidefinition-test-cases#include-control-outputs-in-template-parameters)  and found a way to resolve the problem.  Yup, read the doc :) 

Hit other issues and used this doc to find errors in the other json files. 
https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/template-test-cases

Screenshot mapping my ttk error output to the doc that helped w/ resolution at:
![image](https://user-images.githubusercontent.com/7051133/192908660-ed004f2e-23fb-48a9-b9bb-353cf6aa6019.png)

**Comment by bmoore-msft** [comment]
Ok, sounds like you made the connection - I'll close the issue, feel free to reopen if needed.
