### ISSUE TITLE
arm-ttk.zip for .16 indicates version .15 ? 

### ISSUE THREAD

**Issue by mwilcox12014** [Azure/arm-ttk#694]
When you download arm-ttk.zip from  https://github.com/Azure/arm-ttk/releases/tag/20220926 which should be .16 release 
we receive the message 'installed version is .15 ?'

PS D:\Documents\ARM Template for IPCoSell\arm-ttk\arm-ttk> Import-Module .\arm-ttk.psd1
A newer version of the ARM-TTK is available at: https://github.com/Azure/arm-ttk/releases
Installed Version: 0.15
Latest Version: 0.16

**Comment by bmoore-msft** [comment]
Thanks - I think I got it...
