### ISSUE TITLE
VM Size test does not recognize params in object vars

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#695]
Run the ttk on this sample:
https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/sharepoint/sharepoint-adfs

It looks like we may have regressed something in #682

**Comment by bmoore-msft** [comment]
@StartAutomating

**Comment by StartAutomating** [comment]
@bmoore-msft got repro working.

**Comment by veezhang** [comment]
@StartAutomating @bmoore-msft 
We are publishing our product, and this issue caused the test to fail.
I'am look forward to you fixing this problem as soon as possible.
```
  VM Size Should Be A Parameter
    [-] VM Size Should Be A Parameter (61 ms)
        VMSize parameter must be declared for the parent template
```

**Comment by spoelstraethan** [comment]
We've encountered an issue with this as well, we have a top level template and inner template using a parameter name of `size` instead of `vmSize`, but it maps into the `hardwareProfile.vmSize` property of the inner template, but it is reporting a failure even though the `vmSize` is coming from a parameter.

**Comment by veezhang** [comment]
Due to this, our publish  plan has been delayed by more than a month.

**Comment by veezhang** [comment]
We had a rather poor experience.😠😠

**Comment by galiacheng** [comment]
We ran into the same issue, see https://github.com/Azure/arm-ttk/issues/712， which required huge changes to our templates (https://github.com/oracle/weblogic-azure/pull/215) .

**Comment by veezhang** [comment]
It seems that many people have similar problems, please speed up.

**Comment by MegaByte875** [comment]
I also with the problem, please fix it asap, I hope your efficiency like AWS.

**Comment by GeordieGuy** [comment]
This appears to be back. 

`D:\a\1\s\arm-ttk\testcases\deploymentTemplate\VM-Size-Should-Be-A-Parameter.test.ps1 : VM Size for resourceType '  ' 
named '  ' must be a parameter
At D:\a\1\s\arm-ttk\Test-AzTemplate.ps1:253 char:21
+                     . $myModule $TheTest @testInput 2>&1 3>&1
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,VM-Size-Should-Be-A-Parameter.test.ps1`


On code where the VM size is declared as;

`var referenceImage = {
  windows: {
    publisher: 'MicrosoftWindowsServer'
    offer: 'WindowsServer'
    sku: '2019-Datacenter'
    version: 'latest'
    VMsize: 'Standard_D4s_v3'
  }
}`

**Comment by vidapour** [comment]
@GeordieGuy Can you provide a template where we can replicate this issue so we can determine what is causing the error? Thanks!

**Comment by vidapour** [comment]
@GeordieGuy it seems that you are hardcoding the VMSize to 'Standard_D4s_v3'. The VMSize property should take in a parameter.

**Comment by GeordieGuy** [comment]
> @GeordieGuy it seems that you are hardcoding the VMSize to 'Standard_D4s_v3'. The VMSize property should take in a parameter.

No. Btw, this issue is 5 months old. I barely remember what it was.

**Comment by GeordieGuy** [comment]
> @GeordieGuy it seems that you are hardcoding the VMSize to 'Standard_D4s_v3'. The VMSize property should take in a parameter.

If I think back to 5 months ago when I was having this problem, declaring a variable shouldn't require me to populate it with other parameters. ARMTTK thinks this declaration is creating a VM with a hardcoded SKU, it isn't, it's defining a variable.
