### ISSUE TITLE
Microsoft.OperationalInsights/workspaces/linkedServices - Api versions must be the latest or under 2 years old (730 days)

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#701]
Using this resource definition in ARM

    {
      "name": "[variables('logAnalyticsWorkSpaceName')]",
      "type": "Microsoft.OperationalInsights/workspaces",
      "apiVersion": "2022-10-01",
      "location": "[parameters('location')]",
      "properties": {
        "sku": {
          "name": "PerGB2018"
        },
        "retentionInDays": 30
      },
      "resources": [
        {
          "name": "[concat(variables('logAnalyticsWorkSpaceName'), '/' , 'Automation')]",
          "type": "Microsoft.OperationalInsights/workspaces/linkedServices",
          "apiVersion": "2020-08-01",
          "dependsOn": [
            "[variables('logAnalyticsWorkspaceName')]",
            "[variables('automationAccountName')]"
          ],
          "properties": {
            "resourceId": "[resourceId('Microsoft.Automation/automationAccounts', variables('automationAccountName'))]"
          }
        }
      ]
    }

I am getting the following failed test

      [-] apiVersions Should Be Recent 67ms
        RuntimeException: Api versions must be the latest or under 2 years old (730 days) - API version 2020-08-01 of Microsoft.OperationalInsights/workspaces/linkedServices is 796 days old
        at <ScriptBlock>, C:\Users\drewk\Source Code\GitHub\drewkg\Azure\ARM-TTK\arm-ttk\Test-AzTemplate.ps1: line 481  

Checking against Azure, this is the right API Version

(Get-AzResourceProvider -ProviderNamespace Microsoft.OperationalInsights | select -expand resourceTypes | where-object{$_.resourceTypeName -eq "workspaces/linkedServices"}).apiVersions
2020-08-01
2020-03-01-preview
2019-08-01-preview
2015-11-01-preview

**Comment by bmoore-msft** [comment]
@StartAutomating - this is a case where the latest apiVersion is > 2 years old...  since it's the latest version it should still be in the list of valid versions.

**Comment by StartAutomating** [comment]
@bmoore-msft I'll take a look
