### ISSUE TITLE
VM Size Should Be A Parameter named "vmSize"?

### ISSUE THREAD

**Issue by galiacheng** [Azure/arm-ttk#712]
Hello team, does the rule work as expected to restrict the parameter name as `vmSize`? Could you share more information why the parameter name must be `vmSize`?

Here is a test template:

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "vmSizeSelect": {
      "type": "object"
    },
    "_artifactsLocation": {
      "type": "string"
    },
    "_artifactsLocationSasToken": {
      "type": "securestring"
    }
  },
  "variables": {
    "vmTemplateLink": "[concat(parameters('_artifactsLocation'),'common/vm.json', parameters('_artifactsLocationSasToken'))]"
  },
  "resources": [
    {
      "name": "[concat('Deploy_VM', copyIndex())]",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2020-10-01",
      "properties": {
        "mode": "Incremental",
        "templateLink": {
          "uri": "[variables('vmTemplateLink')]"
        },
        "parameters": {
          "vmSize": {
            "value": "[parameters('vmSizeSelect')]"
          }
        }
      }
    }
  ]
}

```

To test the template: `bash Test-AzTemplate.sh -TemplatePath <path-to>/test.json -Test VM-Size-Should-Be-A-Parameter`

**Comment by spoelstraethan** [comment]
There was a change in https://github.com/Azure/arm-ttk/pull/682 that seems to have caused this regression. They are tracking another issue in #695 about this as well.

**Comment by StartAutomating** [comment]
@bmoore-msft this appears related to our other VMSize issues.  Please assign me.

**Comment by StartAutomating** [comment]
@galiacheng This should have been fixed with the latest round of VM Size Changes.  Please confirm if it is working as you'd expect now.
