### ISSUE TITLE
'URIs Should Be Properly Constructed' issue

### ISSUE THREAD

**Issue by v-gsapaharam** [Azure/arm-ttk#713]
With the latest Version ( 2.210.0) properly constructed URIs are failing on the URI check with the following error:

    [-] URIs Should Be Properly Constructed (39 ms) 
##[error]        Function 'concat' found within 'keyVaultUri' 

An example template that should pass, but fails:

-----
   "resources": [
       {
           "type": "Microsoft.Databricks/workspaces",
           "apiVersion": "2022-04-01-preview",
           "name": "[parameters('workspaceName')]",
            "location": "[parameters('location')]",
           "sku": {
               "name": "[parameters('pricingTier')]"
           },
           "properties": {
               "managedResourceGroupId": "[concat(subscription().id, '/resourceGroups/', variables('managedResourceGroupName'))]",
               "encryption": {
                   "entities": {
                       "managedDisk": {
                           "keySource": "Microsoft.Keyvault",
                           "keyVaultProperties": {
                               "keyVaultUri": "[concat('https://', parameters('keyVaultName'), environment().suffixes.keyvaultDns)]",
                               "keyName": "[parameters('keyName')]",
                               "keyVersion": "[parameters('keyVersion')]"
                           },
                           "rotationToLatestKeyVersionEnabled": "[parameters('enableAutoRotation')]"
                       }
                   }
               }
           }
       },
----

Here is our PR: https://github.com/Azure/azure-quickstart-templates/pull/12949
Piepline Logs: https://dev.azure.com/azurequickstarts/azure-quickstart-templates/_build/results?buildId=114654&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=14b22f05-782e-55fa-3e59-b66c82f514a9&l=157

**Comment by v-gsapaharam** [comment]
Hi ARM Team, would it be possible to investigate this issue?

**Comment by bmoore-msft** [comment]
The code should use the `uri()` function to create a uri, e.g.

```json
"keyVaultUri": "[uri(concat('https://', parameters('keyVaultName'), environment().suffixes.keyvaultDns), '/')]",
```

**Comment by v-gsapaharam** [comment]
Thanks ***@***.***>, will commit the suggested changes, thanks for your pointers.


Thanks,
Ganesh
