### ISSUE TITLE
Incorrect Flagging of apiVersion for Resource Group

### ISSUE THREAD

**Issue by dvdmtw98** [Azure/arm-ttk#732]
### Description

`arm-ttk` is flagging the API version field of Resource Group as invalid/ not found even though its the latest version as mentioned in the documentation

### Output

![RG Validation](https://user-images.githubusercontent.com/31100937/219922979-99aacfb9-9672-4abf-8d83-eb9b40a26fdd.png)

### ARM Template Definition

```json
{
	"name": "[parameters('resourceGroupName')]",
	"type": "Microsoft.Resources/resourceGroups",
	"apiVersion": "2022-09-01",
	"location": "[parameters('location')]",
	"tags": "[parameters('resourceGroupTags')]"
}
```

### Resource Group Definition (Documentation)

**Link to Documentation**: [Resource Group Schema Definitation](https://learn.microsoft.com/en-us/azure/templates/microsoft.resources/resourcegroups?pivots=deployment-language-arm-template)

![Documentation](https://user-images.githubusercontent.com/31100937/219923044-03b887e0-7ba2-4932-8e2f-16c9e0bc62ea.png)

**Comment by mariesetnes** [comment]
I am experiencing similar problems with the following apis:

The apiVersion 2023-01-01 was not found for the resource type: Microsoft.RecoveryServices/vaults
The apiVersion 2023-01-01 was not found for the resource type: Microsoft.RecoveryServices/vaults/backupFabrics/protectionContainers/protectedItems
The apiVersion 2022-09-01 was not found for the resource type: Microsoft.Resources/deployments

**Comment by vidapour** [comment]
These changes have been merged. Thank you!
