### ISSUE TITLE
NoPester flag does not exist in ARM-TTK PS module

### ISSUE THREAD

**Issue by samrobillard** [Azure/arm-ttk#75]
From the ReadMe [here](https://github.com/Azure/arm-ttk/tree/master/arm-ttk), you should be able to use the flag NoPester to be able to extract errors. This flag does not exist. To reproduce the error, simply run 'Test-AzTemplate -TemplatePath $path -NoPester

**Comment by bmoore-msft** [comment]
Thanks @samrobillard - we've updated the readme
