### ISSUE TITLE
The issue "The resource 'xxx' is not defined in the template" is not detected

### ISSUE THREAD

**Issue by qingshanJBHIFI** [Azure/arm-ttk#750]
### Issue

We used separate templates for different resource deployment, we put APIM in `apim.tempalte.json`:

```json
{
      "apiVersion": "2023-03-01-preview",
      "name": "[parameters('apimServiceName')]",
      "location": "[parameters('location')]",
      "type": "Microsoft.ApiManagement/service",
      "sku": {
        "name": "[parameters('sku')]",
        "capacity": "[parameters('skuCount')]"
      },
      "zones": "[parameters('availabilityZones')]",
      "identity": {
        "type": "SystemAssigned"
      },
}
```
and the diagnostics into `azuremonitor.template.json`:

```json
{
      "type": "Microsoft.ApiManagement/service/diagnostics",
      "apiVersion": "2022-09-01-preview",
      "name": "[concat(parameters('apimServiceName'), '/azuremonitor')]",
      "dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service/loggers', parameters('apimServiceName'), 'azuremonitor')]"
      ],
      "dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service', parameters('apimServiceName'))]"
      ],
      "properties": {
        "logClientIp": true,
        "alwaysLog": "allErrors",
        "loggerId": "[resourceId('Microsoft.ApiManagement/service/loggers', parameters('apimServiceName'), 'azuremonitor')]",
        "sampling": {
          "samplingType": "fixed",
          "percentage": "[parameters('samplingRate')]"
        }
    }
}
```

then we have a main tempalte to deploy those two tempates, in `azuremonitor.template.json` we added `dependsOn`, but the APIM service is not defined in the current template file, the deployment will fail. 

When I run the `arm-ttk`, it didn't report this error.

### Expectation

`arm-ttk` should be able to report this issue.

**Comment by vidapour** [comment]
TTK is meant to verify best-practices compliance. It does not check for syntax, dependencies, APIs, etc., for your services.

This is likely closer to what you're looking for: [https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-what-if?tabs=azure-powershell](https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-what-if?tabs=azure-powershell)

Thanks!
