### ISSUE TITLE
Does not work with Microsoft.KubernetesConfiguration/extensions apiVersion 2023-05-01    

### ISSUE THREAD

**Issue by KeithMnemonic** [Azure/arm-ttk#752]
When using a template with

            "type": "Microsoft.KubernetesConfiguration/extensions",
            "apiVersion": "2023-05-01",    

the following error is reported 

[?] apiVersions Should Be Recent (20 ms)
        The apiVersion 2023-05-01 was not found for the resource type: Microsoft.KubernetesConfiguration/extensions

but this API should pass per 

https://learn.microsoft.com/en-us/rest/api/kubernetesconfiguration/extensions/list?tabs=HTTP

Service:
Kubernetes Configuration
API Version:
2023-05-01

**Comment by vidapour** [comment]
This should show up as a warning in the TTK and should not block you if you are submitting the offer to be published. We have taken note of the issue and have added it to our backlog.

If this issue is blocking you please let us know. Thanks!

**Comment by KeithMnemonic** [comment]
I am not blocked but wanted to report it in case others run across this.

**Comment by psah434** [comment]
Should be fixed with 0.23
