### ISSUE TITLE
Add exception for policy definitions in "Template Should Not Contain Blanks"

### ISSUE THREAD

**Issue by samrobillard** [Azure/arm-ttk#76]
In Azure policy definitions, you sometime have to check against empty strings that will fail this test automatically even if it's wanted. For now, I skip this test but I was wondering if there was a better way to handle this use case or add an exception in the test itself.

Example from a policy definition:

{
  "value": "[[resourceGroup().tags[parameters('tagName')]]",
  "notEquals": ""
}

**Comment by bmoore-msft** [comment]
You can add an exception here: https://github.com/Azure/arm-ttk/blob/master/arm-ttk/testcases/deploymentTemplate/Template-Should-Not-Contain-Blanks.test.ps1#L27

**Comment by samrobillard** [comment]
I added the exception. https://github.com/Azure/arm-ttk/pull/84
I hope I did it correctly.

**Comment by bmoore-msft** [comment]
yep - thx
